# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: api-gateway/app/middleware/rate_limit_metrics.py
"""
Sliding-window IP rate limiter backed by Redis, with full metrics emission.
"""

import time
from fastapi import Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

from metrics.registry import RATE_LIMIT_HITS_TOTAL, RATE_LIMIT_REMAINING

_SERVICE       = "api-gateway"
_WINDOW_SECS   = 60
_MAX_REQUESTS  = 20         # tune via env var in prod


class RateLimitMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, redis_client, max_requests: int = _MAX_REQUESTS):
        super().__init__(app)
        self._redis    = redis_client
        self._max_reqs = max_requests

    async def dispatch(self, request: Request, call_next) -> Response:
        if request.url.path in {"/metrics", "/health"}:
            return await call_next(request)

        client_ip = request.client.host
        redis_key = f"rl:{client_ip}"

        # Atomic increment + TTL via pipeline
        pipe = self._redis.pipeline()
        pipe.incr(redis_key)
        pipe.ttl(redis_key)
        count, ttl = await pipe.execute()

        if ttl < 0:
            await self._redis.expire(redis_key, _WINDOW_SECS)
            ttl = _WINDOW_SECS

        remaining = max(0, self._max_reqs - int(count))

        RATE_LIMIT_REMAINING.labels(service=_SERVICE).set(remaining)

        if int(count) > self._max_reqs:
            RATE_LIMIT_HITS_TOTAL.labels(
                service=_SERVICE, client_ip=client_ip
            ).inc()
            return Response(
                content     = '{"detail":"IP rate limit exceeded"}',
                status_code = 429,
                media_type  = "application/json",
                headers     = {"Retry-After": str(max(ttl, 1))},
            )

        response = await call_next(request)
        response.headers["X-RateLimit-Remaining"] = str(remaining)
        response.headers["X-RateLimit-Reset"]     = str(int(time.time()) + max(ttl, 0))
        return response

