# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/circuit_breaker/breaker_registry.py

import pybreaker
from app.config import settings

_breakers: dict[str, pybreaker.CircuitBreaker] = {}

def get_breaker(bank_code: str) -> pybreaker.CircuitBreaker:
    key = bank_code.upper()
    if key not in _breakers:
        _breakers[key] = pybreaker.CircuitBreaker(
            fail_max      = settings.breaker_fail_max,
            reset_timeout = settings.breaker_reset_timeout,
            name          = f"breaker-{key}",
        )
    return _breakers[key]
