# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/config.py

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    # DynamoDB
    dynamodb_endpoint_url: str = "http://localstack:4566"
    dynamodb_table_name: str   = "ibts-transactions"
    aws_access_key_id: str     = "test"
    aws_secret_access_key: str = "test"
    aws_default_region: str    = "ap-south-1"

    # SQS
    sqs_endpoint_url: str  = "http://localstack:4566"
    sqs_queue_name: str    = "ibts-settlement-events"

    # Downstream services
    idempotency_guard_url: str = "http://idempotency-guard:8080"
    payment_router_url: str    = "http://payment-router:8081"
    bank_adapter_url: str      = "http://bank-adapter:8082"

    # App
    port: int = 8083

    class Config:
        env_file = ".env"

settings = Settings()
