# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/dynamo.py

import logging
import os
from datetime import UTC, datetime

import boto3
from boto3.dynamodb.conditions import Attr

from app.config import settings
from app.models import TxnRecord, TxnState
from shared.metrics.dynamo_tracker import TrackedDynamoTable

log = logging.getLogger(__name__)


# ── Module-level cached table ──────────────────────────────────────────────────
# Previously _table() created a new boto3 resource on every call — expensive.
# Now we build once at import time and reuse across all requests.
def _build_table() -> TrackedDynamoTable:
    raw = boto3.resource(
        "dynamodb",
        endpoint_url          = settings.dynamodb_endpoint_url,
        region_name           = settings.aws_default_region,
        aws_access_key_id     = settings.aws_access_key_id,
        aws_secret_access_key = settings.aws_secret_access_key,
    ).Table(settings.dynamodb_table_name)

    return TrackedDynamoTable(
        table      = raw,
        table_name = settings.dynamodb_table_name,
        service    = os.getenv("SERVICE_NAME", "payment-switch"),
    )


# Single instance — all functions below share this
_table = _build_table()


# ── Helpers ────────────────────────────────────────────────────────────────────
def _now() -> str:
    return datetime.now(UTC).isoformat()


# ── Write ──────────────────────────────────────────────────────────────────────
def write_txn(record: TxnRecord) -> None:
    record.created_at = _now()
    record.updated_at = record.created_at
    _table.put_item(Item=record.model_dump())             # ← auto-timed
    log.info("txn_id=%s state=%s written", record.txn_id, record.state)


# ── Update ─────────────────────────────────────────────────────────────────────
def update_state(
    txn_id:    str,
    state:     TxnState,
    bank_rrn:  str | None = None,
    bank_code: str | None = None,
    error:     str | None = None,
) -> None:
    expr  = "SET #s = :s, updated_at = :u"
    names = {"#s": "state"}
    vals  = {":s": state.value, ":u": _now()}

    if bank_rrn:
        expr += ", bank_rrn = :r";  vals[":r"] = bank_rrn
    if bank_code:
        expr += ", bank_code = :b"; vals[":b"] = bank_code
    if error:
        expr += ", #e = :err";      names["#e"] = "error"; vals[":err"] = error

    _table.update_item(                                    # ← auto-timed
        Key                       = {"txn_id": txn_id},
        UpdateExpression          = expr,
        ExpressionAttributeNames  = names,
        ExpressionAttributeValues = vals,
    )
    log.info("txn_id=%s → %s", txn_id, state)


# ── Read by primary key ────────────────────────────────────────────────────────
def get_txn(txn_id: str) -> dict | None:
    resp = _table.get_item(Key={"txn_id": txn_id})        # ← auto-timed
    return resp.get("Item")


# ── Read by idempotency key (scan — no GSI required) ──────────────────────────
def get_txn_by_idempotency_key(idempotency_key: str) -> dict | None:
    """
    Scan table for matching idempotency_key.
    No GSI required — acceptable for low-volume test/dev use.
    For production: replace with a GSI query on idempotency_key.

    NOTE: DynamoDB Limit caps items *scanned*, not returned —
    omitting it guarantees we don't miss the record in a small table.
    """
    resp  = _table.scan(                                   # ← auto-timed
        FilterExpression=Attr("idempotency_key").eq(idempotency_key)
    )
    items = resp.get("Items", [])
    return items[0] if items else None


# ── Read by bank RRN (scan — for duplicate debit detection) ───────────────────
def get_txn_by_bank_rrn(bank_rrn: str) -> dict | None:
    """
    Scan table for a matching bank_rrn (bank reference number).
    Used by payments.py to detect duplicate successful debits.

    Returns the FIRST matching record or None.

    NOTE: For high-volume production use, add a GSI on bank_rrn
    and replace this scan with a query:

        _table.query(
            IndexName="bank_rrn-index",
            KeyConditionExpression=Key("bank_rrn").eq(bank_rrn),
            Limit=2,
        )
    """
    resp  = _table.scan(                                   # ← auto-timed
        FilterExpression=Attr("bank_rrn").eq(bank_rrn),
    )
    items = resp.get("Items", [])

    if len(items) > 1:
        log.warning(
            "get_txn_by_bank_rrn: %d records share bank_rrn=%s — "
            "possible duplicate debit",
            len(items), bank_rrn,
        )

    return items[0] if items else None
