# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/dynamo.py

import boto3
import logging
from datetime import datetime, timezone
from boto3.dynamodb.conditions import Attr          # ← Attr, not Key (no GSI needed)
from app.config import settings
from app.models import TxnRecord, TxnState

log = logging.getLogger(__name__)


def _table():
    ddb = boto3.resource(
        "dynamodb",
        endpoint_url=settings.dynamodb_endpoint_url,
        region_name=settings.aws_default_region,
        aws_access_key_id=settings.aws_access_key_id,
        aws_secret_access_key=settings.aws_secret_access_key,
    )
    return ddb.Table(settings.dynamodb_table_name)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_txn(record: TxnRecord) -> None:
    record.created_at = _now()
    record.updated_at = record.created_at
    _table().put_item(Item=record.model_dump())
    log.info("txn_id=%s state=%s written", record.txn_id, record.state)


def update_state(
    txn_id: str,
    state: TxnState,
    bank_rrn: str | None = None,
    bank_code: str | None = None,
    error: str | None = None,
) -> None:
    expr  = "SET #s = :s, updated_at = :u"
    names = {"#s": "state"}
    vals  = {":s": state.value, ":u": _now()}
    if bank_rrn:
        expr += ", bank_rrn = :r";  vals[":r"] = bank_rrn
    if bank_code:
        expr += ", bank_code = :b"; vals[":b"] = bank_code
    if error:
        expr += ", #e = :err";      names["#e"] = "error"; vals[":err"] = error
    _table().update_item(
        Key={"txn_id": txn_id},
        UpdateExpression=expr,
        ExpressionAttributeNames=names,
        ExpressionAttributeValues=vals,
    )
    log.info("txn_id=%s → %s", txn_id, state)


def get_txn(txn_id: str) -> dict | None:
    resp = _table().get_item(Key={"txn_id": txn_id})
    return resp.get("Item")


def get_txn_by_idempotency_key(idempotency_key: str) -> dict | None:
    """
    Scan table for matching idempotency_key.
    No GSI required — acceptable for low-volume test/dev use.
    For production: replace with a GSI query (see Path B).
    """
    resp = _table().scan(                           # ← no GSI, no infra change
        FilterExpression=Attr("idempotency_key").eq(idempotency_key)
        # No Limit: DynamoDB Limit caps items *scanned*, not returned —
        # omitting it guarantees we don't miss the record in a small table
    )
    items = resp.get("Items", [])
    return items[0] if items else None
