# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/init_resources.py
"""
Standalone script â€” runs ONCE before uvicorn starts (see Dockerfile CMD).
Creates DynamoDB tables and SQS queues if they don't already exist.
Safe to run on every container start â€” fully idempotent.
"""

import logging
import os
import sys

import boto3
from botocore.exceptions import ClientError

logging.basicConfig(
    level  = logging.INFO,
    format = "%(asctime)s %(levelname)s %(name)s â€” %(message)s",
)
log = logging.getLogger(__name__)

LOCALSTACK_URL = os.getenv("LOCALSTACK_URL",      "http://localstack:4566")
AWS_REGION     = os.getenv("AWS_DEFAULT_REGION",  "ap-south-1")
AWS_KEY        = os.getenv("AWS_ACCESS_KEY_ID",    "test")
AWS_SECRET     = os.getenv("AWS_SECRET_ACCESS_KEY","test")


# â”€â”€ Clients â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def _dynamo():
    return boto3.client(
        "dynamodb",
        endpoint_url          = LOCALSTACK_URL,
        region_name           = AWS_REGION,
        aws_access_key_id     = AWS_KEY,
        aws_secret_access_key = AWS_SECRET,
    )


def _sqs():
    return boto3.client(
        "sqs",
        endpoint_url          = LOCALSTACK_URL,
        region_name           = AWS_REGION,
        aws_access_key_id     = AWS_KEY,
        aws_secret_access_key = AWS_SECRET,
    )


# â”€â”€ Helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def ensure_table(client, table_name: str, pk: str = "txn_id") -> None:
    """Create table; silently skip ResourceInUseException."""
    try:
        client.create_table(
            TableName            = table_name,
            AttributeDefinitions = [{"AttributeName": pk, "AttributeType": "S"}],
            KeySchema            = [{"AttributeName": pk, "KeyType": "HASH"}],
            BillingMode          = "PAY_PER_REQUEST",
        )
        log.info("Table '%s' created", table_name)
    except ClientError as exc:
        code = exc.response["Error"]["Code"]
        if code == "ResourceInUseException":
            log.info("Table '%s' already exists â€” skipping", table_name)
        else:
            log.error("Unexpected DynamoDB error creating '%s': %s", table_name, exc)
            raise


def ensure_queue(client, queue_name: str) -> str:
    """Create SQS queue; return URL (new or existing)."""
    try:
        resp = client.create_queue(QueueName=queue_name)
        log.info("SQS queue '%s' created", queue_name)
        return resp["QueueUrl"]
    except ClientError as exc:
        code = exc.response["Error"]["Code"]
        if code in ("QueueAlreadyExists", "AWS.SimpleQueueService.QueueDeletedRecently"):
            resp = client.get_queue_url(QueueName=queue_name)
            log.info("SQS queue '%s' already exists â€” reusing", queue_name)
            return resp["QueueUrl"]
        log.error("Unexpected SQS error creating '%s': %s", queue_name, exc)
        raise


# â”€â”€ Main â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

def main() -> None:
    log.info("Bootstrapping AWS resources at %s ...", LOCALSTACK_URL)

    dynamo = _dynamo()
    sqs    = _sqs()

    # DynamoDB tables
    ensure_table(dynamo, "ibts-transactions",         pk="txn_id")
    ensure_table(dynamo, "ibts-idempotency-records",  pk="idempotency_key")
    ensure_table(dynamo, "ibts-routing-table",        pk="bank_code")

    # SQS queues
    ensure_queue(sqs, "ibts-settlement-events")

    log.info("All resources ready â€” handing off to uvicorn")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        log.critical("Resource bootstrap FAILED: %s", exc)
        sys.exit(1)   # non-zero exit prevents uvicorn from starting

