# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/payment_metrics.py
"""
Business-level payment metrics for the payment-switch service.

Public API
──────────
  record_idempotency(service, idem_result)
  record_bank_request(bank_code, endpoint_type, http_code, duration_s, failed=False, fallback=False)
  record_payment(payer_vpa, payee_vpa, amount_paise, status, idem_result, error_kind, duration_s)
  record_state_corruption(service, violation)
  record_duplicate_debit(service, detection_type)

  async with payment_timer(payer_vpa, payee_vpa, amount_paise, idem_result) as ctx:
      ...
      ctx.status      = "SUCCESS"   # SUCCESS | FAILED | UNKNOWN
      ctx.error_kind  = None        # set on failure
      ctx.bank_code   = "SBI"       # set after VPA resolution
"""

import time
from contextlib import asynccontextmanager

from shared.metrics.registry import (  # ← correct folder name
    BANK_FAILURES_TOTAL,
    BANK_FALLBACK_USED_TOTAL,
    BANK_REQUEST_LATENCY_SECONDS,
    BANK_REQUESTS_TOTAL,
    DUPLICATE_DEBIT_TOTAL,
    IDEMPOTENCY_CHECKS_TOTAL,
    PAYMENT_AMOUNT_PAISE,
    PAYMENT_E2E_LATENCY_SECONDS,
    PAYMENT_ERRORS_TOTAL,
    PAYMENT_INITIATED_TOTAL,
    PAYMENT_STATE_CORRUPTION_TOTAL,
    PAYMENT_TOTAL_AMOUNT_PAISE,
)

# ── VPA handle → bank code mapping ────────────────────────────────────────────
# Matches L_BANK values used across the registry (SBI|HDFC|ICICI|YESBANK|AXIS)
_HANDLE_MAP: dict[str, str] = {
    "sbi":        "SBI",
    "oksbi":      "SBI",
    "okicici":    "ICICI",
    "icici":      "ICICI",
    "okhdfcbank": "HDFC",
    "hdfc":       "HDFC",
    "ybl":        "YESBANK",
    "okaxis":     "AXIS",
    "axisbank":   "AXIS",
    "paytm":      "PAYTM",
    "apl":        "PAYTM",
}


def _bank_from_vpa(vpa: str) -> str:
    """
    Extract a canonical bank code from a UPI VPA.
    e.g.  alice@oksbi  →  SBI
          bob@okhdfcbank  →  HDFC
          unknown@xyz  →  XYZ   (uppercased suffix as fallback)
    """
    if "@" not in vpa:
        return "UNKNOWN"
    suffix = vpa.split("@")[-1].lower().strip()
    return _HANDLE_MAP.get(suffix, suffix.upper())


# ── Idempotency ────────────────────────────────────────────────────────────────
def record_idempotency(service: str, idem_result: str) -> None:
    """
    Call immediately after every idempotency check.

    idem_result: NEW | CACHED | STALE_PROCESSING
    service:     payment-switch (or whichever service owns the check)
    """
    IDEMPOTENCY_CHECKS_TOTAL.labels(
        service     = service,
        idem_result = idem_result,
    ).inc()


# ── Bank adapter call ──────────────────────────────────────────────────────────
def record_bank_request(
    bank_code:     str,
    endpoint_type: str,          # primary | fallback
    http_code:     str,          # "200" | "500" | "timeout" etc.
    duration_s:    float,
    failed:        bool = False,
    fail_type:     str | None = None,   # http_error|timeout|connection|both_failed
    fallback_used: bool = False,
) -> None:
    """
    Call after every outbound bank adapter HTTP attempt (primary or fallback).

    endpoint_type: "primary" | "fallback"   ← matches L_EP_TYPE in registry
    fail_type:     "http_error" | "timeout" | "connection" | "both_failed"
    """
    BANK_REQUESTS_TOTAL.labels(
        bank_code     = bank_code,
        endpoint_type = endpoint_type,
        http_code     = http_code,
    ).inc()

    BANK_REQUEST_LATENCY_SECONDS.labels(
        bank_code     = bank_code,
        endpoint_type = endpoint_type,
    ).observe(duration_s)

    if failed and fail_type:
        BANK_FAILURES_TOTAL.labels(
            bank_code    = bank_code,
            failure_type = fail_type,
        ).inc()

    if fallback_used:
        BANK_FALLBACK_USED_TOTAL.labels(bank_code=bank_code).inc()


# ── Core payment recorder ──────────────────────────────────────────────────────
def record_payment(
    payer_vpa:    str,
    payee_vpa:    str,
    amount_paise: int,
    status:       str,                    # SUCCESS | FAILED | UNKNOWN
    idem_result:  str,                    # NEW | CACHED | STALE_PROCESSING
    error_kind:   str | None = None,   # validation|routing|bank_error|timeout|unknown
    duration_s:   float = 0.0,
) -> None:
    """
    Record a completed payment attempt.  Call once per attempt after outcome is known.
    All label values match registry constants exactly.
    """
    payer_bank = _bank_from_vpa(payer_vpa)
    payee_bank = _bank_from_vpa(payee_vpa)

    # ── Volume counter ─────────────────────────────────────────────────────────
    PAYMENT_INITIATED_TOTAL.labels(
        payer_bank  = payer_bank,
        payee_bank  = payee_bank,
        status      = status,
        idem_result = idem_result,
    ).inc()

    # ── Amount distribution ────────────────────────────────────────────────────
    PAYMENT_AMOUNT_PAISE.labels(
        payer_bank = payer_bank,
        payee_bank = payee_bank,
        status     = status,
    ).observe(amount_paise)

    # ── Running value total (SUCCESS only) ─────────────────────────────────────
    if status == "SUCCESS":
        PAYMENT_TOTAL_AMOUNT_PAISE.labels(
            payer_bank = payer_bank,
            payee_bank = payee_bank,
        ).inc(amount_paise)

    # ── E2E latency ────────────────────────────────────────────────────────────
    if duration_s > 0:
        PAYMENT_E2E_LATENCY_SECONDS.labels(
            payee_bank = payee_bank,
            status     = status,
        ).observe(duration_s)

    # ── Error breakdown ────────────────────────────────────────────────────────
    # Only record when there is a real error kind to avoid polluting the counter
    if error_kind and status != "SUCCESS":
        PAYMENT_ERRORS_TOTAL.labels(
            payee_bank = payee_bank,
            error_kind = error_kind,
        ).inc()


# ── Integrity helpers ──────────────────────────────────────────────────────────
def record_state_corruption(service: str, violation: str) -> None:
    """
    Call when a payment state integrity violation is detected.

    violation examples:
      "missing_txn_record"  | "state_mismatch"
      "dynamo_write_failed" | "idempotency_cache_mismatch"
    """
    PAYMENT_STATE_CORRUPTION_TOTAL.labels(
        service   = service,
        violation = violation,
    ).inc()


def record_duplicate_debit(service: str, detection_type: str) -> None:
    """
    Call when a confirmed duplicate successful debit is detected.

    detection_type examples:
      "idempotency_guard" | "bank_rrn_collision" | "reconciliation"
    """
    DUPLICATE_DEBIT_TOTAL.labels(
        service        = service,
        detection_type = detection_type,
    ).inc()


# ── Async context manager ──────────────────────────────────────────────────────
@asynccontextmanager
async def payment_timer(
    payer_vpa:    str,
    payee_vpa:    str,
    amount_paise: int,
    idem_result:  str,
    service:      str = "payment-switch",
):
    """
    Async context manager — times the full payment block and auto-records
    all metrics on exit whether the block succeeds, fails, or raises.

    Usage:
        async with payment_timer(
            req.payer_vpa, req.payee_vpa,
            req.amount_paise, idem_result,
        ) as ctx:
            # ... do payment work ...
            ctx.status      = "SUCCESS"    # default: FAILED
            ctx.error_kind  = None         # default: "unknown"
            ctx.bank_code   = bank_code    # set after VPA resolution (optional)

    On unhandled exception: status="FAILED", error_kind="unknown", exception re-raised.
    """

    class _Ctx:
        status:    str           = "FAILED"
        error_kind: str | None = "unknown"
        bank_code: str           = "UNKNOWN"   # enriched after VPA resolution

    ctx   = _Ctx()
    start = time.perf_counter()

    try:
        yield ctx

    except Exception:
        ctx.status     = "FAILED"
        ctx.error_kind = ctx.error_kind or "unknown"
        raise

    finally:
        duration = time.perf_counter() - start

        record_payment(
            payer_vpa    = payer_vpa,
            payee_vpa    = payee_vpa,
            amount_paise = amount_paise,
            status       = ctx.status,
            idem_result  = idem_result,
            error_kind   = ctx.error_kind if ctx.status != "SUCCESS" else None,
            duration_s   = duration,
        )
