# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/sqs.py

import boto3, json, logging
from app.config import settings

log = logging.getLogger(__name__)

def _client():
    return boto3.client(
        "sqs",
        endpoint_url=settings.sqs_endpoint_url,
        region_name=settings.aws_default_region,
        aws_access_key_id=settings.aws_access_key_id,
        aws_secret_access_key=settings.aws_secret_access_key,
    )

def emit_settlement_event(txn_id: str, bank_code: str, amount_paise: int) -> None:
    try:
        sqs   = _client()
        url   = sqs.get_queue_url(QueueName=settings.sqs_queue_name)["QueueUrl"]
        body  = json.dumps({
            "txn_id": txn_id,
            "bank_code": bank_code,
            "amount_paise": amount_paise,
            "event": "PAYMENT_SUCCESS",
        })
        sqs.send_message(QueueUrl=url, MessageBody=body)
        log.info("settlement event emitted txn_id=%s", txn_id)
    except Exception as exc:
        # Fire-and-forget — never block the payment response
        log.warning("SQS emit failed (non-fatal): %s", exc)
