# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/bank_call_metrics.py
"""
Executes a bank HTTP call through the circuit breaker, recording every outcome.
"""

import time
import httpx
import pybreaker

from shared.metrics.registry import (
    BANK_REQUESTS_TOTAL,
    BANK_REQUEST_LATENCY_SECONDS,
    BANK_FAILURES_TOTAL,
    BANK_FALLBACK_USED_TOTAL,
    CIRCUIT_BREAKER_REJECTED_TOTAL,
)


async def _call_endpoint(
    bank_code:     str,
    endpoint_type: str,
    url:           str,
    payload:       dict,
    timeout:       float,
) -> dict:
    """Raw HTTP call — no breaker. Records request metrics."""
    start = time.perf_counter()
    code  = "error"
    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(url, json=payload)
        code = str(resp.status_code)
        BANK_REQUESTS_TOTAL.labels(
            bank_code     = bank_code,
            endpoint_type = endpoint_type,
            http_code     = code,
        ).inc()
        resp.raise_for_status()
        return resp.json()

    except httpx.TimeoutException:
        BANK_FAILURES_TOTAL.labels(bank_code=bank_code, failure_type="timeout").inc()
        raise
    except httpx.HTTPStatusError:
        BANK_FAILURES_TOTAL.labels(bank_code=bank_code, failure_type="http_error").inc()
        raise
    except Exception:
        BANK_FAILURES_TOTAL.labels(bank_code=bank_code, failure_type="connection").inc()
        raise
    finally:
        BANK_REQUEST_LATENCY_SECONDS.labels(
            bank_code=bank_code, endpoint_type=endpoint_type
        ).observe(time.perf_counter() - start)


async def call_bank(
    bank_code:    str,
    primary_url:  str,
    fallback_url: str,
    payload:      dict,
    breaker:      pybreaker.CircuitBreaker,
    timeout:      float = 10.0,
) -> dict:
    """
    Try primary through breaker, fall back if primary fails,
    record all outcomes.
    """
    # breaker.call() is synchronous -- wrap the async call
    try:
        breaker.call(lambda: None)   # raises CircuitBreakerError if OPEN
    except pybreaker.CircuitBreakerError:
        CIRCUIT_BREAKER_REJECTED_TOTAL.labels(bank_code=bank_code).inc()
        raise

    try:
        result = await _call_endpoint(bank_code, "primary", primary_url, payload, timeout)
        breaker.call(lambda: None)   # register success with breaker
        return result

    except pybreaker.CircuitBreakerError:
        CIRCUIT_BREAKER_REJECTED_TOTAL.labels(bank_code=bank_code).inc()
        raise
    except Exception:
        BANK_FALLBACK_USED_TOTAL.labels(bank_code=bank_code).inc()
        try:
            # Fallback does not go through breaker
            return await _call_endpoint(
                bank_code, "fallback", fallback_url, payload, timeout
            )
        except Exception:
            BANK_FAILURES_TOTAL.labels(
                bank_code=bank_code, failure_type="both_failed"
            ).inc()
            raise
