# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/breaker_metrics.py
"""
pybreaker listener that emits circuit breaker metrics on every state change.
"""

import time
import pybreaker

from metrics.registry import (
    CIRCUIT_BREAKER_STATE,
    CIRCUIT_BREAKER_FAIL_COUNT,
    CIRCUIT_BREAKER_TRANSITIONS_TOTAL,
    CIRCUIT_BREAKER_OPEN_DURATION_SECONDS,
    CIRCUIT_BREAKER_REJECTED_TOTAL,
)

_STATE_INT = {"closed": 0, "open": 1, "half_open": 2}
_open_since: dict[str, float] = {}


class IBTSBreakerListener(pybreaker.CircuitBreakerListener):

    def __init__(self, bank_code: str):
        self.bank = bank_code

    def state_change(self, cb, old_state, new_state) -> None:
        old = old_state.name.lower()
        new = new_state.name.lower()

        CIRCUIT_BREAKER_STATE.labels(bank_code=self.bank).set(
            _STATE_INT.get(new, -1)
        )
        CIRCUIT_BREAKER_TRANSITIONS_TOTAL.labels(
            bank_code  = self.bank,
            transition = f"{old}_to_{new}",
        ).inc()

        if new == "open":
            _open_since[self.bank] = time.monotonic()

        if old == "open" and new == "half_open":
            opened_at = _open_since.pop(self.bank, None)
            if opened_at:
                CIRCUIT_BREAKER_OPEN_DURATION_SECONDS.labels(
                    bank_code=self.bank
                ).observe(time.monotonic() - opened_at)

    def failure(self, cb, exc) -> None:
        CIRCUIT_BREAKER_FAIL_COUNT.labels(bank_code=self.bank).set(cb.fail_counter)

    def success(self, cb) -> None:
        CIRCUIT_BREAKER_FAIL_COUNT.labels(bank_code=self.bank).set(cb.fail_counter)
        CIRCUIT_BREAKER_STATE.labels(bank_code=self.bank).set(0)


def make_breaker(bank_code: str, fail_max: int = 3,
                 reset_timeout: int = 30) -> pybreaker.CircuitBreaker:
    """Factory â€” returns an instrumented CircuitBreaker for a given bank."""
    breaker = pybreaker.CircuitBreaker(
        fail_max      = fail_max,
        reset_timeout = reset_timeout,
        listeners     = [IBTSBreakerListener(bank_code)],
        name          = bank_code,
    )
    # Seed gauges so Grafana shows all banks from startup
    CIRCUIT_BREAKER_STATE.labels(bank_code=bank_code).set(0)
    CIRCUIT_BREAKER_FAIL_COUNT.labels(bank_code=bank_code).set(0)
    return breaker

