# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/config.py

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    app_name:                str   = "bank-adapter"
    primary_timeout_seconds: float = 3.0
    fallback_timeout_seconds: float = 5.0
    breaker_fail_max:        int   = 3
    breaker_reset_timeout:   int   = 30  # seconds

    class Config:
        env_file = ".env"

settings = Settings()
