# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/main.py

import structlog
from fastapi import FastAPI
from app.routers.adapter_router import router

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer(),
    ]
)

app = FastAPI(title="bank-adapter", version="1.0.0")
app.include_router(router)

@app.get("/actuator/health")
def health():
    return {"status": "UP"}
