# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/main.py

from shared.telemetry import setup_telemetry
setup_telemetry()

import structlog
from fastapi import FastAPI
from app.routers.adapter_router import router
from app.routers.debug_router   import router as debug_router
from shared.metrics.middleware  import MetricsMiddleware, metrics_router  # ← NEW

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer(),
    ]
)

app = FastAPI(title="bank-adapter", version="1.0.0")

# ── Middleware: records ibts_http_requests_total + duration + security ─────────
# Replaces the make_asgi_app() mount — MetricsMiddleware exposes /metrics
# AND records all HTTP traffic automatically
app.add_middleware(MetricsMiddleware, service_name="bank-adapter")   # ← replaces make_asgi_app()

# ── Routers ────────────────────────────────────────────────────────────────────
app.include_router(metrics_router)    # /metrics endpoint
app.include_router(router)            # /api/v1/adapter
app.include_router(debug_router)      # /api/v1/adapter/debug


@app.get("/actuator/health")
def health():
    return {"status": "UP"}
