# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/models.py

from typing import Literal

from pydantic import BaseModel


class AdapterRequest(BaseModel):
    transactionId:    str
    bankCode:         str
    primaryEndpoint:  str
    fallbackEndpoint: str
    amount:           float
    currency:         str = "INR"
    payerVpa:         str
    payeeVpa:         str
    remarks:          str | None = ""

class AdapterResponse(BaseModel):
    transactionId:    str
    bankCode:         str
    status:           Literal["SUCCESS", "FAILED"]
    bankReferenceId:  str | None  = None
    resolvedVia:      Literal["PRIMARY", "FALLBACK", "NONE"]
    attempts:         int
    responseTimeMs:   int
    errorCode:        str | None  = None
    errorMessage:     str | None  = None

