# filename: infra-aws/stage1-cluster/terraform.tfvars
# Code Generated by Sidekick is for learning and experimentation purposes only.

aws_region              = "ap-south-1"
environment             = "poc"
cluster_name            = "ibts-eks"
cluster_version         = "1.30"
vpc_cidr                = "10.0.0.0/16"
availability_zones      = ["ap-south-1a", "ap-south-1b"]
private_subnet_cidrs    = ["10.0.10.0/24", "10.0.11.0/24"]
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
system_node_instance_type = "t3.medium"
