# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/metrics/circuit_breaker.py
"""
Full circuit breaker implementation with all registry metrics wired in.

Every state transition, failure count, open duration, and rejected request
is automatically recorded to Prometheus.

Usage (bank-adapter):
    from shared.metrics.circuit_breaker import CircuitBreaker, CircuitOpenError

    # One breaker per bank — create at module level
    _breakers: dict[str, CircuitBreaker] = {}

    def get_breaker(bank_code: str) -> CircuitBreaker:
        if bank_code not in _breakers:
            _breakers[bank_code] = CircuitBreaker(bank_code=bank_code)
        return _breakers[bank_code]

    # In your bank call:
    breaker = get_breaker(bank_code)
    try:
        async with breaker.protect():
            response = await call_bank(...)
    except CircuitOpenError:
        raise HTTPException(503, f"Bank {bank_code} circuit open")
"""

import asyncio
import logging
import time
from contextlib import asynccontextmanager
from enum import IntEnum

from .registry import (
    CIRCUIT_BREAKER_FAIL_COUNT,
    CIRCUIT_BREAKER_OPEN_DURATION_SECONDS,
    CIRCUIT_BREAKER_REJECTED_TOTAL,
    CIRCUIT_BREAKER_STATE,
    CIRCUIT_BREAKER_TRANSITIONS_TOTAL,
)

log = logging.getLogger(__name__)


# ── State enum ─────────────────────────────────────────────────────────────────
class CBState(IntEnum):
    CLOSED    = 0   # healthy — requests flow through
    OPEN      = 1   # tripped — requests short-circuited
    HALF_OPEN = 2   # probing — one request allowed through


# ── Transition label map — matches registry comment exactly ───────────────────
_TRANSITION = {
    (CBState.CLOSED,    CBState.OPEN):      "closed_to_open",
    (CBState.OPEN,      CBState.HALF_OPEN): "open_to_half_open",
    (CBState.HALF_OPEN, CBState.CLOSED):    "half_open_to_closed",
    (CBState.HALF_OPEN, CBState.OPEN):      "half_open_to_open",
}


class CircuitOpenError(Exception):
    """Raised when a request is rejected because the breaker is OPEN."""
    def __init__(self, bank_code: str):
        super().__init__(f"Circuit breaker OPEN for bank {bank_code}")
        self.bank_code = bank_code


class CircuitBreaker:
    """
    Per-bank circuit breaker.

    Config:
        failure_threshold   — consecutive failures before tripping       (default 5)
        recovery_timeout_s  — seconds to wait before probing HALF_OPEN   (default 30)
        success_threshold   — successes in HALF_OPEN before closing       (default 2)
        excluded_exceptions — exception types that do NOT count as failures

    All state changes automatically update Prometheus gauges and counters.
    """

    def __init__(
        self,
        bank_code:          str,
        failure_threshold:  int   = 5,
        recovery_timeout_s: float = 30.0,
        success_threshold:  int   = 2,
        excluded_exceptions: tuple = (),
    ):
        self.bank_code           = bank_code
        self.failure_threshold   = failure_threshold
        self.recovery_timeout_s  = recovery_timeout_s
        self.success_threshold   = success_threshold
        self.excluded_exceptions = excluded_exceptions

        self._state            = CBState.CLOSED
        self._fail_count       = 0
        self._half_open_ok     = 0
        self._opened_at: float | None = None   # perf_counter timestamp
        self._lock             = asyncio.Lock()

        # Initialise gauges so Prometheus shows 0 from startup
        CIRCUIT_BREAKER_STATE.labels(bank_code=bank_code).set(CBState.CLOSED)
        CIRCUIT_BREAKER_FAIL_COUNT.labels(bank_code=bank_code).set(0)

    # ── State property with auto-metric update ─────────────────────────────────
    @property
    def state(self) -> CBState:
        return self._state

    def _set_state(self, new_state: CBState) -> None:
        """
        Transition to new_state.
        Records transition counter, updates state gauge,
        records OPEN duration histogram when leaving OPEN.
        """
        if new_state == self._state:
            return

        old_state   = self._state
        transition  = _TRANSITION.get((old_state, new_state), "unknown")

        # Record open duration when breaker closes or goes half-open
        if old_state == CBState.OPEN and self._opened_at is not None:
            open_duration = time.perf_counter() - self._opened_at
            CIRCUIT_BREAKER_OPEN_DURATION_SECONDS.labels(
                bank_code=self.bank_code
            ).observe(open_duration)
            self._opened_at = None

        if new_state == CBState.OPEN:
            self._opened_at = time.perf_counter()

        self._state = new_state

        # Update gauges + counters
        CIRCUIT_BREAKER_STATE.labels(
            bank_code=self.bank_code
        ).set(int(new_state))

        CIRCUIT_BREAKER_TRANSITIONS_TOTAL.labels(
            bank_code  = self.bank_code,
            transition = transition,
        ).inc()

        log.warning(
            "circuit_breaker bank=%s %s → %s",
            self.bank_code,
            old_state.name,
            new_state.name,
        )

    def _set_fail_count(self, count: int) -> None:
        self._fail_count = count
        CIRCUIT_BREAKER_FAIL_COUNT.labels(bank_code=self.bank_code).set(count)

    # ── Core logic ─────────────────────────────────────────────────────────────
    def _should_attempt(self) -> bool:
        """
        Returns True if a request should be allowed through.
        Handles OPEN → HALF_OPEN timeout transition.
        """
        if self._state == CBState.CLOSED:
            return True

        if self._state == CBState.OPEN:
            # Check if recovery timeout has elapsed
            if (
                self._opened_at is not None
                and time.perf_counter() - self._opened_at >= self.recovery_timeout_s
            ):
                self._half_open_ok = 0
                self._set_state(CBState.HALF_OPEN)
                return True
            return False   # still OPEN — reject

        # HALF_OPEN — allow one probe through
        return True

    def _on_success(self) -> None:
        if self._state == CBState.HALF_OPEN:
            self._half_open_ok += 1
            if self._half_open_ok >= self.success_threshold:
                self._set_fail_count(0)
                self._set_state(CBState.CLOSED)
        elif self._state == CBState.CLOSED:
            # Reset fail count on any success
            if self._fail_count > 0:
                self._set_fail_count(0)

    def _on_failure(self) -> None:
        if self._state == CBState.HALF_OPEN:
            # Probe failed — back to OPEN
            self._set_state(CBState.OPEN)
            return

        new_count = self._fail_count + 1
        self._set_fail_count(new_count)

        if new_count >= self.failure_threshold:
            self._set_fail_count(0)
            self._set_state(CBState.OPEN)

    # ── Public context manager ─────────────────────────────────────────────────
    @asynccontextmanager
    async def protect(self):
        """
        Async context manager — wrap every bank call with this.

        Raises CircuitOpenError immediately if breaker is OPEN.
        Records success/failure and updates all metrics automatically.

        Usage:
            async with breaker.protect():
                response = await call_bank(...)
        """
        async with self._lock:
            allowed = self._should_attempt()

        if not allowed:
            CIRCUIT_BREAKER_REJECTED_TOTAL.labels(
                bank_code=self.bank_code
            ).inc()
            raise CircuitOpenError(self.bank_code)

        try:
            yield
            async with self._lock:
                self._on_success()

        except self.excluded_exceptions:
            # e.g. validation errors — don't count against the breaker
            raise

        except Exception:
            async with self._lock:
                self._on_failure()
            raise

    # ── Manual helpers (for health-check / admin endpoints) ───────────────────
    def force_open(self) -> None:
        """Manually trip the breaker — useful for testing or manual intervention."""
        self._set_fail_count(0)
        self._set_state(CBState.OPEN)

    def force_close(self) -> None:
        """Manually reset the breaker — useful after a confirmed bank recovery."""
        self._set_fail_count(0)
        self._set_state(CBState.CLOSED)

    @property
    def is_open(self) -> bool:
        return self._state == CBState.OPEN

    @property
    def is_closed(self) -> bool:
        return self._state == CBState.CLOSED


# ── Module-level breaker registry ─────────────────────────────────────────────
# One breaker per bank_code — shared across all requests in the process
_breakers: dict[str, CircuitBreaker] = {}


def get_breaker(
    bank_code:          str,
    failure_threshold:  int   = 5,
    recovery_timeout_s: float = 30.0,
    success_threshold:  int   = 2,
    excluded_exceptions: tuple = (),
) -> CircuitBreaker:
    """
    Get or create a CircuitBreaker for the given bank_code.
    Config params are only applied on first creation.

    Call this from bank-adapter at startup or on first request per bank.
    """
    if bank_code not in _breakers:
        _breakers[bank_code] = CircuitBreaker(
            bank_code           = bank_code,
            failure_threshold   = failure_threshold,
            recovery_timeout_s  = recovery_timeout_s,
            success_threshold   = success_threshold,
            excluded_exceptions = excluded_exceptions,
        )
    return _breakers[bank_code]
