# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/delete/dynamo_tracker.py
"""
Wraps boto3 DynamoDB Table resource to record latency and errors.

    from shared.delete.dynamo_tracker import TrackedTable
    table = TrackedTable(boto3_table, service="idempotency", table_name="idempotency-records")
    item  = table.get_item(Key={"idempotency_key": key})
"""

import time
from typing import Any

from .registry import DYNAMO_OP_LATENCY_SECONDS, DYNAMO_ERRORS_TOTAL


class TrackedTable:
    def __init__(self, table, service: str, table_name: str):
        self._table   = table
        self._service = service
        self._tname   = table_name

    def _call(self, operation: str, **kwargs) -> Any:
        start = time.perf_counter()
        try:
            method = getattr(self._table, operation.lower().replace("item", "_item"))
            return method(**kwargs)
        except Exception as exc:
            error_type = getattr(exc, "response", {}) \
                .get("Error", {}).get("Code", type(exc).__name__)
            DYNAMO_ERRORS_TOTAL.labels(
                service    = self._service,
                table      = self._tname,
                error_type = error_type,
            ).inc()
            raise
        finally:
            DYNAMO_OP_LATENCY_SECONDS.labels(
                service   = self._service,
                table     = self._tname,
                operation = operation,
            ).observe(time.perf_counter() - start)

    def get_item(self, **kwargs):
        return self._call("get_item", **kwargs)

    def put_item(self, **kwargs):
        return self._call("put_item", **kwargs)

    def update_item(self, **kwargs):
        return self._call("update_item", **kwargs)

    def query(self, **kwargs):
        return self._call("query", **kwargs)

