# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/metrics/ibts_metrics.py

from prometheus_client import Counter, Histogram, Gauge, REGISTRY
import time

# ── Payment lifecycle ──────────────────────────────────────────────────────────
PAYMENT_INITIATED = Counter(
    "ibts_payment_initiated_total",
    "Total payment attempts",
    ["status", "payee_bank", "idem_result"],
    # status values: SUCCESS | FAILED | UNKNOWN
)

PAYMENT_ERRORS = Counter(
    "ibts_payment_errors_total",
    "Payment errors by kind",
    ["error_kind", "service"],
    # error_kind: TIMEOUT | BANK_REJECT | VALIDATION | INTERNAL | UNKNOWN
)

PAYMENT_UNKNOWN = Counter(
    "ibts_payment_unknown_total",
    "Payments with indeterminate outcome — no ACK/NACK within TTL",
    ["payee_bank"],
)

# ── End-to-end latency ─────────────────────────────────────────────────────────
PAYMENT_E2E_LATENCY = Histogram(
    "ibts_payment_end_to_end_latency_seconds",
    "Wall-clock time from API receipt to final status",
    buckets=[0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0],
)

# ── Bank-level outbound latency ────────────────────────────────────────────────
BANK_REQUEST_LATENCY = Histogram(
    "ibts_bank_request_latency_seconds",
    "Latency of outbound calls to bank endpoints",
    ["bank_code", "endpoint_type"],
    # endpoint_type: DEBIT | CREDIT | STATUS
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0],
)

# ── Circuit breaker ────────────────────────────────────────────────────────────
CIRCUIT_BREAKER_STATE = Gauge(
    "ibts_circuit_breaker_state",
    "Circuit breaker state per bank  0=closed  1=open  2=half_open",
    ["bank_code"],
)

# ── Idempotency ────────────────────────────────────────────────────────────────
IDEMPOTENCY_CHECKS = Counter(
    "ibts_idempotency_checks_total",
    "Idempotency key lookups",
    ["idem_result"],
    # idem_result: NEW | CACHED
)

# ── Security ───────────────────────────────────────────────────────────────────
RATE_LIMIT_HITS = Counter(
    "ibts_rate_limit_hits_total",
    "HTTP 429 responses issued",
    ["service", "client_id"],
)

AUTH_FAILURES = Counter(
    "ibts_auth_failures_total",
    "HTTP 401 / 403 responses issued",
    ["service", "reason"],
    # reason: EXPIRED_TOKEN | INVALID_SIG | FORBIDDEN
)

# ── Cache & storage ────────────────────────────────────────────────────────────
ROUTE_CACHE_HIT_RATIO = Gauge(
    "ibts_route_cache_hit_ratio",
    "Rolling hit ratio of the routing cache",
    ["service"],
)

REDIS_OP_LATENCY = Histogram(
    "ibts_redis_operation_latency_seconds",
    "Redis command latency",
    ["service", "operation"],
    # operation: GET | SET | DEL | EXPIRE
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1],
)

DYNAMO_OP_LATENCY = Histogram(
    "ibts_dynamo_operation_latency_seconds",
    "DynamoDB call latency",
    ["service", "table", "operation"],
    # operation: GetItem | PutItem | Query | UpdateItem
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5],
)

# ── Availability ───────────────────────────────────────────────────────────────
SERVICE_AVAILABILITY = Gauge(
    "ibts_service_availability_ratio",
    "Rolling availability ratio  1.0 = fully up",
    ["service"],
)


# ── Helper: context manager for end-to-end payment tracking ───────────────────
class track_payment:
    """
    Wraps a payment flow — records E2E latency, increments counters.

    Usage:
        with track_payment(payee_bank="BANK_A", idem_result="NEW") as t:
            result = await call_bank(...)
            t.set_status("SUCCESS")   # or FAILED / UNKNOWN
    """

    def __init__(self, payee_bank: str, idem_result: str = "NEW"):
        self.payee_bank  = payee_bank
        self.idem_result = idem_result
        self.status      = "UNKNOWN"
        self._start      = None

    def set_status(self, status: str):
        self.status = status

    def __enter__(self):
        self._start = time.perf_counter()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        elapsed = time.perf_counter() - self._start
        PAYMENT_E2E_LATENCY.observe(elapsed)

        if exc_type is not None:
            # unhandled exception → outcome unknown
            self.status = "UNKNOWN"

        PAYMENT_INITIATED.labels(
            status     = self.status,
            payee_bank = self.payee_bank,
            idem_result = self.idem_result,
        ).inc()

        if self.status == "UNKNOWN":
            PAYMENT_UNKNOWN.labels(payee_bank=self.payee_bank).inc()

        return False  # never suppress exceptions
