# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/metrics/integration_test.py
"""
Smoke-test: import every metric and confirm /metrics is reachable.
Run inside each service container:   python -m shared.metrics.integration_test
"""

import sys
import urllib.request


def check_imports():
    print("  [OK] all registry imports resolved")

def check_metrics_endpoint(host: str = "localhost", port: int = 8084):
    url = f"http://{host}:{port}/metrics"
    try:
        resp = urllib.request.urlopen(url, timeout=3)
        body = resp.read().decode()
        assert "ibts_http_requests_total" in body, "Counter missing from /metrics"
        assert "ibts_circuit_breaker_state" in body, "Gauge missing from /metrics"
        print(f"  [OK] /metrics reachable at {url}  ({len(body)} bytes)")
    except Exception as exc:
        print(f"  [FAIL] /metrics not reachable at {url}: {exc}")
        sys.exit(1)


from metrics.registry import (
    DUPLICATE_DEBIT_TOTAL,
    PAYMENT_STATE_CORRUPTION_TOTAL,
)


def record_state_corruption(violation: str) -> None:
    PAYMENT_STATE_CORRUPTION_TOTAL.labels(
        service="payment-switch",
        violation=violation,
    ).inc()


def record_duplicate_debit(detection_type: str) -> None:
    DUPLICATE_DEBIT_TOTAL.labels(
        service="bank-adapter",
        detection_type=detection_type,
    ).inc()




if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8084
    check_imports()
    check_metrics_endpoint(port=port)
    print("  All checks passed.")



