# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/metrics/middleware.py
"""
Drop-in FastAPI middleware + /metrics endpoint for every IBTS service.

    from shared.metrics.middleware import MetricsMiddleware, metrics_router

    app.add_middleware(MetricsMiddleware, service_name="payment-switch")
    app.include_router(metrics_router)
"""

import time
from collections.abc import Callable

from fastapi import APIRouter, Request, Response
from prometheus_client import CONTENT_TYPE_LATEST, generate_latest
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.routing import Match

from .registry import (
    AUTH_FAILURES_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_IN_FLIGHT,
    HTTP_REQUESTS_TOTAL,
    RATE_LIMIT_HITS_TOTAL,
    RATE_LIMIT_REMAINING,
)

# ── Paths that must NOT be instrumented ───────────────────────────────────────
# /metrics is excluded so Prometheus scrapes never record themselves
_SKIP_PATHS = frozenset({"/metrics", "/health", "/readyz", "/livez"})   # ← was /delete


def _route_template(request: Request) -> str:
    """
    Return the route pattern  /api/v1/payments/{txn_id}
    instead of the real path to prevent label cardinality explosion.
    Falls back to raw path for unmatched routes (404s etc.).
    """
    for route in request.app.routes:
        match, _ = route.matches(request.scope)
        if match == Match.FULL:
            return getattr(route, "path", request.url.path)
    return request.url.path


class MetricsMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, service_name: str = "unknown"):
        super().__init__(app)
        self.service = service_name

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        path = _route_template(request)

        if path in _SKIP_PATHS:
            return await call_next(request)

        method  = request.method
        lbl_inf = {"service": self.service, "endpoint": path}

        HTTP_REQUESTS_IN_FLIGHT.labels(**lbl_inf).inc()
        start       = time.perf_counter()
        status_code = 500

        try:
            response    = await call_next(request)
            status_code = response.status_code
            return response

        finally:
            duration = time.perf_counter() - start
            code     = str(status_code)

            HTTP_REQUESTS_TOTAL.labels(
                service=self.service, endpoint=path,
                method=method, http_code=code,
            ).inc()

            HTTP_REQUEST_DURATION_SECONDS.labels(
                service=self.service, endpoint=path,
                method=method, http_code=code,
            ).observe(duration)

            HTTP_REQUESTS_IN_FLIGHT.labels(**lbl_inf).dec()

            # ── Security metrics ──────────────────────────────────────────────
            # Wired here so every service gets them for free via the middleware.
            # Labels match registry exactly: reason=missing_key|invalid_key
            #                                client_ip from X-Forwarded-For

            client_ip = (
                request.headers.get("X-Forwarded-For", "").split(",")[0].strip()
                or request.client.host
            )

            if status_code == 429:
                RATE_LIMIT_HITS_TOTAL.labels(
                    service=self.service,
                    client_ip=client_ip,
                ).inc()

                # Update remaining-quota gauge if gateway sets the header
                remaining = response.headers.get("X-RateLimit-Remaining")
                if remaining is not None:
                    try:
                        RATE_LIMIT_REMAINING.labels(service=self.service).set(
                            float(remaining)
                        )
                    except ValueError:
                        pass

            elif status_code == 401:
                has_key = bool(
                    request.headers.get("Authorization")
                    or request.headers.get("X-API-Key")
                )
                AUTH_FAILURES_TOTAL.labels(
                    service=self.service,
                    reason="invalid_key" if has_key else "missing_key",
                ).inc()

            elif status_code == 403:
                # Key was present but lacked the required scope
                AUTH_FAILURES_TOTAL.labels(
                    service=self.service,
                    reason="invalid_key",
                ).inc()


# ── /metrics endpoint ─────────────────────────────────────────────────────────
metrics_router = APIRouter()


@metrics_router.get("/metrics", include_in_schema=False)   # ← was /delete (ROOT CAUSE FIX)
async def prometheus_metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)
