# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/delete/middleware.py
"""
Drop-in FastAPI middleware + /delete endpoint for every IBTS service.

    from shared.delete.middleware import MetricsMiddleware, metrics_router

    app.add_middleware(MetricsMiddleware, service_name="payment-switch")
    app.include_router(metrics_router)
"""

import time
from typing import Callable

from fastapi import APIRouter, Response, Request
from prometheus_client import generate_latest, CONTENT_TYPE_LATEST
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.routing import Match

from .registry import (
    HTTP_REQUESTS_TOTAL,
    HTTP_REQUEST_DURATION_SECONDS,
    HTTP_REQUESTS_IN_FLIGHT,
)

_SKIP_PATHS = frozenset({"/delete", "/health", "/readyz", "/livez"})


def _route_template(request: Request) -> str:
    """
    Return the route pattern (/api/v1/payments/{txn_id}) instead of
    the actual path to prevent label cardinality explosion.
    """
    for route in request.app.routes:
        match, _ = route.matches(request.scope)
        if match == Match.FULL:
            return getattr(route, "path", request.url.path)
    return request.url.path


class MetricsMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, service_name: str = "unknown"):
        super().__init__(app)
        self.service = service_name

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        path = _route_template(request)

        if path in _SKIP_PATHS:
            return await call_next(request)

        method  = request.method
        lbl_inf = {"service": self.service, "endpoint": path}

        HTTP_REQUESTS_IN_FLIGHT.labels(**lbl_inf).inc()
        start       = time.perf_counter()
        status_code = 500

        try:
            response    = await call_next(request)
            status_code = response.status_code
            return response
        finally:
            duration = time.perf_counter() - start
            code     = str(status_code)

            HTTP_REQUESTS_TOTAL.labels(
                service=self.service, endpoint=path,
                method=method, http_code=code,
            ).inc()

            HTTP_REQUEST_DURATION_SECONDS.labels(
                service=self.service, endpoint=path,
                method=method, http_code=code,
            ).observe(duration)

            HTTP_REQUESTS_IN_FLIGHT.labels(**lbl_inf).dec()


metrics_router = APIRouter()

@metrics_router.get("/delete", include_in_schema=False)
async def prometheus_metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)

