# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/metrics/redis_tracker.py
"""
Thin async wrapper around redis.asyncio that auto-records latency
and errors for every operation using your registry metrics.

Usage:
    from shared.metrics.redis_tracker import TrackedRedis
    import redis.asyncio as aioredis

    _raw   = await aioredis.from_url("redis://ibts-redis:6379")
    redis  = TrackedRedis(_raw, service="payment-switch")

    value  = await redis.get("route:SBI")
    await  redis.set("route:SBI", payload, ex=300)
"""

import time
import redis.asyncio as aioredis

from .registry import (
    REDIS_OP_LATENCY_SECONDS,
    REDIS_ERRORS_TOTAL,
    ROUTE_CACHE_OPS_TOTAL,
    ROUTE_CACHE_HIT_RATIO,
)


class TrackedRedis:
    """
    Drop-in replacement for redis.asyncio.Redis.
    Every method records:
      - ibts_redis_operation_latency_seconds  (always)
      - ibts_redis_errors_total               (on exception)

    For routing-cache operations (service="payment-router") it
    additionally records:
      - ibts_route_cache_ops_total            (hit | miss | set | evict)
      - ibts_route_cache_hit_ratio            (rolling gauge, updated on get)
    """

    def __init__(self, client: aioredis.Redis, service: str):
        self._r           = client
        self._service     = service
        self._is_router   = service == "payment-router"

        # rolling counters for hit-ratio gauge (in-process, resets on restart)
        self._cache_hits   = 0
        self._cache_misses = 0

    # ── Internal dispatcher ────────────────────────────────────────────────────
    async def _call(self, operation: str, coro):
        start = time.perf_counter()
        try:
            result = await coro
            return result
        except Exception as exc:
            REDIS_ERRORS_TOTAL.labels(
                service    = self._service,
                error_type = type(exc).__name__,
            ).inc()
            raise
        finally:
            REDIS_OP_LATENCY_SECONDS.labels(
                service   = self._service,
                operation = operation,
            ).observe(time.perf_counter() - start)

    # ── Hit-ratio helper (router service only) ─────────────────────────────────
    def _update_hit_ratio(self, hit: bool, bank_code: str = "UNKNOWN") -> None:
        if not self._is_router:
            return

        cache_op = "hit" if hit else "miss"
        ROUTE_CACHE_OPS_TOTAL.labels(
            bank_code = bank_code,
            operation = cache_op,
        ).inc()

        if hit:
            self._cache_hits += 1
        else:
            self._cache_misses += 1

        total = self._cache_hits + self._cache_misses
        if total > 0:
            ROUTE_CACHE_HIT_RATIO.labels(service=self._service).set(
                self._cache_hits / total
            )

    # ── Public methods ─────────────────────────────────────────────────────────
    async def get(self, key: str, bank_code: str = "UNKNOWN"):
        """
        GET a key.
        For routing cache calls pass bank_code so hit/miss is tracked per bank.
        """
        result = await self._call("GET", self._r.get(key))
        self._update_hit_ratio(hit=result is not None, bank_code=bank_code)
        return result

    async def set(self, key: str, value, ex: int = None,
                  bank_code: str = "UNKNOWN"):
        """
        SET a key with optional TTL.
        Records a 'set' cache op for routing service.
        """
        result = await self._call("SET", self._r.set(key, value, ex=ex))
        if self._is_router:
            ROUTE_CACHE_OPS_TOTAL.labels(
                bank_code = bank_code,
                operation = "set",
            ).inc()
        return result

    async def delete(self, *keys: str, bank_code: str = "UNKNOWN"):
        """
        DEL one or more keys.
        Records an 'evict' cache op for routing service.
        """
        result = await self._call("DEL", self._r.delete(*keys))
        if self._is_router:
            ROUTE_CACHE_OPS_TOTAL.labels(
                bank_code = bank_code,
                operation = "evict",
            ).inc()
        return result

    async def exists(self, *keys: str):
        return await self._call("EXISTS", self._r.exists(*keys))

    async def expire(self, key: str, seconds: int):
        return await self._call("EXPIRE", self._r.expire(key, seconds))

    async def incr(self, key: str):
        return await self._call("INCR", self._r.incr(key))

    async def hget(self, name: str, field: str):
        return await self._call("HGET", self._r.hget(name, field))

    async def hset(self, name: str, mapping: dict):
        return await self._call("HSET", self._r.hset(name, mapping=mapping))

    async def hgetall(self, name: str):
        return await self._call("HGETALL", self._r.hgetall(name))

    async def ping(self):
        return await self._call("PING", self._r.ping())
