# filename: infra-aws/stage2-config/00-versions.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.47"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.29"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.0"
    }
  }

  backend "s3" {
    bucket       = "sandesh-tf-file"
    key          = "ibts-eks/stage2/terraform.tfstate"
    region       = "us-east-1"
    encrypt      = true
    use_lockfile = true
  }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = {
      Project     = "ibts"
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# ══════════════════════════════════════════════════════
# READ STAGE 1 OUTPUTS
# Cluster is guaranteed to exist before this stage runs
# No try() needed — stage2 never runs without stage1
# ══════════════════════════════════════════════════════
data "terraform_remote_state" "stage1" {
  backend = "s3"
  config = {
    bucket = "sandesh-tf-file"
    key    = "ibts-eks/stage1/terraform.tfstate"
    region = "us-east-1"
  }
}

# Read auth token directly from AWS API
# Cluster exists at this point so this never fails
data "aws_eks_cluster_auth" "this" {
  name = data.terraform_remote_state.stage1.outputs.cluster_name
}

locals {
  cluster_endpoint = data.terraform_remote_state.stage1.outputs.cluster_endpoint
  cluster_ca       = base64decode(
    data.terraform_remote_state.stage1.outputs.cluster_certificate_authority_data
  )
  cluster_token = data.aws_eks_cluster_auth.this.token
}

# ── Providers — all read from stage1 remote state
# No module outputs, no chicken-and-egg problem
provider "kubernetes" {
  host                   = local.cluster_endpoint
  cluster_ca_certificate = local.cluster_ca
  token                  = local.cluster_token
}

provider "helm" {
  kubernetes {
    host                   = local.cluster_endpoint
    cluster_ca_certificate = local.cluster_ca
    token                  = local.cluster_token
  }
}

provider "kubectl" {
  host                   = local.cluster_endpoint
  cluster_ca_certificate = local.cluster_ca
  token                  = local.cluster_token
  load_config_file       = false
}
