# filename: infra-aws/stage2-config/01-variables.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

variable "aws_region" {
  type    = string
  default = "ap-south-2"
}

variable "environment" {
  type    = string
  default = "poc"
}

variable "cluster_name" {
  type    = string
  default = "ibts-eks"
}

variable "karpenter_version" {
  type    = string
  default = "1.0.8"
}

variable "aws_lb_controller_version" {
  type    = string
  default = "1.8.1"
}

variable "karpenter_spot_instance_families" {
  type    = list(string)
  default = ["t3", "t3a"]
}

variable "karpenter_spot_instance_sizes" {
  type    = list(string)
  default = ["medium", "large"]
}
