# filename: infra-aws/stage2-config/01-variables.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

variable "aws_region" {
  type    = string
  default = "ap-south-2"
}

variable "environment" {
  type    = string
  default = "poc"
}

variable "cluster_name" {
  type    = string
  default = "ibts-eks"
}

variable "karpenter_version" {
  type    = string
  default = "1.0.8"
}

variable "aws_lb_controller_version" {
  type    = string
  default = "1.8.1"
}

variable "karpenter_spot_instance_families" {
  type    = list(string)
  default = ["t3", "t3a"]
}

variable "karpenter_spot_instance_sizes" {
  type    = list(string)
  default = ["medium", "large"]
}

variable "jwt_secret" {
  description = "JWT signing secret — set via TF_VAR_jwt_secret in CI"
  type        = string
  sensitive   = true
  default     = "ibts-dev-secret-change-in-prod"
}

variable "api_key" {
  description = "API key for api-gateway — set via TF_VAR_api_key in CI"
  type        = string
  sensitive   = true
  default     = "ibts-api-key-dev"
}

variable "grafana_admin_password" {
  description = "Grafana admin password — set via TF_VAR_grafana_admin_password in CI"
  type        = string
  sensitive   = true
  default     = "ibts-grafana-dev"
}