# filename: infra-aws/inital/stage2-config/03-karpenter.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ── Pull cluster data from stage1 remote state
data "aws_eks_cluster" "this" {
  name = var.cluster_name
}

# ── Karpenter SQS queue for spot interruption events
resource "aws_sqs_queue" "karpenter_interruption" {
  name                      = "${var.cluster_name}-karpenter"
  message_retention_seconds = 300
  sqs_managed_sse_enabled   = true
}

# ── EventBridge rules → SQS
resource "aws_cloudwatch_event_rule" "karpenter_interruption_spot" {
  name        = "${var.cluster_name}-karpenter-spot"
  description = "Karpenter spot interruption warning"
  event_pattern = jsonencode({
    source      = ["aws.ec2"]
    detail-type = ["EC2 Spot Instance Interruption Warning"]
  })
}

resource "aws_cloudwatch_event_target" "karpenter_interruption_spot" {
  rule      = aws_cloudwatch_event_rule.karpenter_interruption_spot.name
  target_id = "KarpenterInterruptionQueueTarget"
  arn       = aws_sqs_queue.karpenter_interruption.arn
}

resource "aws_cloudwatch_event_rule" "karpenter_rebalance" {
  name        = "${var.cluster_name}-karpenter-rebalance"
  description = "Karpenter rebalance recommendation"
  event_pattern = jsonencode({
    source      = ["aws.ec2"]
    detail-type = ["EC2 Instance Rebalance Recommendation"]
  })
}

resource "aws_cloudwatch_event_target" "karpenter_rebalance" {
  rule      = aws_cloudwatch_event_rule.karpenter_rebalance.name
  target_id = "KarpenterRebalanceQueueTarget"
  arn       = aws_sqs_queue.karpenter_interruption.arn
}

resource "aws_cloudwatch_event_rule" "karpenter_instance_state" {
  name        = "${var.cluster_name}-karpenter-instance-state"
  description = "Karpenter EC2 instance state change"
  event_pattern = jsonencode({
    source      = ["aws.ec2"]
    detail-type = ["EC2 Instance State-change Notification"]
  })
}

resource "aws_cloudwatch_event_target" "karpenter_instance_state" {
  rule      = aws_cloudwatch_event_rule.karpenter_instance_state.name
  target_id = "KarpenterInstanceStateQueueTarget"
  arn       = aws_sqs_queue.karpenter_interruption.arn
}

# ── SQS policy allowing EventBridge to publish
resource "aws_sqs_queue_policy" "karpenter_interruption" {
  queue_url = aws_sqs_queue.karpenter_interruption.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowEventBridge"
      Effect    = "Allow"
      Principal = { Service = "events.amazonaws.com" }
      Action    = "sqs:SendMessage"
      Resource  = aws_sqs_queue.karpenter_interruption.arn
    }]
  })
}

# ── Node IAM role
resource "aws_iam_role" "karpenter_node" {
  name = "${var.cluster_name}-karpenter-node"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "karpenter_node_worker" {
  role       = aws_iam_role.karpenter_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_cni" {
  role       = aws_iam_role.karpenter_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_ecr" {
  role       = aws_iam_role.karpenter_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
}

resource "aws_iam_role_policy_attachment" "karpenter_node_ssm" {
  role       = aws_iam_role.karpenter_node.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "karpenter_node" {
  name = "${var.cluster_name}-karpenter-node"
  role = aws_iam_role.karpenter_node.name
}

# ── EKS access entry — lets Karpenter nodes auto-join cluster
resource "aws_eks_access_entry" "karpenter_node" {
  cluster_name  = var.cluster_name
  principal_arn = aws_iam_role.karpenter_node.arn
  type          = "EC2_LINUX"
}

# ── Karpenter controller IRSA
module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name                               = "${var.cluster_name}-karpenter-controller"
  attach_karpenter_controller_policy      = true
  karpenter_controller_cluster_id         = var.cluster_name
  karpenter_controller_node_iam_role_arns = [aws_iam_role.karpenter_node.arn]
  karpenter_sqs_queue_arn                 = aws_sqs_queue.karpenter_interruption.arn

  oidc_providers = {
    main = {
      provider_arn               = local.oidc_provider_arn
      namespace_service_accounts = ["kube-system:karpenter"]
    }
  }

  depends_on = [aws_sqs_queue.karpenter_interruption]
}

# ── Instance profile management permissions
# Karpenter v1 manages instance profiles itself at runtime
# The base module policy does not include iam:GetInstanceProfile /
# iam:CreateInstanceProfile / iam:AddRoleToInstanceProfile
# Without these the EC2NodeClass stays InstanceProfileReady=Unknown
resource "aws_iam_role_policy" "karpenter_controller_instance_profile" {
  name = "${var.cluster_name}-karpenter-instance-profile"
  role = module.karpenter_irsa.iam_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "KarpenterInstanceProfile"
      Effect = "Allow"
      Action = [
        "iam:CreateInstanceProfile",
        "iam:DeleteInstanceProfile",
        "iam:GetInstanceProfile",
        "iam:AddRoleToInstanceProfile",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:TagInstanceProfile"
      ]
      Resource = "arn:aws:iam::*:instance-profile/*"
    }]
  })
}

# ── ✅ ADDED: Karpenter v1 compatible EC2 launch permissions
#
# terraform-aws-modules/iam ~> 5.39 generates the Karpenter controller
# policy for Karpenter v0.x. It includes IAM conditions referencing:
#   karpenter.sh/provisioner-name   ← v0.x tag — no longer exists in v1
#
# Karpenter v1.0.8 uses a different tag:
#   karpenter.sh/nodepool           ← v1.x tag
#
# When the old condition is evaluated against v1 resources:
#   condition never matches → ec2:RunInstances DENIED by IAM
#   Karpenter creates NodeClaim successfully ✅
#   EC2 instance launch is silently denied ❌
#   NodeClaim stays READY=Unknown, TYPE/CAPACITY/ZONE/NODE all empty
#   Pods stay Pending forever
#
# This policy adds v1-compatible permissions with no restricting
# tag conditions on the old provisioner tag. It works alongside
# the base policy generated by the IRSA module.
resource "aws_iam_role_policy" "karpenter_controller_v1" {
  name = "${var.cluster_name}-karpenter-v1-launch"
  role = module.karpenter_irsa.iam_role_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      # EC2 describe + launch — no tag condition blocking on old tag
      {
        Sid    = "KarpenterV1EC2Launch"
        Effect = "Allow"
        Action = [
          "ec2:RunInstances",
          "ec2:CreateFleet",
          "ec2:CreateLaunchTemplate",
          "ec2:DeleteLaunchTemplate",
          "ec2:DescribeLaunchTemplates",
          "ec2:DescribeInstances",
          "ec2:DescribeInstanceTypes",
          "ec2:DescribeInstanceTypeOfferings",
          "ec2:DescribeAvailabilityZones",
          "ec2:DescribeImages",
          "ec2:DescribeSpotPriceHistory",
          "ec2:DescribeSecurityGroups",
          "ec2:DescribeSubnets",
          "ec2:DescribeVpcs"
        ]
        Resource = "*"
      },
      # Tagging + termination scoped to cluster-owned resources
      {
        Sid    = "KarpenterV1Tagging"
        Effect = "Allow"
        Action = [
          "ec2:CreateTags",
          "ec2:TerminateInstances",
          "ec2:DeleteLaunchTemplate"
        ]
        Resource = "*"
        Condition = {
          StringEquals = {
            "aws:ResourceTag/kubernetes.io/cluster/${var.cluster_name}" = "owned"
          }
        }
      },
      # PassRole — required to attach instance profile to launched EC2
      {
        Sid      = "KarpenterV1PassRole"
        Effect   = "Allow"
        Action   = "iam:PassRole"
        Resource = aws_iam_role.karpenter_node.arn
      },
      # SSM — resolves AMI ID from alias (al2@latest in EC2NodeClass)
      {
        Sid      = "KarpenterV1SSM"
        Effect   = "Allow"
        Action   = ["ssm:GetParameter"]
        Resource = "arn:aws:ssm:*:*:parameter/aws/service/eks/optimized-ami/*"
      },
      # Pricing — used for spot instance type selection scoring
      {
        Sid      = "KarpenterV1Pricing"
        Effect   = "Allow"
        Action   = "pricing:GetProducts"
        Resource = "*"
      }
    ]
  })

  depends_on = [module.karpenter_irsa]
}

# ── Karpenter controller service account
resource "kubernetes_service_account" "karpenter" {
  metadata {
    name      = "karpenter"
    namespace = "kube-system"
    annotations = {
      "eks.amazonaws.com/role-arn" = module.karpenter_irsa.iam_role_arn
    }
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.11"

  cluster_name    = var.cluster_name
  cluster_version = var.cluster_version

  vpc_id     = aws_vpc.ibts.id
  subnet_ids = aws_subnet.private[*].id

  cluster_endpoint_public_access  = true
  cluster_endpoint_private_access = true

  enable_irsa = true

  authentication_mode                      = "API_AND_CONFIG_MAP"
  enable_cluster_creator_admin_permissions = true

  cluster_enabled_log_types = ["api", "audit"]
  cluster_addons            = {}

  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
  }

  access_entries = {}

  tags = {
    "karpenter.sh/discovery" = var.cluster_name
  }

  eks_managed_node_groups = {
    system = {
      name           = "eks-system-nodes"
      instance_types = ["t3.medium"]

      min_size     = 1
      max_size     = 1
      desired_size = 1

      capacity_type = "ON_DEMAND"

      labels = {
        "node.kubernetes.io/purpose" = "system"
      }

      taints = {
        addons = {
          key    = "CriticalAddonsOnly"
          value  = "true"
          effect = "NO_SCHEDULE"
        }
      }
    }
  }
}
