# filename: infra-aws/inital/stage2-config/04-controllers.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ══════════════════════════════════════════════════════
# EBS CSI DRIVER
#
# WHY: Elasticsearch, Grafana, Prometheus all request PVCs
#      Without this controller those PVCs stay Pending forever
#      IRSA role already created in 02-irsa.tf → ebs_csi_irsa
#
# Service account name MUST match what IRSA expects:
#   namespace_service_accounts = ["kube-system:ebs-csi-controller-sa"]
# ══════════════════════════════════════════════════════

resource "kubernetes_service_account" "ebs_csi_controller" {
  metadata {
    name      = "ebs-csi-controller-sa"
    namespace = "kube-system"
    annotations = {
      "eks.amazonaws.com/role-arn" = module.ebs_csi_irsa.iam_role_arn
    }
  }
}

resource "helm_release" "ebs_csi_driver" {
  name       = "aws-ebs-csi-driver"
  namespace  = "kube-system"
  repository = "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
  chart      = "aws-ebs-csi-driver"
  version    = "2.29.1"

  values = [yamlencode({
    controller = {
      serviceAccount = {
        create = false
        name   = kubernetes_service_account.ebs_csi_controller.metadata[0].name
      }
    }
    storageClasses = [
      {
        name = "ebs-gp3"
        annotations = {
          "storageclass.kubernetes.io/is-default-class" = "true"
        }
        volumeBindingMode  = "WaitForFirstConsumer"
        reclaimPolicy      = "Retain"
        parameters = {
          type      = "gp3"
          encrypted = "true"
        }
      }
    ]
  })]

  depends_on = [kubernetes_service_account.ebs_csi_controller]
}

# ══════════════════════════════════════════════════════
# AWS LOAD BALANCER CONTROLLER
#
# WHY: api-gateway service uses type=LoadBalancer with
#      AWS NLB annotations — without this controller
#      the service stays in <pending> state forever
#
# IRSA role already created in 02-irsa.tf → irsa_aws_lb_controller
#
# Service account name MUST match what IRSA expects:
#   namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
# ══════════════════════════════════════════════════════

resource "kubernetes_service_account" "aws_lb_controller" {
  metadata {
    name      = "aws-load-balancer-controller"
    namespace = "kube-system"
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_aws_lb_controller.iam_role_arn
    }
  }
}

resource "helm_release" "aws_lb_controller" {
  name       = "aws-load-balancer-controller"
  namespace  = "kube-system"
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  version    = "1.7.2"

  values = [yamlencode({
    clusterName = var.cluster_name
    region      = var.aws_region
    vpcId       = data.terraform_remote_state.stage1.outputs.vpc_id

    serviceAccount = {
      create = false
      name   = kubernetes_service_account.aws_lb_controller.metadata[0].name
    }

    # Run on system nodes alongside other controllers
    nodeSelector = { "node.kubernetes.io/purpose" = "system" }
    tolerations = [{
      key      = "CriticalAddonsOnly"
      operator = "Exists"
      effect   = "NoSchedule"
    }]

    replicaCount = 1
  })]

  depends_on = [kubernetes_service_account.aws_lb_controller]
}
