# filename: infra-aws/stage2-config/05-namespaces.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

resource "kubernetes_namespace" "ibts_app" {
  metadata {
    name   = "ibts-app"
    labels = { name = "ibts-app", environment = var.environment }
  }
}

resource "kubernetes_namespace" "ibts_observability" {
  metadata {
    name   = "ibts-observability"
    labels = { name = "ibts-observability", environment = var.environment }
  }
}

resource "kubernetes_resource_quota" "ibts_app" {
  metadata {
    name      = "ibts-app-quota"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
  }
  spec {
    hard = {
      "requests.cpu"    = "2"
      "requests.memory" = "4Gi"
      "limits.cpu"      = "4"
      "limits.memory"   = "6Gi"
      "pods"            = "20"
    }
  }
}

resource "kubernetes_resource_quota" "ibts_observability" {
  metadata {
    name      = "ibts-observability-quota"
    namespace = kubernetes_namespace.ibts_observability.metadata[0].name
  }
  spec {
    hard = {
      "requests.cpu"    = "1"
      "requests.memory" = "2Gi"
      "limits.cpu"      = "2"
      "limits.memory"   = "3Gi"
      "pods"            = "15"
    }
  }
}

resource "kubernetes_service_account" "payment_switch" {
  metadata {
    name      = "payment-switch"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_payment_switch.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}

resource "kubernetes_service_account" "payment_router" {
  metadata {
    name      = "payment-router"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_payment_router.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}

resource "kubernetes_service_account" "idempotency_guard" {
  metadata {
    name      = "idempotency-guard"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_idempotency_guard.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}


