# filename: infra-aws/inital/stage2-config/05-namespaces.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

resource "kubernetes_namespace" "ibts_app" {
  metadata {
    name   = "ibts-app"
    labels = { name = "ibts-app", environment = var.environment }
  }
}

resource "kubernetes_namespace" "ibts_observability" {
  metadata {
    name   = "ibts-observability"
    labels = { name = "ibts-observability", environment = var.environment }
  }
}

resource "kubernetes_resource_quota" "ibts_app" {
  metadata {
    name      = "ibts-app-quota"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
  }
  spec {
    hard = {
      "requests.cpu"    = "2"
      "requests.memory" = "4Gi"
      "limits.cpu"      = "4"
      "limits.memory"   = "6Gi"
      "pods"            = "20"
    }
  }
}

resource "kubernetes_resource_quota" "ibts_observability" {
  metadata {
    name      = "ibts-observability-quota"
    namespace = kubernetes_namespace.ibts_observability.metadata[0].name
  }
  spec {
    hard = {
      # ✅ INCREASED — breakdown of what each component needs:
      # kube-prometheus-stack (operator+prometheus+grafana
      #   +alertmanager+node-exporter+kube-state-metrics): ~2 CPU req / 4Gi mem req
      # elasticsearch:                                       0.1 CPU req / 1Gi   mem req
      # kibana:                                              0.1 CPU req / 512Mi mem req
      # otel-collector:                                      0.05 CPU req / 128Mi mem req
      # jaeger:                                              0.05 CPU req / 128Mi mem req
      # fluent-bit (DaemonSet — 1 pod per node):             0.01 CPU req / 32Mi  mem req
      # ─────────────────────────────────────────────────────────────────────────────────
      # TOTAL requests:  ~2.5 CPU / ~6Gi   → set headroom at 4 CPU / 8Gi
      # TOTAL limits:    ~8   CPU / ~13Gi  → set headroom at 10 CPU / 14Gi
      "requests.cpu"    = "4"
      "requests.memory" = "8Gi"
      "limits.cpu"      = "10"
      "limits.memory"   = "14Gi"
      "pods"            = "50"
    }
  }
}

resource "kubernetes_service_account" "payment_switch" {
  metadata {
    name      = "payment-switch"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_payment_switch.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}

resource "kubernetes_service_account" "payment_router" {
  metadata {
    name      = "payment-router"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_payment_router.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}

resource "kubernetes_service_account" "idempotency_guard" {
  metadata {
    name      = "idempotency-guard"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
    annotations = {
      "eks.amazonaws.com/role-arn" = module.irsa_idempotency_guard.iam_role_arn
    }
  }
  depends_on = [kubernetes_namespace.ibts_app]
}
