# filename: infra-aws/inital/stage2-config/06-dynamodb.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

resource "aws_dynamodb_table" "idempotency_records" {
  name         = "IdempotencyRecords"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "idempotency_key"

  attribute {
    name = "idempotency_key"
    type = "S"
  }

  ttl {
    attribute_name = "expiry_time"
    enabled        = true
  }

  tags = { Service = "idempotency-guard" }
}

resource "aws_dynamodb_table" "ibts_transactions" {
  name         = "ibts-transactions"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "transaction_id"

  attribute {
    name = "transaction_id"
    type = "S"
  }

  attribute {
    name = "status"
    type = "S"
  }

  global_secondary_index {
    name            = "status-index"
    hash_key        = "status"
    projection_type = "ALL"
  }

  tags = { Service = "payment-switch" }
}

resource "aws_dynamodb_table" "routing_table" {
  name         = "routing-table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "vpa_suffix"

  attribute {
    name = "vpa_suffix"
    type = "S"
  }

  tags = { Service = "payment-router" }
}
