# filename: infra-aws/inital/stage2-config/07-sqs-app.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

resource "aws_sqs_queue" "settlement_events" {
  name                       = "ibts-settlement-events"
  message_retention_seconds  = 86400
  visibility_timeout_seconds = 30
  sqs_managed_sse_enabled    = true
}

resource "aws_sqs_queue" "settlement_events_dlq" {
  name                      = "ibts-settlement-events-dlq"
  message_retention_seconds = 1209600
  sqs_managed_sse_enabled   = true
}

resource "aws_sqs_queue_redrive_policy" "settlement_events" {
  queue_url = aws_sqs_queue.settlement_events.id
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.settlement_events_dlq.arn
    maxReceiveCount     = 3
  })
}

resource "aws_sqs_queue_policy" "settlement_events" {
  queue_url = aws_sqs_queue.settlement_events.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "AllowPaymentSwitch"
      Effect    = "Allow"
      Principal = { AWS = module.irsa_payment_switch.iam_role_arn }
      Action    = ["sqs:SendMessage", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:GetQueueAttributes"]
      Resource  = aws_sqs_queue.settlement_events.arn
    }]
  })
}
