# filename: infra-aws/inital/stage2-config/08-app-config.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ══════════════════════════════════════════════════════
# SECRETS
# Your deployments reference these by name:
#   envFrom.secretRef.name: api-gateway-secrets
# ══════════════════════════════════════════════════════

resource "kubernetes_secret" "api_gateway" {
  metadata {
    name      = "api-gateway-secrets"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
  }

  data = {
    JWT_SECRET = var.jwt_secret
    API_KEY    = var.api_key
  }

  type = "Opaque"
}

# ══════════════════════════════════════════════════════
# SHARED CONFIG MAP
# Your deployments reference this by name:
#   envFrom.configMapRef.name: ibts-shared-config
#
# Contains all non-secret env vars so your deployment
# manifests don't hardcode region, OTel endpoint etc.
# ══════════════════════════════════════════════════════

resource "kubernetes_config_map" "ibts_shared" {
  metadata {
    name      = "ibts-shared-config"
    namespace = kubernetes_namespace.ibts_app.metadata[0].name
  }

  data = {
    # AWS
    AWS_DEFAULT_REGION = var.aws_region

    # DynamoDB table names — pulled from actual table resources
    DYNAMODB_TABLE_NAME_IDEMPOTENCY = aws_dynamodb_table.idempotency_records.name
    DYNAMODB_TABLE_NAME_TRANSACTIONS = aws_dynamodb_table.ibts_transactions.name
    ROUTING_TABLE_NAME              = aws_dynamodb_table.routing_table.name

    # SQS queue name — pulled from actual queue resource
    SQS_QUEUE_NAME = aws_sqs_queue.settlement_events.name

    # OTel — points to in-cluster collector
    OTEL_EXPORTER_OTLP_ENDPOINT = "http://otel-collector.${kubernetes_namespace.ibts_observability.metadata[0].name}.svc.cluster.local:4318"
    OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
    OTEL_TRACES_EXPORTER         = "otlp"
    OTEL_METRICS_EXPORTER        = "none"
    OTEL_LOGS_EXPORTER           = "none"
    OTEL_PYTHON_LOG_CORRELATION  = "true"

    # Inter-service URLs — use k8s DNS
    IDEMPOTENCY_GUARD_URL = "http://idempotency-guard.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local:8080"
    PAYMENT_ROUTER_URL    = "http://payment-router.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local:8081"
    BANK_ADAPTER_URL      = "http://bank-adapter.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local:8082"
    PAYMENT_SWITCH_URL    = "http://payment-switch.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local:8083"
    REDIS_HOST            = "redis.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local"
    REDIS_PORT            = "6379"
    MOCK_BANK_URL         = "http://mock-bank-server.${kubernetes_namespace.ibts_app.metadata[0].name}.svc.cluster.local:8080"
  }
}
