# filename: infra-aws/inital/stage2-config/09-observability.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

locals {
  obs_ns = kubernetes_namespace.ibts_observability.metadata[0].name
}

# ══════════════════════════════════════════════════════
# PROMETHEUS + GRAFANA + ALERTMANAGER
#
# FIX: disabled admission webhooks
#
# kube-prometheus-stack runs a pre-install Job to generate
# TLS certs for its ValidatingWebhookConfiguration.
# That Job cannot schedule fast enough in CI → hook times out
# → entire release fails before any pod is created
#
# admissionWebhooks.enabled = false
#   → skips pre-install + pre-delete hook Jobs entirely
#   → no ValidatingWebhookConfiguration created
#   → prometheus still works 100% — webhooks only validate
#     PrometheusRule CRDs (nice to have, not required)
# ══════════════════════════════════════════════════════

resource "helm_release" "kube_prometheus_stack" {
  name             = "kube-prometheus-stack"
  namespace        = local.obs_ns
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "kube-prometheus-stack"
  version          = "58.2.2"
  create_namespace = false
  timeout          = 900
  atomic           = false
  cleanup_on_fail  = false

  values = [yamlencode({
    prometheusOperator = {
      admissionWebhooks = {
        # ✅ KEY FIX: disables the pre-install Job that was timing out
        # The Job tries to create a TLS cert via a pod
        # Pod cannot schedule fast enough in pipeline → hook timeout
        # Disabling this skips the hook entirely
        enabled = false
        patch = {
          enabled = false
        }
      }
      # Don't request high resources for the operator itself
      resources = {
        requests = { cpu = "50m", memory = "64Mi" }
        limits   = { cpu = "200m", memory = "256Mi" }
      }
    }
    prometheus = {
      prometheusSpec = {
        retention = "30d"
        podMonitorSelectorNilUsesHelmValues     = false
        serviceMonitorSelectorNilUsesHelmValues = false
        resources = {
          requests = { cpu = "200m", memory = "512Mi" }
          limits   = { cpu = "500m", memory = "1Gi" }
        }
        storageSpec = {
          volumeClaimTemplate = {
            spec = {
              storageClassName = "gp3"
              resources = { requests = { storage = "10Gi" } }
            }
          }
        }
      }
    }
    grafana = {
      enabled                  = true
      adminPassword            = var.grafana_admin_password
      defaultDashboardsEnabled = true
      persistence = {
        enabled          = true
        storageClassName = "gp3"
        size             = "5Gi"
      }
      resources = {
        requests = { cpu = "50m", memory = "128Mi" }
        limits   = { cpu = "200m", memory = "256Mi" }
      }
    }
    alertmanager = {
      enabled = true
      alertmanagerSpec = {
        storage = {
          volumeClaimTemplate = {
            spec = {
              storageClassName = "gp3"
              resources = { requests = { storage = "2Gi" } }
            }
          }
        }
        resources = {
          requests = { cpu = "10m", memory = "64Mi" }
          limits   = { cpu = "100m", memory = "128Mi" }
        }
      }
    }
    kubelet = {
      enabled        = true
      serviceMonitor = { cAdvisor = true }
    }
    prometheus-node-exporter = {
      resources = {
        requests = { cpu = "10m", memory = "32Mi" }
        limits   = { cpu = "100m", memory = "64Mi" }
      }
    }
    kube-state-metrics = {
      resources = {
        requests = { cpu = "10m", memory = "64Mi" }
        limits   = { cpu = "100m", memory = "128Mi" }
      }
    }
  })]

  depends_on = [kubernetes_namespace.ibts_observability]
}

# ══════════════════════════════════════════════════════
# ELASTICSEARCH
# ══════════════════════════════════════════════════════

resource "helm_release" "elasticsearch" {
  name             = "elasticsearch"
  namespace        = local.obs_ns
  repository       = "https://helm.elastic.co"
  chart            = "elasticsearch"
  version          = "8.5.1"
  create_namespace = false
  timeout          = 900
  atomic           = false
  cleanup_on_fail  = false

  values = [yamlencode({
    replicas           = 1
    minimumMasterNodes = 1
    esJavaOpts         = "-Xmx512m -Xms512m"
    resources = {
      requests = { cpu = "100m", memory = "1Gi" }
      limits   = { cpu = "1000m", memory = "1.5Gi" }
    }
    volumeClaimTemplate = {
      storageClassName = "gp3"
      resources = { requests = { storage = "10Gi" } }
    }
    esConfig = {
      "elasticsearch.yml" = "xpack.security.enabled: false\nxpack.ml.enabled: false\n"
    }
  })]

  # ✅ Explicit depends_on — only starts after prometheus stack
  # avoids race condition where both try to schedule large pods simultaneously
  depends_on = [helm_release.kube_prometheus_stack]
}

# ══════════════════════════════════════════════════════
# KIBANA
# ══════════════════════════════════════════════════════

resource "helm_release" "kibana" {
  name             = "kibana"
  namespace        = local.obs_ns
  repository       = "https://helm.elastic.co"
  chart            = "kibana"
  version          = "8.5.1"
  create_namespace = false
  timeout          = 600

  values = [yamlencode({
    elasticsearchHosts = "http://elasticsearch-master.${local.obs_ns}.svc.cluster.local:9200"
    resources = {
      requests = { cpu = "100m", memory = "512Mi" }
      limits   = { cpu = "500m", memory = "1Gi" }
    }
  })]

  depends_on = [helm_release.elasticsearch]
}

# ══════════════════════════════════════════════════════
# OTEL COLLECTOR
#
# FIX: image.repository explicitly declared (breaking change v0.91.0)
# ══════════════════════════════════════════════════════

resource "helm_release" "otel_collector" {
  name             = "otel-collector"
  namespace        = local.obs_ns
  repository       = "https://open-telemetry.github.io/opentelemetry-helm-charts"
  chart            = "opentelemetry-collector"
  version          = "0.91.0"
  create_namespace = false
  timeout          = 300

  values = [yamlencode({
    mode = "deployment"

    # ✅ Required since chart v0.91.0 — removed from defaults
    image = {
      repository = "otel/opentelemetry-collector-contrib"
    }

    config = {
      receivers = {
        otlp = {
          protocols = {
            grpc = { endpoint = "0.0.0.0:4317" }
            http = { endpoint = "0.0.0.0:4318" }
          }
        }
      }
      processors = {
        batch          = {}
        memory_limiter = {
          check_interval         = "1s"
          limit_percentage       = 75
          spike_limit_percentage = 15
        }
      }
      exporters = {
        otlp = {
          endpoint = "jaeger-collector.${local.obs_ns}.svc.cluster.local:4317"
          tls      = { insecure = true }
        }
        prometheus = { endpoint = "0.0.0.0:8889" }
      }
      service = {
        pipelines = {
          traces = {
            receivers  = ["otlp"]
            processors = ["memory_limiter", "batch"]
            exporters  = ["otlp"]
          }
        }
      }
    }
    ports = {
      otlp      = { enabled = true, containerPort = 4317, servicePort = 4317 }
      otlp-http = { enabled = true, containerPort = 4318, servicePort = 4318 }
      metrics   = { enabled = true, containerPort = 8889, servicePort = 8889 }
    }
    resources = {
      requests = { cpu = "50m", memory = "128Mi" }
      limits   = { cpu = "200m", memory = "256Mi" }
    }
  })]

  # ✅ Waits for prometheus stack — avoids parallel scheduling pressure
  depends_on = [helm_release.kube_prometheus_stack]
}

# ══════════════════════════════════════════════════════
# JAEGER
# ══════════════════════════════════════════════════════

resource "helm_release" "jaeger" {
  name             = "jaeger"
  namespace        = local.obs_ns
  repository       = "https://jaegertracing.github.io/helm-charts"
  chart            = "jaeger"
  version          = "3.0.0"
  create_namespace = false
  timeout          = 300

  values = [yamlencode({
    provisionDataStore = { cassandra = false, elasticsearch = false }
    storage = {
      type = "elasticsearch"
      elasticsearch = {
        host   = "elasticsearch-master.${local.obs_ns}.svc.cluster.local"
        port   = 9200
        scheme = "http"
      }
    }
    collector = { enabled = true }
    query = {
      enabled = true
      service = { type = "ClusterIP", port = 16686 }
    }
    agent = { enabled = false }
  })]

  depends_on = [helm_release.elasticsearch]
}

# ══════════════════════════════════════════════════════
# FLUENT-BIT DaemonSet
# ══════════════════════════════════════════════════════

resource "helm_release" "fluent_bit" {
  name             = "fluent-bit"
  namespace        = local.obs_ns
  repository       = "https://fluent.github.io/helm-charts"
  chart            = "fluent-bit"
  version          = "0.46.7"
  create_namespace = false
  timeout          = 300

  values = [yamlencode({
    kind = "DaemonSet"
    config = {
      inputs = <<-EOF
        [INPUT]
            Name            tail
            Tag             kube.*
            Path            /var/log/containers/*.log
            Parser          cri
            Mem_Buf_Limit   5MB
            Skip_Long_Lines On
      EOF
      filters = <<-EOF
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
            Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
            Merge_Log           On
            Keep_Log            Off
            K8S-Logging.Parser  On
            K8S-Logging.Exclude On
      EOF
      outputs = <<-EOF
        [OUTPUT]
            Name               es
            Match              kube.*
            Host               elasticsearch-master.${local.obs_ns}.svc.cluster.local
            Port               9200
            Index              ibts-logs
            Suppress_Type_Name On
      EOF
    }
    tolerations = [{
      key      = "CriticalAddonsOnly"
      operator = "Exists"
      effect   = "NoSchedule"
    }]
    resources = {
      requests = { cpu = "10m", memory = "32Mi" }
      limits   = { cpu = "100m", memory = "128Mi" }
    }
  })]

  depends_on = [helm_release.elasticsearch]
}
