# filename: infra-aws/inital/stage2-config/09-observability.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.
#
# Observability Helm stack (prometheus, elasticsearch, kibana,
# otel-collector, jaeger, fluent-bit) is intentionally NOT managed
# by Terraform. Deployed separately via scripts/deploy-observability.sh
# after Terraform is green.
#
# Reason: kube-prometheus-stack pre-install webhook Job consistently
# times out in CI regardless of timeout/quota settings.
# Helm CLI deployment outside Terraform has no this constraint.

locals {
  obs_ns = kubernetes_namespace.ibts_observability.metadata[0].name
}
