# filename: infra-aws/stage2-config/terraform.tfvars
# Code Generated by Sidekick is for learning and experimentation purposes only.

aws_region                       = "ap-south-2"
environment                      = "poc"
cluster_name                     = "ibts-eks"
karpenter_version                = "1.0.8"
aws_lb_controller_version        = "1.8.1"
karpenter_spot_instance_families = ["t3", "t3a"]
karpenter_spot_instance_sizes    = ["medium", "large"]
