# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/main.py

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from pydantic import ValidationError
from datetime import datetime, timezone
from app.routers import route_router

app = FastAPI(title="payment-router", version="1.0.0")

app.include_router(route_router.router)


from app.routers.payment_router import router as payment_router
app.include_router(payment_router)

@app.exception_handler(ValidationError)
async def validation_handler(request: Request, exc: ValidationError):
    return JSONResponse(status_code=422, content={
        "status": 422,
        "message": exc.errors()[0]["msg"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })

@app.get("/actuator/health")
def health():
    return {"status": "UP", "services": "payment-router"}
