# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/test-payment-router.ps1

param(
  [string]$BaseUrl = "http://localhost:8081"
)

$pass = 0; $fail = 0

function Assert-Pass { param([string]$L) Write-Host "  [PASS] $L" -ForegroundColor Green;  $script:pass++ }
function Assert-Fail { param([string]$L, [string]$D="") Write-Host "  [FAIL] $L $D" -ForegroundColor Red; $script:fail++ }

function Invoke-Api {
    param([string]$Uri, [string]$Method="GET", [string]$Body=$null)
    $p = @{ Uri=$Uri; Method=$Method; ContentType="application/json"; ErrorAction="Stop" }
    if ($Body) { $p.Body = $Body }
    return Invoke-RestMethod @p
}

function Test-Case { param([string]$Id, [string]$Desc)
    Write-Host "`n[$Id] $Desc" -ForegroundColor Cyan
}

# T01
Test-Case "T01" "Health check"
try {
    $r = Invoke-Api -Uri "$BaseUrl/actuator/health"
    if ($r.status -eq "UP") { Assert-Pass "status=UP" }
    else { Assert-Fail "Expected UP" $r.status }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T02
Test-Case "T02" "VPA resolve - john@sbi -> SBI (DB first load)"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@sbi"}'
    if ($r.bankCode -eq "SBI" -and $r.resolvedFrom -eq "DB") { Assert-Pass "bankCode=SBI resolvedFrom=DB" }
    else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T03
Test-Case "T03" "VPA resolve - john@sbi -> SBI (cache hit)"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@sbi"}'
    if ($r.bankCode -eq "SBI" -and $r.resolvedFrom -eq "CACHE" -and $r.ttlRemainingMs -gt 0) {
        Assert-Pass "resolvedFrom=CACHE ttlRemainingMs=$($r.ttlRemainingMs)"
    } else { Assert-Fail "Expected CACHE hit" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T04
Test-Case "T04" "VPA resolve - john@okicici -> ICICI"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@okicici"}'
    if ($r.bankCode -eq "ICICI") { Assert-Pass "bankCode=ICICI" }
    else { Assert-Fail "Expected ICICI" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T05
Test-Case "T05" "VPA resolve - john@ybl -> YESBANK (PhonePe handle)"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@ybl"}'
    if ($r.bankCode -eq "YESBANK") { Assert-Pass "bankCode=YESBANK" }
    else { Assert-Fail "Expected YESBANK" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T06
Test-Case "T06" "IFSC resolve - SBIN0001234 -> SBI"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"ifsc":"SBIN0001234"}'
    if ($r.bankCode -eq "SBI") { Assert-Pass "bankCode=SBI via IFSC" }
    else { Assert-Fail "Expected SBI" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T07
Test-Case "T07" "IFSC resolve - HDFC0000123 -> HDFC"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"ifsc":"HDFC0000123"}'
    if ($r.bankCode -eq "HDFC") { Assert-Pass "bankCode=HDFC via IFSC" }
    else { Assert-Fail "Expected HDFC" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T08
Test-Case "T08" "Unknown VPA handle - expect 404"
try {
    Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@unknownxyz"}'
    Assert-Fail "Expected 404 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 404) { Assert-Pass "404 unknown handle" }
    else { Assert-Fail "Wrong status code: $code" }
}

# T09
Test-Case "T09" "Unknown IFSC prefix - expect 404"
try {
    Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"ifsc":"ZZZZ0001234"}'
    Assert-Fail "Expected 404 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 404) { Assert-Pass "404 unknown IFSC prefix" }
    else { Assert-Fail "Wrong status code: $code" }
}

# T10
Test-Case "T10" "Both vpa and ifsc - expect 422"
try {
    Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST `
        -Body '{"vpa":"john@sbi","ifsc":"SBIN0001234"}'
    Assert-Fail "Expected 422 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 422) { Assert-Pass "422 both fields rejected" }
    else { Assert-Fail "Wrong status code: $code" }
}

# T11
Test-Case "T11" "Neither vpa nor ifsc - expect 422"
try {
    Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{}'
    Assert-Fail "Expected 422 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 422) { Assert-Pass "422 empty body rejected" }
    else { Assert-Fail "Wrong status code: $code" }
}

# T12
Test-Case "T12" "fallbackEndpoint populated - HDFC"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/route/resolve" -Method POST -Body '{"vpa":"john@okhdfcbank"}'
    if ($r.bankCode -eq "HDFC" -and $r.fallbackEndpoint) {
        Assert-Pass "HDFC fallbackEndpoint=$($r.fallbackEndpoint)"
    } else { Assert-Fail "Missing fallbackEndpoint" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T13
Test-Case "T13" "Debug scan - 13 banks seeded"
try {
    $routes = Invoke-Api -Uri "$BaseUrl/api/v1/route/debug/routes"
    $count  = ($routes | Measure-Object).Count
    if ($count -ge 13) { Assert-Pass "$count routes in DynamoDB" }
    else { Assert-Fail "Expected 13+, got $count" }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# ── Summary ────────────────────────────────────────────────────────────────
$total = $pass + $fail
Write-Host "`n======================================" -ForegroundColor White
Write-Host " RESULTS: $pass/$total passed" -ForegroundColor $(if ($fail -eq 0){"Green"}else{"Yellow"})
if ($fail -gt 0) { Write-Host " $fail test(s) FAILED" -ForegroundColor Red }
else             { Write-Host " All tests passed - payment-router healthy" -ForegroundColor Green }
Write-Host "======================================`n" -ForegroundColor White
