# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: api-gateway/tests/all.ps1
#
# Unified IBTS test suite -- ALL traffic through API Gateway (port 8084)
#
#   Phase 0  Pre-flight
#   Phase 1  Idempotency
#   Phase 2  Routing
#   Phase 3  Input Validation
#   Phase 4  Circuit Breaker
#   Phase 5  Rate Limiting
#   Teardown
#
# Usage:
#   .\all.ps1
#   .\all.ps1 -SkipSlowTests    # skips 32 s breaker reset sleep
# ==============================================================================

param([switch]$SkipSlowTests)

$ErrorActionPreference = "Continue"

$GW_URL      = "http://localhost:8084"
$API_KEY     = "ibts-api-key-dev"
$AWS_EP      = "http://localhost:4566"
$REGION      = "ap-south-1"
$ROUTING_TBL = "routing-table"
$RESET_SECS  = 32
$RL_WINDOW   = 65      # seconds -- Retry-After=60 so wait 65 to be safe

$global:PASS   = 0
$global:FAIL   = 0
$global:RUN_ID = Get-Date -Format "yyyyMMddHHmmss"

# ==============================================================================
# Output helpers
# ==============================================================================
function Write-Pass([string]$m) { Write-Host "  [PASS] $m" -ForegroundColor Green;  $global:PASS++ }
function Write-Fail([string]$m) { Write-Host "  [FAIL] $m" -ForegroundColor Red;    $global:FAIL++ }

function Write-Section([string]$phase, [string]$title) {
    Write-Host ""
    Write-Host "----------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "  $phase  |  $title"                                   -ForegroundColor Cyan
    Write-Host "----------------------------------------------------" -ForegroundColor DarkGray
}

function Write-Case([string]$id, [string]$desc) {
    Write-Host ""
    Write-Host "  [$id] $desc" -ForegroundColor White
}

function New-IdemKey { "ibts-$global:RUN_ID-$(New-Guid)" }

# Wait for IP rate-limit window to expire between heavy phases
function Wait-RateLimit([string]$reason = "rate-limit window reset") {
    Write-Host ""
    Write-Host "  [WAIT] Sleeping $RL_WINDOW s -- $reason" -ForegroundColor DarkYellow
    Start-Sleep -Seconds $RL_WINDOW
}

# ==============================================================================
# Invoke-GW
#   -Body        : any hashtable or ordered dict (no type constraint)
#   -IdemKey     : adds x-idempotency-key header
#   -ExtraHeader : raw "Name: value" string appended last
#   -SkipApiKey  : omit the default x-api-key header (for auth tests)
# ==============================================================================
function Invoke-GW {
    param(
        [string] $Path,
        [string] $Method      = "GET",
        $Body                 = $null,    # no type -- accepts @{} and [ordered]@{}
        [string] $IdemKey     = $null,
        [string] $ExtraHeader = $null,
        [switch] $SkipApiKey
    )

    $uri     = "$GW_URL$Path"
    $tmpFile = $null

    $curlArgs = @("-s", "-X", $Method, $uri,
                  "-H", "Content-Type: application/json",
                  "-D", "-",
                  "-w", "`nHTTP_CODE:%{http_code}")

    if (-not $SkipApiKey) { $curlArgs += @("-H", "x-api-key: $API_KEY") }
    if ($IdemKey)          { $curlArgs += @("-H", "x-idempotency-key: $IdemKey") }
    if ($ExtraHeader)      { $curlArgs += @("-H", $ExtraHeader) }

    if ($Body) {
        $tmpFile = [System.IO.Path]::GetTempFileName() + ".json"
        [System.IO.File]::WriteAllText(
            $tmpFile,
            ($Body | ConvertTo-Json -Depth 5),
            [System.Text.UTF8Encoding]::new($false)
        )
        $curlArgs += @("-d", "@$tmpFile")
    }

    $raw = & curl.exe @curlArgs
    if ($tmpFile) { Remove-Item $tmpFile -Force -ErrorAction SilentlyContinue }

    $lines    = $raw -split "`r?`n"
    $codeLine = $lines | Where-Object { $_ -match "^HTTP_CODE:" } | Select-Object -Last 1
    $httpCode = [int]($codeLine -replace "HTTP_CODE:", "")

    $hdrs = @{}
    foreach ($l in $lines) {
        if ($l -match "^([A-Za-z0-9\-]+):\s*(.+)$" -and $l -notmatch "^HTTP_CODE:") {
            $hdrs[$Matches[1].ToLower()] = $Matches[2].Trim()
        }
    }

    $bodyText = (($lines | Where-Object {
        $_ -notmatch "^HTTP[_/]"           -and
        $_ -notmatch "^HTTP_CODE:"         -and
        $_ -notmatch "^[A-Za-z0-9\-]+:\s" -and
        $_.Trim() -ne ""
    }) -join "").Trim()

    $obj = $bodyText | ConvertFrom-Json -ErrorAction SilentlyContinue

    [ordered]@{
        httpCode = $httpCode
        body     = $bodyText
        obj      = $obj
        headers  = $hdrs
        detail   = if ($obj -and $obj.detail)   { "$($obj.detail)"   } else { "" }
        status   = if ($obj -and $obj.status)    { "$($obj.status)"   } else { "" }
        txn_id   = if ($obj -and $obj.txn_id)    { "$($obj.txn_id)"   } else { "" }
        bank_rrn = if ($obj -and $obj.bank_rrn)  { "$($obj.bank_rrn)" } else { "" }
        source   = if ($obj -and $obj.source)    { "$($obj.source)"   } else { "" }
        message  = if ($obj -and $obj.message)   { "$($obj.message)"  } else { "" }
    }
}

# ==============================================================================
# Infrastructure helpers
# ==============================================================================
function Set-SBIRoute([string]$Primary, [string]$Fallback) {
    Write-Host "    [Route] SBI primary=$Primary" -ForegroundColor DarkGray
    $ts  = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
    $tmp = [System.IO.Path]::GetTempFileName()
    $item = @{
        bankCode         = @{ S    = "SBI" }
        bankName         = @{ S    = "State Bank of India" }
        primaryEndpoint  = @{ S    = $Primary }
        fallbackEndpoint = @{ S    = $Fallback }
        active           = @{ BOOL = $true }
        updatedAt        = @{ N    = "$ts" }
    } | ConvertTo-Json -Depth 5
    [System.IO.File]::WriteAllText($tmp, $item, [System.Text.UTF8Encoding]::new($false))
    $out = aws --endpoint-url $AWS_EP dynamodb put-item `
               --region $REGION --table-name $ROUTING_TBL --item "file://$tmp" 2>&1
    Remove-Item $tmp -Force
    if ($LASTEXITCODE -ne 0) { Write-Host "    [ERR] DynamoDB: $out" -ForegroundColor DarkRed }
    else                     { Write-Host "    [OK]  DynamoDB updated" -ForegroundColor DarkGray }
    docker exec ibts-redis redis-cli DEL "route:SBI" | Out-Null
    Write-Host "    [OK]  Redis route:SBI evicted" -ForegroundColor DarkGray
    Start-Sleep -Milliseconds 400
}

function Get-BreakerState([string]$BankCode) {
    $py   = "import urllib.request; print(urllib.request.urlopen('http://localhost:8082/api/v1/adapter/debug/breakers').read().decode())"
    $json = docker exec bank-adapter python3 -c $py 2>$null
    if ([string]::IsNullOrWhiteSpace($json)) { return @{ state = "unknown"; fail_count = -1 } }
    $all   = $json | ConvertFrom-Json -ErrorAction SilentlyContinue
    $entry = $all.PSObject.Properties[$BankCode.ToUpper()]
    if ($null -eq $entry) { return @{ state = "closed"; fail_count = 0 } }
    @{ state = "$($entry.Value.state)"; fail_count = [int]"$($entry.Value.fail_count)" }
}

function Reset-Breaker([string]$BankCode) {
    $py = "import urllib.request; urllib.request.urlopen(urllib.request.Request('http://localhost:8082/api/v1/adapter/debug/breakers/$BankCode/reset',data=b'',method='POST'))"
    docker exec bank-adapter python3 -c $py 2>$null | Out-Null
    Write-Host "    [OK]  Breaker $BankCode reset to CLOSED" -ForegroundColor DarkGray
}

function Send-Payment {
    param(
        [string]$PayerVpa, [string]$PayeeVpa,
        [int]$Paise, [string]$Label, [string]$IdemKey = $null
    )
    if (-not $IdemKey) { $IdemKey = New-IdemKey }
    Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey $IdemKey -Body @{
        payer_vpa       = $PayerVpa
        payee_vpa       = $PayeeVpa
        amount_paise    = $Paise
        idempotency_key = $IdemKey
        remarks         = $Label
    }
}

# ==============================================================================
# PHASE 0 -- Pre-flight  (no payments, no rate-limit spend)
# ==============================================================================
Write-Section "PHASE 0" "Pre-flight"

Write-Case "P0-01" "API Gateway health"
$h = Invoke-GW -Path "/actuator/health"
Write-Host "    [DBG] http=$($h.httpCode) body=$($h.body)" -ForegroundColor DarkGray
if ($h.httpCode -eq 200 -and $h.status -eq "UP") { Write-Pass "Gateway status=UP" }
else { Write-Fail "Gateway not UP  http=$($h.httpCode) body=$($h.body)" }

Write-Case "P0-02" "Missing x-api-key -> 401 or 403"
# -SkipApiKey suppresses the default header entirely
$noKey = Invoke-GW -Path "/api/v1/payments" -Method POST -SkipApiKey -Body @{
    payer_vpa       = "a@sbi"
    payee_vpa       = "b@sbi"
    amount_paise    = 100
    idempotency_key = "preflight-nokey-$global:RUN_ID"
}
Write-Host "    [DBG] http=$($noKey.httpCode)" -ForegroundColor DarkGray
if ($noKey.httpCode -in @(401, 403)) { Write-Pass "Rejected without API key  http=$($noKey.httpCode)" }
else { Write-Fail "Expected 401/403 got $($noKey.httpCode)" }

Write-Case "P0-03" "Redis reachable"
$ping = docker exec ibts-redis redis-cli PING 2>&1
if ($ping -match "PONG") { Write-Pass "Redis PONG" }
else                     { Write-Fail "Redis unreachable: $ping" }

Write-Case "P0-04" "LocalStack DynamoDB reachable"
$tbls = aws --endpoint-url $AWS_EP dynamodb list-tables --region $REGION 2>&1
if ($LASTEXITCODE -eq 0) { Write-Pass "LocalStack DynamoDB OK" }
else                     { Write-Fail "LocalStack error: $tbls" }

# ==============================================================================
# PHASE 1 -- Idempotency
# ==============================================================================
Write-Section "PHASE 1" "Idempotency"

Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
             -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

$iKey1  = New-IdemKey
$iKey2  = New-IdemKey
$iTxnId = $null

Write-Case "P1-01" "First request -- new key -> 200 SUCCESS source=NEW"
$r = Send-Payment "alice@sbi" "bob@sbi" 10000 "idem-first" $iKey1
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status) source=$($r.source) txn=$($r.txn_id)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS" -and $r.source -eq "NEW") {
    Write-Pass "200 SUCCESS source=NEW txn_id=$($r.txn_id)"
    $iTxnId = $r.txn_id
} else { Write-Fail "Expected 200/SUCCESS/NEW  got http=$($r.httpCode) status=$($r.status) source=$($r.source)" }

Write-Case "P1-02" "Replay same key -> 200 SUCCESS source=CACHED (same txn_id)"
$r2 = Send-Payment "alice@sbi" "bob@sbi" 10000 "idem-replay" $iKey1
Write-Host "    [DBG] http=$($r2.httpCode) source=$($r2.source) txn=$($r2.txn_id)" -ForegroundColor DarkGray
if ($r2.httpCode -eq 200 -and $r2.source -eq "CACHED" -and $r2.txn_id -eq $iTxnId) {
    Write-Pass "200 CACHED same txn_id=$($r2.txn_id)"
} else { Write-Fail "Expected CACHED  got source=$($r2.source) txn=$($r2.txn_id)" }

Write-Case "P1-03" "Third replay -- still CACHED"
$r3 = Send-Payment "alice@sbi" "bob@sbi" 10000 "idem-replay2" $iKey1
Write-Host "    [DBG] http=$($r3.httpCode) source=$($r3.source)" -ForegroundColor DarkGray
if ($r3.httpCode -eq 200 -and $r3.source -eq "CACHED") { Write-Pass "200 CACHED on 3rd replay" }
else { Write-Fail "Expected CACHED  got http=$($r3.httpCode) source=$($r3.source)" }

Write-Case "P1-04" "Different key -- independent NEW transaction"
$r4 = Send-Payment "alice@sbi" "bob@sbi" 10000 "idem-different" $iKey2
Write-Host "    [DBG] http=$($r4.httpCode) source=$($r4.source) txn=$($r4.txn_id)" -ForegroundColor DarkGray
if ($r4.httpCode -eq 200 -and $r4.source -eq "NEW" -and $r4.txn_id -ne $iTxnId) {
    Write-Pass "NEW transaction txn_id=$($r4.txn_id)"
} else { Write-Fail "Expected NEW/different txn  got source=$($r4.source) txn=$($r4.txn_id)" }

Write-Case "P1-05" "Amount mismatch on existing key -> 422 or CACHED (must not create new txn)"
$r5 = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey $iKey1 -Body @{
    payer_vpa       = "alice@sbi"
    payee_vpa       = "bob@sbi"
    amount_paise    = 99999
    idempotency_key = $iKey1
    remarks         = "amount-mismatch"
}
Write-Host "    [DBG] http=$($r5.httpCode) source=$($r5.source) detail=$($r5.detail)" -ForegroundColor DarkGray
if ($r5.httpCode -eq 422 -or $r5.source -eq "CACHED") {
    Write-Pass "Amount mismatch handled  http=$($r5.httpCode) source=$($r5.source)"
} else { Write-Fail "Expected 422 or CACHED  got http=$($r5.httpCode) source=$($r5.source)" }

# ==============================================================================
# PHASE 2 -- Routing
# ==============================================================================
Write-Section "PHASE 2" "Routing"

Write-Case "P2-01" "SBI VPA (alice@sbi -> bob@sbi) -> 200 SUCCESS"
$r = Send-Payment "alice@sbi" "bob@sbi" 50000 "route-sbi"
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status) rrn=$($r.bank_rrn)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "SBI routed  rrn=$($r.bank_rrn)" }
else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode) detail=$($r.detail)" }

Write-Case "P2-02" "ICICI VPA -> 200 SUCCESS"
$r = Send-Payment "alice@sbi" "bob@okicici" 25000 "route-icici"
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "ICICI routed" }
else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode) detail=$($r.detail)" }

Write-Case "P2-03" "HDFC VPA -> 200 SUCCESS"
$r = Send-Payment "alice@sbi" "bob@okhdfcbank" 100000 "route-hdfc"
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "HDFC routed" }
else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode) detail=$($r.detail)" }

Write-Case "P2-04" "YesBank VPA -> 200 SUCCESS"
$r = Send-Payment "alice@sbi" "bob@ybl" 15000 "route-yesbank"
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "YesBank routed" }
else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode) detail=$($r.detail)" }

Write-Case "P2-05" "Unknown VPA handle -> 404"
$r = Send-Payment "alice@sbi" "bob@unknownxyz" 10000 "route-unknown"
Write-Host "    [DBG] http=$($r.httpCode) detail=$($r.detail)" -ForegroundColor DarkGray
if ($r.httpCode -eq 404) { Write-Pass "404 unresolvable VPA" }
else { Write-Fail "Expected 404  got http=$($r.httpCode) detail=$($r.detail)" }

# ---- Phase 1+2 spent ~10 requests. Wait for IP window before Phase 3 --------
Wait-RateLimit "clear IP window after Phase 1+2 before validation tests"

# ==============================================================================
# PHASE 3 -- Input Validation
# ==============================================================================
Write-Section "PHASE 3" "Input Validation"

Write-Case "P3-01" "Missing idempotency_key -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -Body @{
    payer_vpa    = "alice@sbi"
    payee_vpa    = "bob@sbi"
    amount_paise = 10000
}
Write-Host "    [DBG] http=$($r.httpCode) detail=$($r.detail)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 missing idempotency_key" }
else { Write-Fail "Expected 422  got $($r.httpCode) detail=$($r.detail)" }

Write-Case "P3-02" "Zero amount_paise -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey (New-IdemKey) -Body @{
    payer_vpa       = "alice@sbi"
    payee_vpa       = "bob@sbi"
    amount_paise    = 0
    idempotency_key = (New-IdemKey)
}
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 zero amount rejected" }
else { Write-Fail "Expected 422  got $($r.httpCode)" }

Write-Case "P3-03" "Negative amount_paise -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey (New-IdemKey) -Body @{
    payer_vpa       = "alice@sbi"
    payee_vpa       = "bob@sbi"
    amount_paise    = -500
    idempotency_key = (New-IdemKey)
}
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 negative amount rejected" }
else { Write-Fail "Expected 422  got $($r.httpCode)" }

Write-Case "P3-04" "Invalid payer VPA format (no @) -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey (New-IdemKey) -Body @{
    payer_vpa       = "notavpa"
    payee_vpa       = "bob@sbi"
    amount_paise    = 10000
    idempotency_key = (New-IdemKey)
}
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 bad payer VPA format" }
else { Write-Fail "Expected 422  got $($r.httpCode)" }

Write-Case "P3-05" "Missing payer_vpa -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey (New-IdemKey) -Body @{
    payee_vpa       = "bob@sbi"
    amount_paise    = 10000
    idempotency_key = (New-IdemKey)
}
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 missing payer_vpa" }
else { Write-Fail "Expected 422  got $($r.httpCode)" }

Write-Case "P3-06" "Empty body -> 422"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST -IdemKey (New-IdemKey) -Body @{}
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 422) { Write-Pass "422 empty body rejected" }
else { Write-Fail "Expected 422  got $($r.httpCode)" }

Write-Case "P3-07" "GET non-existent txn_id -> 404"
$r = Invoke-GW -Path "/api/v1/payments/nonexistent-$global:RUN_ID"
Write-Host "    [DBG] http=$($r.httpCode)" -ForegroundColor DarkGray
if ($r.httpCode -eq 404) { Write-Pass "404 txn not found" }
else { Write-Fail "Expected 404  got $($r.httpCode)" }

Write-Case "P3-08" "GET known txn_id from Phase 1 -> 200 SUCCESS"
if ($iTxnId) {
    $r = Invoke-GW -Path "/api/v1/payments/$iTxnId"
    Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status)" -ForegroundColor DarkGray
    if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "GET txn_id=$iTxnId status=SUCCESS" }
    else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode)" }
} else {
    Write-Host "    [SKIP] No txn_id captured in Phase 1" -ForegroundColor DarkYellow
}

# ---- Phase 3 used ~8 requests. Wait before Circuit Breaker phase -------------
Wait-RateLimit "clear IP window before Circuit Breaker tests"

# ==============================================================================
# PHASE 4 -- Circuit Breaker
# ==============================================================================
Write-Section "PHASE 4" "Circuit Breaker"

if ($SkipSlowTests) {
    Write-Host "  [SKIP] -SkipSlowTests set -- Phase 4 skipped" -ForegroundColor DarkYellow
} else {

    Write-Case "P4-01" "Clean route -> 200 SUCCESS, breaker healthy"
    Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
                 -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

    $r = Send-Payment "alice@sbi" "bob@sbi" 10000 "cb-happy"
    Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status) rrn=$($r.bank_rrn)" -ForegroundColor DarkGray
    if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") { Write-Pass "200 SUCCESS rrn=$($r.bank_rrn)" }
    else { Write-Fail "Expected 200/SUCCESS  got http=$($r.httpCode) detail=$($r.detail)" }

    $b = Get-BreakerState "SBI"
    Write-Host "    [Breaker] state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
    if ($b.fail_count -le 0) { Write-Pass "Breaker healthy fail_count=$($b.fail_count)" }
    else { Write-Fail "Unexpected fail_count=$($b.fail_count)" }

    Write-Case "P4-02" "Both endpoints fail -> 502 Both primary and fallback failed (fail_count=2)"
    Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn/fail" `
                 -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fail/fallback"

    $r = Send-Payment "alice@sbi" "bob@sbi" 10000 "cb-trip-A"
    Write-Host "    [DBG] http=$($r.httpCode) detail=$($r.detail)" -ForegroundColor DarkGray
    if ($r.httpCode -eq 502 -and $r.detail -like "*Both primary and fallback failed*") {
        Write-Pass "502 Both primary and fallback failed"
    } else { Write-Fail "Expected 502/Both failed  got http=$($r.httpCode) detail=$($r.detail)" }

    $b = Get-BreakerState "SBI"
    Write-Host "    [Breaker] after trip-A: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
    if ($b.fail_count -eq 2) { Write-Pass "fail_count=2 as expected" }
    else { Write-Fail "Expected fail_count=2  got $($b.fail_count)" }

    Write-Case "P4-03" "Third failure trips breaker -> 502 Circuit breaker open for SBI"
    $r = Send-Payment "alice@sbi" "bob@sbi" 10000 "cb-trip-B"
    Write-Host "    [DBG] http=$($r.httpCode) detail=$($r.detail)" -ForegroundColor DarkGray
    if ($r.httpCode -eq 502 -and $r.detail -like "*Circuit breaker open for*") {
        Write-Pass "502 Circuit breaker open for SBI -- tripped"
    } else { Write-Fail "Expected 502/Circuit breaker open  got http=$($r.httpCode) detail=$($r.detail)" }

    $b = Get-BreakerState "SBI"
    Write-Host "    [Breaker] after trip-B: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
    if ($b.state -eq "open") { Write-Pass "Breaker state=OPEN confirmed" }
    else { Write-Fail "Expected OPEN  got state=$($b.state)" }

    Write-Case "P4-04" "Open breaker short-circuits 3 requests (each < 500 ms)"
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    for ($i = 1; $i -le 3; $i++) {
        $sw.Restart()
        $r = Send-Payment "alice@sbi" "bob@sbi" 10000 "cb-open-$i"
        $sw.Stop(); $ms = $sw.ElapsedMilliseconds
        Write-Host "    [DBG] req-$i http=$($r.httpCode) detail=$($r.detail) elapsed=${ms}ms" -ForegroundColor DarkGray
        if ($r.httpCode -eq 502 -and $r.detail -like "*Circuit breaker open*") {
            Write-Pass "req-$i  502 short-circuit elapsed=${ms}ms"
        } else { Write-Fail "req-$i  expected 502/open  got http=$($r.httpCode) detail=$($r.detail)" }
        if ($ms -gt 500) { Write-Fail "req-$i  elapsed=${ms}ms > 500ms -- not short-circuiting" }
    }

    Write-Case "P4-05" "Restore good route then sleep ${RESET_SECS}s"
    Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
                 -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"
    Write-Host "    Sleeping $RESET_SECS s for breaker reset timeout..." -ForegroundColor DarkGray
    Start-Sleep -Seconds $RESET_SECS

    $b = Get-BreakerState "SBI"
    Write-Host "    [Breaker] post-sleep: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray

    Write-Case "P4-06" "Half-open probe -> 200 SUCCESS, breaker closes"
    $r = Send-Payment "alice@sbi" "bob@sbi" 10000 "cb-probe"
    Write-Host "    [DBG] probe http=$($r.httpCode) status=$($r.status) detail=$($r.detail)" -ForegroundColor DarkGray
    if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") {
        Write-Pass "Probe 200 SUCCESS -- breaker recovered"
    } elseif ($r.detail -like "*Circuit breaker open*") {
        Write-Fail "Breaker still OPEN after ${RESET_SECS}s -- check BREAKER_RESET_TIMEOUT on bank-adapter"
    } else { Write-Fail "Unexpected  http=$($r.httpCode) detail=$($r.detail)" }

    $b = Get-BreakerState "SBI"
    Write-Host "    [Breaker] final cb: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
    if ($b.state -eq "closed") { Write-Pass "Breaker CLOSED after probe" }
    else { Write-Fail "Breaker state=$($b.state) expected closed" }
}

# ==============================================================================
# PHASE 5 -- Rate Limiting
# NOTE: Rate limit window = 60 s (Retry-After=60).
#       We deliberately exhaust the window here to test 429 behaviour,
#       then wait $RL_WINDOW seconds before the recovery assertion.
# ==============================================================================
Write-Section "PHASE 5" "Rate Limiting"

Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
             -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

# Start with a clean window so P5-01 shows the transition 200->429
Wait-RateLimit "ensure clean window before burst test"

Write-Case "P5-01" "Burst 30 requests -- expect some 200s then 429s"
Write-Host "    Firing 30 requests back-to-back..." -ForegroundColor DarkGray

$codes    = @()
$first429 = $null

for ($i = 1; $i -le 30; $i++) {
    $r = Send-Payment "alice@sbi" "bob@sbi" 100 "rl-burst-$i"
    $codes += $r.httpCode
    if ($r.httpCode -eq 429 -and $null -eq $first429) { $first429 = $i }
    Write-Host ("    [{0,2}] HTTP={1}  detail={2}" -f $i, $r.httpCode, $r.detail) -ForegroundColor DarkGray
}

$c200 = ($codes | Where-Object { $_ -eq 200 }).Count
$c429 = ($codes | Where-Object { $_ -eq 429 }).Count

Write-Host ""
Write-Host "    Summary: 200=$c200  429=$c429  first-429=req#$first429" -ForegroundColor DarkGray

if ($c200 -gt 0) { Write-Pass "At least one request succeeded before limit (count=$c200)" }
else             { Write-Fail "No 200 received -- rate limit may have been pre-exhausted" }

if ($c429 -gt 0) { Write-Pass "429 received under burst (count=$c429/30, first at req#$first429)" }
else {
    Write-Host "    [INFO] No 429 -- check RATE_LIMIT_REQUESTS env var on api-gateway" -ForegroundColor Yellow
    Write-Fail "429 never triggered in 30-request burst"
}

Write-Case "P5-02" "429 response carries Retry-After header"
$retryChecked = $false
for ($i = 1; $i -le 10; $i++) {
    $r = Send-Payment "alice@sbi" "bob@sbi" 100 "rl-hdr-$i"
    if ($r.httpCode -eq 429) {
        $ra = $r.headers["retry-after"]
        Write-Host "    [DBG] 429 at req-$i  Retry-After=$ra" -ForegroundColor DarkGray
        if ($ra) { Write-Pass "Retry-After header present  value=$ra" }
        else {
            Write-Host "    [DBG] Headers: $($r.headers.Keys -join ', ')" -ForegroundColor DarkGray
            Write-Fail "429 received but Retry-After header missing"
        }
        $retryChecked = $true
        break
    }
}
if (-not $retryChecked) {
    Write-Host "    [SKIP] No 429 to check Retry-After against" -ForegroundColor DarkYellow
}

Write-Case "P5-03" "Rate limit window resets -- single request succeeds after ${RL_WINDOW}s"
Write-Host "    Waiting $RL_WINDOW s for IP window reset (Retry-After=60)..." -ForegroundColor DarkGray
Start-Sleep -Seconds $RL_WINDOW

$r = Send-Payment "alice@sbi" "bob@sbi" 100 "rl-recovery"
Write-Host "    [DBG] http=$($r.httpCode) status=$($r.status)" -ForegroundColor DarkGray
if ($r.httpCode -eq 200 -and $r.status -eq "SUCCESS") {
    Write-Pass "200 SUCCESS after rate-limit window reset"
} elseif ($r.httpCode -eq 429) {
    Write-Fail "Still 429 after ${RL_WINDOW}s -- window may be longer than expected"
} else { Write-Fail "Unexpected  http=$($r.httpCode) detail=$($r.detail)" }

Write-Case "P5-04" "Second API key has independent quota"
$r = Invoke-GW -Path "/api/v1/payments" -Method POST `
     -SkipApiKey `
     -ExtraHeader "x-api-key: ibts-api-key-dev-2" `
     -IdemKey "rl-key2-$global:RUN_ID" `
     -Body @{
         payer_vpa       = "alice@sbi"
         payee_vpa       = "bob@sbi"
         amount_paise    = 100
         idempotency_key = "rl-key2-$global:RUN_ID"
         remarks         = "rl-second-key"
     }
Write-Host "    [DBG] http=$($r.httpCode)  (200=own quota  401/403=key not provisioned -- both acceptable)" -ForegroundColor DarkGray
if ($r.httpCode -in @(200, 401, 403)) { Write-Pass "Second-key behaviour correct  http=$($r.httpCode)" }
else { Write-Fail "Unexpected  http=$($r.httpCode) detail=$($r.detail)" }

# ==============================================================================
# TEARDOWN
# ==============================================================================
Write-Section "TEARDOWN" "Restore state"

Set-SBIRoute -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
             -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

Reset-Breaker "SBI"

$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] final: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
if ($b.state -eq "closed") { Write-Pass "Breaker restored to CLOSED" }
else { Write-Fail "Breaker still in state=$($b.state)" }

# ==============================================================================
# RESULTS
# ==============================================================================
$total = $global:PASS + $global:FAIL
$color = if ($global:FAIL -eq 0) { "Green" } else { "Yellow" }

Write-Host ""
Write-Host "====================================================" -ForegroundColor White
Write-Host ("  RUN ID : {0}"     -f $global:RUN_ID)               -ForegroundColor DarkGray
Write-Host ("  PASSED : {0}/{1}" -f $global:PASS, $total)         -ForegroundColor $color
if ($global:FAIL -gt 0) {
    Write-Host ("  FAILED : {0}/{1} -- review [FAIL] lines above" -f $global:FAIL, $total) -ForegroundColor Red
} else {
    Write-Host "  All tests passed -- API Gateway healthy end-to-end" -ForegroundColor Green
}
Write-Host "====================================================" -ForegroundColor White
Write-Host ""

if ($global:FAIL -gt 0) { exit 1 }
