# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: api-gateway/tests/test-circuit-breaker.ps1
#
# Real API response shapes (confirmed by diagnostic):
#   200  {"txn_id":"...","status":"SUCCESS","bank_rrn":"...","message":"SUCCESS","source":"NEW"}
#   502  {"detail":"Both primary and fallback failed"}        <- both endpoints 503
#   502  {"detail":"Circuit breaker open for for SBI"}         <- trip call (fail_count hits max)
#   502  {"detail":"Circuit breaker open for SBI"}            <- breaker already OPEN
#
# Breaker state endpoint: GET http://localhost:8082/api/v1/adapter/debug/breakers
#   {"SBI":{"state":"open"|"closed","fail_count":<n>}}
# Fail threshold = 3 (primary 503 = +1, fallback 503 = +2, next primary 503 = +3 -> OPEN)
# Reset:           POST http://localhost:8082/api/v1/adapter/debug/breakers/SBI/reset

$ErrorActionPreference = "Continue"

$BASE_URL    = "http://localhost:8084"
$AWS_EP      = "http://localhost:4566"
$REGION      = "ap-south-1"
$API_KEY     = "ibts-api-key-dev"
$ROUTING_TBL = "routing-table"
$RESET_SECS  = 32

$global:PASS = 0
$global:FAIL = 0

function Write-Pass([string]$msg)    { Write-Host "  [PASS] $msg" -ForegroundColor Green; $global:PASS++ }
function Write-Fail([string]$msg)    { Write-Host "  [FAIL] $msg" -ForegroundColor Red;   $global:FAIL++ }
function Write-Section([string]$msg) { Write-Host ""; Write-Host "=== $msg ===" -ForegroundColor Cyan }
function New-IdemKey                 { "ibts-cb-$(New-Guid)" }

# ------------------------------------------------------------------------------
# Send-SBIPayment
#   Uses curl.exe + temp file to avoid all PowerShell/Windows shell-escaping
#   issues that cause 422s when building JSON inline.
#   Returns a normalized hashtable:
#     httpCode  : int
#     status    : "SUCCESS" | "FAILED"
#     detail    : string (from {"detail":"..."} on 502)
#     txn_id    : string
#     bank_rrn  : string
# ------------------------------------------------------------------------------
function Send-SBIPayment([string]$Label) {
    $k        = New-IdemKey
    $bodyFile = [System.IO.Path]::GetTempFileName() + ".json"

    $bodyObj = [ordered]@{
        payer_vpa       = "alice@sbi"
        payee_vpa       = "bob@sbi"
        amount_paise    = 10000
        idempotency_key = $k
        remarks         = $Label
    }
    [System.IO.File]::WriteAllText(
        $bodyFile,
        ($bodyObj | ConvertTo-Json),
        [System.Text.UTF8Encoding]::new($false)   # BOM-free for curl
    )

    $raw = curl.exe -s -X POST "$BASE_URL/api/v1/payments" `
           -H "x-api-key: $API_KEY" `
           -H "Content-Type: application/json" `
           -H "x-idempotency-key: $k" `
           -d "@$bodyFile" `
           -w "`nHTTP_CODE:%{http_code}"

    Remove-Item $bodyFile -Force

    # Separate body lines from the HTTP_CODE trailer line
    $lines    = $raw -split "`n"
    $codeLine = $lines | Where-Object { $_ -match '^HTTP_CODE:' } | Select-Object -Last 1
    $body     = ($lines | Where-Object { $_ -notmatch '^HTTP_CODE:' }) -join "" | ForEach-Object { $_.Trim() }
    $httpCode = [int]($codeLine -replace 'HTTP_CODE:', '')

    $obj = $body | ConvertFrom-Json -ErrorAction SilentlyContinue

    # Normalize into a single consistent shape regardless of HTTP code
    [ordered]@{
        httpCode = $httpCode
        status   = if ($httpCode -eq 200) { "SUCCESS" } else { "FAILED" }
        detail   = if ($null -ne $obj) { "$($obj.detail)" } else { "" }
        txn_id   = if ($null -ne $obj -and $null -ne $obj.txn_id)  { "$($obj.txn_id)"  } else { "" }
        bank_rrn = if ($null -ne $obj -and $null -ne $obj.bank_rrn){ "$($obj.bank_rrn)" } else { "" }
        message  = if ($null -ne $obj -and $null -ne $obj.message)  { "$($obj.message)"  } else { "" }
        rawBody  = $body
    }
}

# ------------------------------------------------------------------------------
# Set-SBIRoute  — writes DynamoDB row and evicts Redis cache key
# ------------------------------------------------------------------------------
function Set-SBIRoute([string]$Primary, [string]$Fallback) {
    Write-Host "  [Route] SBI primary=$Primary" -ForegroundColor DarkGray

    $ts      = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
    $tmpFile = [System.IO.Path]::GetTempFileName()
    $item = @{
        bankCode         = @{ S    = "SBI"                 }
        bankName         = @{ S    = "State Bank of India" }
        primaryEndpoint  = @{ S    = $Primary              }
        fallbackEndpoint = @{ S    = $Fallback             }
        active           = @{ BOOL = $true                 }
        updatedAt        = @{ N    = "$ts"                 }
    } | ConvertTo-Json -Depth 5

    [System.IO.File]::WriteAllText($tmpFile, $item, [System.Text.UTF8Encoding]::new($false))
    $result = aws --endpoint-url $AWS_EP dynamodb put-item `
        --region $REGION --table-name $ROUTING_TBL `
        --item "file://$tmpFile" 2>&1
    Remove-Item $tmpFile -Force

    if ($LASTEXITCODE -ne 0) {
        Write-Host "  [ERR] DynamoDB put-item failed (exit $LASTEXITCODE): $result" -ForegroundColor DarkRed
    } else {
        Write-Host "  [OK]  DynamoDB updated" -ForegroundColor DarkGray
    }

    docker exec ibts-redis redis-cli DEL "route:SBI" | Out-Null
    Write-Host "  [OK]  route:SBI Redis key evicted" -ForegroundColor DarkGray
    Start-Sleep -Milliseconds 400
}

# ------------------------------------------------------------------------------
# Get-BreakerState  — reads live breaker state from bank-adapter debug endpoint
# ------------------------------------------------------------------------------
function Get-BreakerState([string]$BankCode) {
    $py   = "import urllib.request; print(urllib.request.urlopen('http://localhost:8082/api/v1/adapter/debug/breakers').read().decode())"
    $json = docker exec bank-adapter python3 -c $py 2>$null
    if ([string]::IsNullOrWhiteSpace($json)) {
        return @{ state = "unknown"; fail_count = -1 }
    }
    $all   = $json | ConvertFrom-Json -ErrorAction SilentlyContinue
    $entry = $all.PSObject.Properties[$BankCode.ToUpper()]
    if ($null -eq $entry) { return @{ state = "closed"; fail_count = 0 } }
    @{
        state      = "$($entry.Value.state)"
        fail_count = [int]"$($entry.Value.fail_count)"
    }
}

# ------------------------------------------------------------------------------
# Reset-Breaker
# ------------------------------------------------------------------------------
function Reset-Breaker([string]$BankCode) {
    $py = "import urllib.request; urllib.request.urlopen(urllib.request.Request('http://localhost:8082/api/v1/adapter/debug/breakers/$BankCode/reset',data=b'',method='POST'))"
    docker exec bank-adapter python3 -c $py 2>$null | Out-Null
    Write-Host "  [OK]  Breaker $BankCode reset to CLOSED" -ForegroundColor DarkGray
}

# ==============================================================================
# PHASE 1 - SBI happy path (200 SUCCESS)
# ==============================================================================
Write-Section "Phase 1 - SBI Happy Path"

Set-SBIRoute `
    -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
    -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

$p1 = Send-SBIPayment "phase1-ok"
Write-Host "  [DBG] http=$($p1.httpCode) status=$($p1.status) rrn=$($p1.bank_rrn)" -ForegroundColor DarkGray

if ($p1.httpCode -eq 200 -and $p1.status -eq "SUCCESS") {
    Write-Pass "Phase 1 - HTTP=200 status=SUCCESS rrn=$($p1.bank_rrn)"
} else {
    Write-Fail "Phase 1 - expected HTTP 200/SUCCESS got http=$($p1.httpCode) detail=$($p1.detail) body=$($p1.rawBody)"
}

$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
if ($b.fail_count -le 0) {
    Write-Pass "Phase 1 - breaker healthy (fail_count=$($b.fail_count))"
} else {
    Write-Fail "Phase 1 - unexpected fail_count=$($b.fail_count)"
}

# ==============================================================================
# PHASE 2 - Trip the breaker
#   fail-1: primary 503 (+1) + fallback 503 (+2) -> "Both primary and fallback failed"
#   fail-2: primary 503 (+3) -> BREAKER TRIPS    -> "Circuit breaker open for for SBI"
# ==============================================================================
Write-Section "Phase 2 - Trip Circuit Breaker"

Set-SBIRoute `
    -Primary  "http://mock-bank-server:8080/mock/sbi/txn/fail" `
    -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fail/fallback"

$p2a = Send-SBIPayment "phase2-trip-A"
Write-Host "  [DBG] 2-A http=$($p2a.httpCode) detail=$($p2a.detail)" -ForegroundColor DarkGray

if ($p2a.httpCode -eq 502 -and $p2a.detail -like "*Both primary and fallback failed*") {
    Write-Pass "Phase 2-A - HTTP=502 detail='$($p2a.detail)' (fail_count should be 2)"
} else {
    Write-Fail "Phase 2-A - expected 502/'Both primary and fallback failed' got http=$($p2a.httpCode) detail=$($p2a.detail)"
}

$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] after 2-A: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
if ($b.fail_count -eq 2) {
    Write-Pass "Phase 2-A - fail_count=2 as expected"
} else {
    Write-Fail "Phase 2-A - expected fail_count=2 got $($b.fail_count)"
}

$p2b = Send-SBIPayment "phase2-trip-B"
Write-Host "  [DBG] 2-B http=$($p2b.httpCode) detail=$($p2b.detail)" -ForegroundColor DarkGray

if ($p2b.httpCode -eq 502 -and $p2b.detail -like "*Circuit breaker open for*") {
    Write-Pass "Phase 2-B - HTTP=502 detail='$($p2b.detail)' (breaker tripped)"
} else {
    Write-Fail "Phase 2-B - expected 502/'Circuit breaker open for' got http=$($p2b.httpCode) detail=$($p2b.detail)"
}

$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] after 2-B: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray
if ($b.state -eq "open") {
    Write-Pass "Phase 2 - breaker is OPEN"
} else {
    Write-Fail "Phase 2 - expected breaker OPEN got state=$($b.state)"
}

# ==============================================================================
# PHASE 3 - Breaker OPEN: all calls short-circuit
#   Expected: HTTP 502, detail = "Circuit breaker open for SBI"
# ==============================================================================
Write-Section "Phase 3 - Breaker OPEN Short-Circuits"

$sw = [System.Diagnostics.Stopwatch]::StartNew()
for ($i = 1; $i -le 3; $i++) {
    $sw.Restart()
    $p3 = Send-SBIPayment "phase3-open-$i"
    $sw.Stop()
    $ms = $sw.ElapsedMilliseconds
    Write-Host "  [DBG] req-$i http=$($p3.httpCode) detail=$($p3.detail) elapsed=${ms}ms" -ForegroundColor DarkGray

    if ($p3.httpCode -eq 502 -and $p3.detail -like "*Circuit breaker open*") {
        Write-Pass "Phase 3 req-$i - HTTP=502 detail='$($p3.detail)' elapsed=${ms}ms"
        if ($ms -gt 500) {
            Write-Fail "Phase 3 req-$i - elapsed=${ms}ms is too high; breaker may not be short-circuiting"
        }
    } else {
        Write-Fail "Phase 3 req-$i - expected 502/'Circuit breaker open' got http=$($p3.httpCode) detail=$($p3.detail)"
    }
}

# ==============================================================================
# PHASE 4 - Half-open recovery after reset_timeout
#   Requires BREAKER_RESET_TIMEOUT <= $RESET_SECS in bank-adapter env.
#   Restore SUCCESS route BEFORE sleep so the probe hits the working endpoint.
# ==============================================================================
Write-Section "Phase 4 - Half-Open Recovery (sleeping $RESET_SECS s)"

Set-SBIRoute `
    -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
    -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

# BREAKER_RESET_TIMEOUT = 30s (confirmed via `docker exec bank-adapter sh -c "env | grep RESET"`)
Write-Host "  Sleeping $RESET_SECS s..." -ForegroundColor DarkGray
    Start-Sleep -Seconds $RESET_SECS

$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] post-sleep: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray

$p4 = Send-SBIPayment "phase4-probe"
Write-Host "  [DBG] probe http=$($p4.httpCode) status=$($p4.status) detail=$($p4.detail)" -ForegroundColor DarkGray

if ($p4.httpCode -eq 200 -and $p4.status -eq "SUCCESS") {
    Write-Pass "Phase 4 - probe HTTP=200 SUCCESS, breaker recovered"
} elseif ($p4.detail -like "*Circuit breaker open*") {
    Write-Fail "Phase 4 - breaker still OPEN after ${RESET_SECS}s; check BREAKER_RESET_TIMEOUT env var on bank-adapter"
} else {
    Write-Fail "Phase 4 - unexpected http=$($p4.httpCode) detail=$($p4.detail) body=$($p4.rawBody)"
}

$b = Get-BreakerState "SBI"
if ($b.state -eq "closed") {
    Write-Pass "Phase 4 - breaker CLOSED after successful probe"
} else {
    Write-Fail "Phase 4 - breaker state=$($b.state) (expected closed)"
}

# ==============================================================================
# TEARDOWN
# ==============================================================================
Write-Section "Teardown"

Set-SBIRoute `
    -Primary  "http://mock-bank-server:8080/mock/sbi/txn" `
    -Fallback "http://mock-bank-server:8080/mock/sbi/txn/fallback"

Reset-Breaker "SBI"
$b = Get-BreakerState "SBI"
Write-Host "  [Breaker] final: state=$($b.state) fail_count=$($b.fail_count)" -ForegroundColor DarkGray

Write-Host ""
Write-Host "========================================" -ForegroundColor White
$color = if ($global:FAIL -eq 0) { "Green" } else { "Yellow" }
Write-Host "  Circuit Breaker:  $global:PASS passed   $global:FAIL failed" -ForegroundColor $color
Write-Host "========================================" -ForegroundColor White
Write-Host ""
if ($global:FAIL -gt 0) { exit 1 }
