# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: tests/test-api-gateway.ps1

$GATEWAY   = "http://localhost:8084"
$API_KEY   = "ibts-api-key-dev"
$HEADERS   = @{ "X-API-Key" = $API_KEY; "Content-Type" = "application/json" }
$PASS = 0; $FAIL = 0

function Check($label, $cond) {
    if ($cond) { Write-Host "  [PASS] $label" -ForegroundColor Green; $script:PASS++ }
    else        { Write-Host "  [FAIL] $label" -ForegroundColor Red;   $script:FAIL++ }
}

# ── T01 Health (no auth needed) ───────────────────────────────────────────────
Write-Host "`n[T01] Gateway health check"
$r = Invoke-RestMethod "$GATEWAY/actuator/health" -Method GET
Check "status=UP" ($r.status -eq "UP")

# ── T02 No auth → 401 ────────────────────────────────────────────────────────
Write-Host "`n[T02] Missing auth → 401"
try {
    Invoke-RestMethod "$GATEWAY/api/v1/payments" -Method POST -ContentType "application/json" `
        -Body '{"debit_vpa":"a@sbi","credit_vpa":"b@hdfc","amount":100,"idempotency_key":"gw-t02"}' | Out-Null
    Check "should have 401" $false
} catch { Check "401 no-auth rejected" ($_.Exception.Response.StatusCode.value__ -eq 401) }

# ── T03 Bad API key → 401 ────────────────────────────────────────────────────
Write-Host "`n[T03] Wrong API key → 401"
try {
    Invoke-RestMethod "$GATEWAY/api/v1/payments" -Method POST `
        -Headers @{ "X-API-Key"="wrong"; "Content-Type"="application/json" } `
        -Body '{"debit_vpa":"a@sbi","credit_vpa":"b@hdfc","amount":100,"idempotency_key":"gw-t03"}' | Out-Null
    Check "should have 401" $false
} catch { Check "401 bad-key rejected" ($_.Exception.Response.StatusCode.value__ -eq 401) }

# ── T04 Valid payment proxied → SUCCESS ───────────────────────────────────────
Write-Host "`n[T04] Valid payment → proxied to payment-switch → SUCCESS"
$body = @{
    debit_vpa      = "john@sbi"
    credit_vpa     = "merchant@okhdfcbank"
    amount         = 500
    idempotency_key = "gw-t04-$(Get-Random)"
} | ConvertTo-Json
$r = Invoke-RestMethod "$GATEWAY/api/v1/payments" -Method POST -Headers $HEADERS -Body $body
Check "SUCCESS status" ($r.status -eq "SUCCESS")
Check "txn_id present"  ($r.txn_id -ne $null)
$TXN_ID = $r.txn_id
Write-Host "    txn_id=$TXN_ID"

# ── T05 GET payment by txn_id ─────────────────────────────────────────────────
Write-Host "`n[T05] GET /api/v1/payments/{txn_id} → proxied"
$r = Invoke-RestMethod "$GATEWAY/api/v1/payments/$TXN_ID" -Method GET -Headers $HEADERS
Check "DB record status=SUCCESS" ($r.status -eq "SUCCESS")

# ── T06 X-Request-ID echoed back ──────────────────────────────────────────────
Write-Host "`n[T06] X-Request-ID header round-trip"
$REQ_ID = "test-req-$(Get-Random)"
$resp = Invoke-WebRequest "$GATEWAY/actuator/health" -Method GET `
    -Headers @{ "X-Request-ID" = $REQ_ID }
Check "X-Request-ID echoed" ($resp.Headers["X-Request-ID"] -eq $REQ_ID)

# ── T07 X-Latency-Ms header present ───────────────────────────────────────────
Write-Host "`n[T07] X-Latency-Ms header present"
$resp = Invoke-WebRequest "$GATEWAY/actuator/health" -Method GET -Headers $HEADERS
Check "latency header set" ($resp.Headers["X-Latency-Ms"] -ne $null)

# ── T08 Zero amount → 422 (gateway proxies, switch validates) ────────────────
Write-Host "`n[T08] Zero amount → 422 from payment-switch via gateway"
try {
    Invoke-RestMethod "$GATEWAY/api/v1/payments" -Method POST -Headers $HEADERS `
        -Body '{"debit_vpa":"a@sbi","credit_vpa":"b@hdfc","amount":0,"idempotency_key":"gw-t08"}' | Out-Null
    Check "should have 422" $false
} catch { Check "422 proxied correctly" ($_.Exception.Response.StatusCode.value__ -eq 422) }

# ── T09 Unknown VPA → 404 via gateway ────────────────────────────────────────
Write-Host "`n[T09] Unknown VPA → 404 proxied"
try {
    Invoke-RestMethod "$GATEWAY/api/v1/payments" -Method POST -Headers $HEADERS `
        -Body "{`"debit_vpa`":`"a@sbi`",`"credit_vpa`":`"ghost@unknown`",`"amount`":100,`"idempotency_key`":`"gw-t09-$(Get-Random)`"}" | Out-Null
    Check "should have 404" $false
} catch { Check "404 proxied correctly" ($_.Exception.Response.StatusCode.value__ -eq 404) }

# ── Results ───────────────────────────────────────────────────────────────────
Write-Host "`n======================================"
Write-Host " RESULTS: $PASS/$($PASS+$FAIL) passed"
if ($FAIL -eq 0) { Write-Host " All tests passed — api-gateway healthy" -ForegroundColor Green }
else             { Write-Host " $FAIL test(s) FAILED" -ForegroundColor Red }
Write-Host "======================================"
