# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
set -e

echo ">>> Creating IdempotencyRecords table..."

awslocal dynamodb create-table \
    --table-name IdempotencyRecords \
    --attribute-definitions AttributeName=idempotencyKey,AttributeType=S \
    --key-schema AttributeName=idempotencyKey,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region ap-south-1

echo ">>> Enabling TTL on IdempotencyRecords..."

awslocal dynamodb update-time-to-live \
    --table-name IdempotencyRecords \
    --time-to-live-specification Enabled=true,AttributeName=expiresAt \
    --region ap-south-1

echo ">>> All tables ready."
