# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/routers/adapter_router.py

from fastapi import APIRouter, Depends
from app.models import AdapterRequest, AdapterResponse
from app.services.adapter_service import AdapterService

router = APIRouter(prefix="/api/v1/adapter", tags=["adapter"])

def get_service() -> AdapterService:
    return AdapterService()

@router.post("/send", response_model=AdapterResponse)
async def send(req: AdapterRequest,
               service: AdapterService = Depends(get_service)):
    return await service.send(req)
