# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/routers/debug_router.py

from fastapi import APIRouter
from app.circuit_breaker.breaker_registry import all_breaker_states, reset_breaker

router = APIRouter(prefix="/api/v1/adapter/debug", tags=["debug"])


@router.get("/breakers")
def get_breaker_states():
    """Return state + fail counter for every bank breaker in memory."""
    return all_breaker_states()


@router.post("/breakers/{bank_code}/reset", status_code=204)
def reset_bank_breaker(bank_code: str):
    """Recreate breaker in CLOSED state — test teardown only, never expose in prod."""
    reset_breaker(bank_code)
