# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/auth.py

import logging
from fastapi import Request, HTTPException, status
from fastapi.security.utils import get_authorization_scheme_param
import jwt

from app.config import settings

log = logging.getLogger("api-gateway.auth")

CREDENTIALS_EXCEPTION = HTTPException(
    status_code=status.HTTP_401_UNAUTHORIZED,
    detail="Invalid or missing credentials",
    headers={"WWW-Authenticate": "Bearer"},
)


def _verify_jwt(token: str) -> dict:
    try:
        return jwt.decode(token, settings.JWT_SECRET, algorithms=[settings.JWT_ALGORITHM])
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="Token expired")
    except jwt.InvalidTokenError:
        raise CREDENTIALS_EXCEPTION


async def verify_auth(request: Request) -> dict:
    """
    Accepts either:
      - Authorization: Bearer <jwt>
      - X-API-Key: <api_key>   (dev/service-to-service convenience)
    """
    # 1. Try API key first (fast path for internal services)
    api_key = request.headers.get("X-API-Key")
    if api_key:
        if api_key == settings.API_KEY:
            log.debug("auth=api_key ip=%s", request.client.host)
            return {"sub": "api-key-client", "auth_method": "api_key"}
        raise HTTPException(status_code=401, detail="Invalid API key")

    # 2. Try JWT Bearer
    auth_header = request.headers.get("Authorization", "")
    scheme, token = get_authorization_scheme_param(auth_header)
    if not auth_header or scheme.lower() != "bearer":
        raise CREDENTIALS_EXCEPTION

    claims = _verify_jwt(token)
    log.debug("auth=jwt sub=%s ip=%s", claims.get("sub"), request.client.host)
    return claims
