# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: api-gateway/app/main.py

import json
import logging
import time
import uuid
from contextlib import asynccontextmanager

import httpx
import redis.asyncio as aioredis
from fastapi import Depends, FastAPI, HTTPException, Request, Response
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
from prometheus_client import make_asgi_app
from starlette.routing import Mount

from app.auth import verify_auth
from app.config import settings
from app.proxy import proxy_request
from app.rate_limiter import RateLimiter
from shared.metrics.middleware import MetricsMiddleware
from shared.metrics.redis_tracker import TrackedRedis
from shared.telemetry import setup_telemetry


setup_telemetry()
HTTPXClientInstrumentor().instrument()


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
)

log = logging.getLogger("api-gateway")


_redis: TrackedRedis | None = None
_limiter: RateLimiter | None = None
_http: httpx.AsyncClient | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _redis, _limiter, _http

    _raw = aioredis.from_url(
        f"redis://{settings.REDIS_HOST}:{settings.REDIS_PORT}",
        decode_responses=True,
    )
    _redis = TrackedRedis(_raw, service="api-gateway")

    _limiter = RateLimiter(_redis)

    _http = httpx.AsyncClient(
        base_url=settings.PAYMENT_SWITCH_URL,
        timeout=settings.UPSTREAM_TIMEOUT,
    )

    log.info(
        "api-gateway UP upstream=%s env=%s",
        settings.PAYMENT_SWITCH_URL,
        settings.ENV,
    )

    yield

    if _redis is not None:
        await _redis._r.aclose()

    if _http is not None:
        await _http.aclose()

    log.info("api-gateway DOWN")


app = FastAPI(
    title="IBTS API Gateway",
    version="1.0.0",
    lifespan=lifespan,
    routes=[
        Mount("/metrics", make_asgi_app()),
    ],
)

FastAPIInstrumentor.instrument_app(app)

app.add_middleware(
    MetricsMiddleware,
    service_name="api-gateway",
)


@app.middleware("http")
async def access_log(request: Request, call_next):
    request.state.request_id = request.headers.get(
        "X-Request-ID",
        str(uuid.uuid4()),
    )

    start_time = time.perf_counter()
    response: Response = await call_next(request)
    latency_ms = round((time.perf_counter() - start_time) * 1000, 1)

    client_host = (
        request.client.host
        if request.client is not None
        else "unknown"
    )

    log.info(
        "method=%s path=%s status=%s latency_ms=%s req_id=%s ip=%s",
        request.method,
        request.url.path,
        response.status_code,
        latency_ms,
        request.state.request_id,
        client_host,
    )

    response.headers["X-Request-ID"] = request.state.request_id
    response.headers["X-Latency-Ms"] = str(latency_ms)

    return response


@app.get("/actuator/health", tags=["ops"])
async def health():
    return {
        "status": "UP",
        "service": "api-gateway",
    }


@app.post("/api/v1/payments", tags=["payments"])
async def create_payment(
    request: Request,
    claims: dict = Depends(verify_auth),
):
    await _enforce_ip_limit(request)

    try:
        body_json = json.loads(await request.body())
        vpa = body_json.get("payer_vpa", "")

        if vpa and _limiter is not None:
            allowed, _ = await _limiter.check_vpa(vpa)

            if not allowed:
                raise HTTPException(
                    status_code=429,
                    detail=f"Rate limit exceeded for VPA {vpa}",
                )

    except (ValueError, TypeError):
        pass

    return await proxy_request(
        _http,
        request,
        "/api/v1/payments/initiate",
    )


@app.get("/api/v1/payments/{txn_id}", tags=["payments"])
async def get_payment(
    txn_id: str,
    request: Request,
    claims: dict = Depends(verify_auth),
):
    await _enforce_ip_limit(request)

    return await proxy_request(
        _http,
        request,
        f"/api/v1/payments/{txn_id}",
    )


async def _enforce_ip_limit(request: Request):
    if _limiter is None:
        raise HTTPException(
            status_code=503,
            detail="Rate limiter is not initialized",
        )

    client_host = (
        request.client.host
        if request.client is not None
        else "unknown"
    )

    allowed, _ = await _limiter.check_ip(client_host)

    if not allowed:
        raise HTTPException(
            status_code=429,
            detail="IP rate limit exceeded",
            headers={
                "Retry-After": str(settings.RL_WINDOW_SECONDS),
            },
        )
