# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: app/proxy.py

import logging
from fastapi import Request, HTTPException
from fastapi.responses import Response
import httpx

log = logging.getLogger("api-gateway.proxy")

# Headers that must not be forwarded upstream
_HOP_BY_HOP = {
    "host", "connection", "keep-alive", "proxy-authenticate",
    "proxy-authorization", "te", "trailers", "transfer-encoding", "upgrade",
}


def _forward_headers(request: Request) -> dict:
    return {
        k: v for k, v in request.headers.items()
        if k.lower() not in _HOP_BY_HOP
    }


async def proxy_request(
    client: httpx.AsyncClient,
    request: Request,
    upstream_path: str,
) -> Response:
    headers = _forward_headers(request)
    headers["X-Forwarded-For"] = request.client.host
    headers["X-Request-ID"] = request.headers.get(
        "X-Request-ID", request.state.request_id
    )

    body = await request.body()   # Starlette caches — safe to call multiple times

    try:
        upstream_resp = await client.request(
            method=request.method,
            url=upstream_path,
            headers=headers,
            content=body,
            params=request.query_params,
        )
    except httpx.TimeoutException:
        log.error("upstream_timeout path=%s", upstream_path)
        raise HTTPException(status_code=504, detail="Upstream timeout")
    except httpx.ConnectError:
        log.error("upstream_unreachable path=%s", upstream_path)
        raise HTTPException(status_code=502, detail="Upstream unreachable")

    # Strip hop-by-hop from response too
    resp_headers = {
        k: v for k, v in upstream_resp.headers.items()
        if k.lower() not in _HOP_BY_HOP
    }
    return Response(
        content=upstream_resp.content,
        status_code=upstream_resp.status_code,
        headers=resp_headers,
        media_type=upstream_resp.headers.get("content-type"),
    )
