# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: api-gateway/app/rate_limiter.py

import logging
import time

from app.config import settings

from shared.metrics.redis_tracker import TrackedRedis

log = logging.getLogger("api-gateway.rl")


class RateLimiter:
    """
    Sliding-window rate limiter backed by Redis sorted sets.

    Key layout:
      rl:ip:{client_ip}   -> 100 req / 60s
      rl:vpa:{debit_vpa}  -> 10  req / 60s
    """

    def __init__(self, client: TrackedRedis, cfg=settings):
        self._r = client
        self._cfg = cfg

    async def _sliding_check(self, key: str, limit: int) -> tuple[bool, int]:
        now = time.time()
        window_start = now - self._cfg.RL_WINDOW_SECONDS

        # Use raw client for pipeline — TrackedRedis does not wrap pipeline
        pipe = self._r._r.pipeline()
        pipe.zremrangebyscore(key, "-inf", window_start)
        pipe.zadd(key, {str(now): now})
        pipe.zcard(key)
        pipe.expire(key, self._cfg.RL_WINDOW_SECONDS + 1)
        results = await pipe.execute()

        count: int = results[2]
        allowed = count <= limit
        remaining = max(0, limit - count)
        return allowed, remaining

    async def check_ip(self, ip: str) -> tuple[bool, int]:
        key = f"rl:ip:{ip}"
        allowed, remaining = await self._sliding_check(key, self._cfg.RL_PER_IP_REQUESTS)
        if not allowed:
            log.warning("rate_limit=IP ip=%s count_over_limit=True", ip)
        return allowed, remaining

    async def check_vpa(self, vpa: str) -> tuple[bool, int]:
        key = f"rl:vpa:{vpa}"
        allowed, remaining = await self._sliding_check(key, self._cfg.RL_PER_VPA_REQUESTS)
        if not allowed:
            log.warning("rate_limit=VPA vpa=%s count_over_limit=True", vpa)
        return allowed, remaining
