# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/repository/routing_repository.py

import os
import boto3
import time
import logging
from typing import Optional
from app.config import settings

logger = logging.getLogger(__name__)

# ── Environment ───────────────────────────────────────────────────
_ENV      = os.getenv("ENV", "prod").lower()
_IS_LOCAL = _ENV == "local"
_MOCK     = "http://mock-bank-server:8080/mock"

# ── Seed data ─────────────────────────────────────────────────────
_SEED_ROUTES_PROD = [
    ("SBI",      "State Bank of India",       "https://upi.sbi.co.in/txn",        "https://upi2.sbi.co.in/txn"),
    ("ICICI",    "ICICI Bank",                "https://upi.icicibank.com/txn",     "https://upi2.icicibank.com/txn"),
    ("HDFC",     "HDFC Bank",                 "https://upi.hdfcbank.com/txn",      "https://upi2.hdfcbank.com/txn"),
    ("AXIS",     "Axis Bank",                 "https://upi.axisbank.co.in/txn",    "https://upi2.axisbank.co.in/txn"),
    ("YESBANK",  "Yes Bank",                  "https://upi.yesbank.in/txn",        "https://upi2.yesbank.in/txn"),
    ("PAYTM",    "Paytm Payments Bank",       "https://upi.paytmbank.com/txn",     "https://upi2.paytmbank.com/txn"),
    ("KOTAK",    "Kotak Mahindra Bank",       "https://upi.kotak.com/txn",         "https://upi2.kotak.com/txn"),
    ("INDUSIND", "IndusInd Bank",             "https://upi.indusind.com/txn",      "https://upi2.indusind.com/txn"),
    ("PNB",      "Punjab National Bank",      "https://upi.pnbindia.in/txn",       "https://upi2.pnbindia.in/txn"),
    ("BOI",      "Bank of India",             "https://upi.bankofindia.co.in/txn", "https://upi2.bankofindia.co.in/txn"),
    ("CANARA",   "Canara Bank",               "https://upi.canarabank.in/txn",     "https://upi2.canarabank.in/txn"),
    ("FEDERAL",  "Federal Bank",              "https://upi.federalbank.co.in/txn", "https://upi2.federalbank.co.in/txn"),
    ("NPCI",     "NPCI Default",              "https://upi.npci.org.in/txn",       "https://upi2.npci.org.in/txn"),
]

_SEED_ROUTES_LOCAL = [
    ("SBI",      "State Bank of India",       f"{_MOCK}/sbi/txn",      f"{_MOCK}/sbi/txn/fallback"),
    ("ICICI",    "ICICI Bank",                f"{_MOCK}/icici/txn",    f"{_MOCK}/icici/txn/fallback"),
    ("HDFC",     "HDFC Bank",                 f"{_MOCK}/hdfc/txn",     f"{_MOCK}/hdfc/txn/fallback"),
    ("AXIS",     "Axis Bank",                 f"{_MOCK}/axis/txn",     f"{_MOCK}/axis/txn/fallback"),
    ("YESBANK",  "Yes Bank",                  f"{_MOCK}/yesbank/txn",  f"{_MOCK}/yesbank/txn/fallback"),
    ("PAYTM",    "Paytm Payments Bank",       f"{_MOCK}/paytm/txn",    f"{_MOCK}/paytm/txn/fallback"),
    ("KOTAK",    "Kotak Mahindra Bank",       f"{_MOCK}/kotak/txn",    f"{_MOCK}/kotak/txn/fallback"),
    ("INDUSIND", "IndusInd Bank",             f"{_MOCK}/indusind/txn", f"{_MOCK}/indusind/txn/fallback"),
    ("PNB",      "Punjab National Bank",      f"{_MOCK}/pnb/txn",      f"{_MOCK}/pnb/txn/fallback"),
    ("BOI",      "Bank of India",             f"{_MOCK}/boi/txn",      f"{_MOCK}/boi/txn/fallback"),
    ("CANARA",   "Canara Bank",               f"{_MOCK}/canara/txn",   f"{_MOCK}/canara/txn/fallback"),
    ("FEDERAL",  "Federal Bank",              f"{_MOCK}/federal/txn",  f"{_MOCK}/federal/txn/fallback"),
    ("NPCI",     "NPCI Default",              f"{_MOCK}/npci/txn",     f"{_MOCK}/npci/txn/fallback"),
]

SEED_ROUTES = _SEED_ROUTES_LOCAL if _IS_LOCAL else _SEED_ROUTES_PROD
logger.info("Routing seed mode: ENV=%s  routes=%d", _ENV, len(SEED_ROUTES))


# ── Repository — unchanged from here down ─────────────────────────
class RoutingRepository:

    def __init__(self):
        self._client = boto3.resource(
            "dynamodb",
            region_name           = settings.aws_region,
            endpoint_url          = settings.dynamo_endpoint,
            aws_access_key_id     = settings.aws_access_key_id,
            aws_secret_access_key = settings.aws_secret_access_key,
        )
        self._table = None
        self._init_table()

    def _init_table(self):
        try:
            self._client.create_table(
                TableName            = settings.routing_table_name,
                KeySchema            = [{"AttributeName": "bankCode", "KeyType": "HASH"}],
                AttributeDefinitions = [{"AttributeName": "bankCode", "AttributeType": "S"}],
                BillingMode          = "PAY_PER_REQUEST",
            )
            logger.info("Created table: %s", settings.routing_table_name)
            self._table = self._client.Table(settings.routing_table_name)
            self._table.wait_until_exists()
            self._seed()

        except self._client.meta.client.exceptions.ResourceInUseException:
            logger.info("Table already exists — skipping seed: %s", settings.routing_table_name)
            self._table = self._client.Table(settings.routing_table_name)
            self._table.wait_until_exists()

    def _seed(self):
        for code, name, primary, fallback in SEED_ROUTES:
            self._table.put_item(Item={
                "bankCode":         code,
                "bankName":         name,
                "primaryEndpoint":  primary,
                "fallbackEndpoint": fallback,
                "active":           True,
                "updatedAt":        int(time.time() * 1000),
            })
        logger.info("Seeded %d routes", len(SEED_ROUTES))

    def find_by_bank_code(self, bank_code: str) -> Optional[dict]:
        resp = self._table.get_item(Key={"bankCode": bank_code})
        item = resp.get("Item")
        if item and item.get("active"):
            return item
        return None

    def find_all(self) -> list[dict]:
        return self._table.scan().get("Items", [])
