# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/repository/routing_repository.py

import boto3
import time
import logging
from typing import Optional
from app.config import settings

logger = logging.getLogger(__name__)

SEED_ROUTES = [
    ("SBI",      "State Bank of India",       "https://upi.sbi.co.in/txn",        "https://upi2.sbi.co.in/txn"),
    ("ICICI",    "ICICI Bank",                "https://upi.icicibank.com/txn",     "https://upi2.icicibank.com/txn"),
    ("HDFC",     "HDFC Bank",                 "https://upi.hdfcbank.com/txn",      "https://upi2.hdfcbank.com/txn"),
    ("AXIS",     "Axis Bank",                 "https://upi.axisbank.co.in/txn",    "https://upi2.axisbank.co.in/txn"),
    ("YESBANK",  "Yes Bank",                  "https://upi.yesbank.in/txn",        "https://upi2.yesbank.in/txn"),
    ("PAYTM",    "Paytm Payments Bank",       "https://upi.paytmbank.com/txn",     "https://upi2.paytmbank.com/txn"),
    ("KOTAK",    "Kotak Mahindra Bank",       "https://upi.kotak.com/txn",         "https://upi2.kotak.com/txn"),
    ("INDUSIND", "IndusInd Bank",             "https://upi.indusind.com/txn",      "https://upi2.indusind.com/txn"),
    ("PNB",      "Punjab National Bank",      "https://upi.pnbindia.in/txn",       "https://upi2.pnbindia.in/txn"),
    ("BOI",      "Bank of India",             "https://upi.bankofindia.co.in/txn", "https://upi2.bankofindia.co.in/txn"),
    ("CANARA",   "Canara Bank",               "https://upi.canarabank.in/txn",     "https://upi2.canarabank.in/txn"),
    ("FEDERAL",  "Federal Bank",              "https://upi.federalbank.co.in/txn", "https://upi2.federalbank.co.in/txn"),
    ("NPCI",     "NPCI Default",              "https://upi.npci.org.in/txn",       "https://upi2.npci.org.in/txn"),
]

class RoutingRepository:
    def __init__(self):
        self._client = boto3.resource(
            "dynamodb",
            region_name          = settings.aws_region,
            endpoint_url         = settings.dynamo_endpoint,
            aws_access_key_id    = settings.aws_access_key,
            aws_secret_access_key= settings.aws_secret_key,
        )
        self._table = None
        self._init_table()

    def _init_table(self):
        try:
            self._client.create_table(
                TableName            = settings.routing_table_name,
                KeySchema            = [{"AttributeName": "bankCode", "KeyType": "HASH"}],
                AttributeDefinitions = [{"AttributeName": "bankCode", "AttributeType": "S"}],
                BillingMode          = "PAY_PER_REQUEST",
            )
            logger.info("Created table: %s", settings.routing_table_name)
        except self._client.meta.client.exceptions.ResourceInUseException:
            logger.info("Table already exists: %s", settings.routing_table_name)

        self._table = self._client.Table(settings.routing_table_name)
        self._table.wait_until_exists()
        self._seed()

    def _seed(self):
        for code, name, primary, fallback in SEED_ROUTES:
            self._table.put_item(Item={
                "bankCode":         code,
                "bankName":         name,
                "primaryEndpoint":  primary,
                "fallbackEndpoint": fallback,
                "active":           True,
                "updatedAt":        int(time.time() * 1000),
            })
        logger.info("Seeded %d routes", len(SEED_ROUTES))

    def find_by_bank_code(self, bank_code: str) -> Optional[dict]:
        resp = self._table.get_item(Key={"bankCode": bank_code})
        item = resp.get("Item")
        if item and item.get("active"):
            return item
        return None

    def find_all(self) -> list[dict]:
        return self._table.scan().get("Items", [])
