# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/config.py

from pydantic_settings import BaseSettings

class Settings(BaseSettings):
    app_name: str       = "payment-router"
    port: int           = 8081

    # DynamoDB
    aws_region: str         = "ap-south-1"
    dynamo_endpoint: str    = "http://dynamodb-local:8000"
    aws_access_key: str     = "local"
    aws_secret_key: str     = "local"
    routing_table_name: str = "routing-table"

    # Redis
    redis_host: str     = "redis"
    redis_port: int     = 6379
    cache_ttl_seconds: int = 300

    class Config:
        env_file = ".env"

settings = Settings()
