# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/dependencies.py

from functools import lru_cache
import redis
from app.config import settings
from app.repository.routing_repository import RoutingRepository
from app.services.routing_service import RoutingService

@lru_cache
def get_repository() -> RoutingRepository:
    return RoutingRepository()

@lru_cache
def get_redis_client() -> redis.Redis:
    return redis.Redis(
        host     = settings.redis_host,
        port     = settings.redis_port,
        decode_responses = True,
    )

def get_routing_service() -> RoutingService:
    return RoutingService(get_repository(), get_redis_client())
