# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/router_metrics.py
"""
Records VPA resolution outcomes and maintains the rolling cache hit ratio.
Call record_resolution() after every VPA lookup.
"""

import time
from collections import deque
from threading import Lock

from shared.metrics.registry import (
    VPA_RESOLUTION_TOTAL,
    VPA_RESOLUTION_LATENCY_SECONDS,
    ROUTE_CACHE_OPS_TOTAL,
    ROUTE_CACHE_HIT_RATIO,
    VPA_UNKNOWN_TOTAL,
)

_SERVICE = "payment-router"

# Rolling window of last 200 cache lookups to compute hit ratio
_window: deque[bool] = deque(maxlen=200)
_lock   = Lock()


def _update_hit_ratio(hit: bool) -> None:
    with _lock:
        _window.append(hit)
        ratio = sum(_window) / len(_window) if _window else 1.0
    ROUTE_CACHE_HIT_RATIO.labels(service=_SERVICE).set(ratio)


def record_resolution(
    bank_code:     str,
    resolved_from: str,     # "DB" | "CACHE"
    success:       bool,
    duration_s:    float,
    handle_suffix: str = "",
) -> None:
    VPA_RESOLUTION_TOTAL.labels(
        bank_code     = bank_code,
        resolved_from = resolved_from,
        success       = str(success).lower(),
    ).inc()

    VPA_RESOLUTION_LATENCY_SECONDS.labels(
        bank_code     = bank_code,
        resolved_from = resolved_from,
    ).observe(duration_s)

    hit = resolved_from == "CACHE" and success
    _update_hit_ratio(hit)

    if not success and handle_suffix:
        VPA_UNKNOWN_TOTAL.labels(handle_suffix=handle_suffix).inc()


def record_cache_op(bank_code: str, operation: str) -> None:
    """operation: hit | miss | set | evict"""
    ROUTE_CACHE_OPS_TOTAL.labels(
        bank_code = bank_code,
        operation = operation,
    ).inc()
    if operation in ("hit", "miss"):
        _update_hit_ratio(operation == "hit")
