# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/services/routing_service.py

import json
import logging
from app.config import settings
from app.models import RouteRequest, RouteResponse
from app.resolvers.vpa_resolver import resolve_vpa
from app.resolvers.ifsc_resolver import resolve_ifsc
from app.repository.routing_repository import RoutingRepository
import redis as redis_lib

logger = logging.getLogger(__name__)

CACHE_PREFIX = "route:"

class RoutingService:
    def __init__(self, repository: RoutingRepository, redis_client: redis_lib.Redis):
        self._repo  = repository
        self._redis = redis_client

    def resolve(self, request: RouteRequest) -> RouteResponse:
        bank_code = self._extract_bank_code(request)
        logger.info("Resolving route for bankCode=%s", bank_code)

        cache_key = f"{CACHE_PREFIX}{bank_code}"

        # 1. Try Redis cache
        cached = self._redis.get(cache_key)
        if cached:
            ttl_ms = max((self._redis.pttl(cache_key)), 0)
            logger.info("Cache HIT for bankCode=%s", bank_code)
            route = json.loads(cached)
            return self._build_response(route, "CACHE", ttl_ms)

        # 2. Cache miss — read DynamoDB
        logger.info("Cache MISS for bankCode=%s — reading DynamoDB", bank_code)
        route = self._repo.find_by_bank_code(bank_code)
        if not route:
            from fastapi import HTTPException
            raise HTTPException(status_code=404,
                                detail=f"No active route for bankCode: {bank_code}")

        # 3. Repopulate cache
        try:
            self._redis.setex(cache_key, settings.cache_ttl_seconds, json.dumps(route))
        except Exception as e:
            logger.warning("Cache write failed for %s: %s", bank_code, e)

        return self._build_response(route, "DB", settings.cache_ttl_seconds * 1000)

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _extract_bank_code(self, request: RouteRequest) -> str:
        from fastapi import HTTPException
        if request.vpa:
            code = resolve_vpa(request.vpa)
            if not code:
                raise HTTPException(status_code=404,
                                    detail=f"Unknown VPA handle: {request.vpa}")
            return code
        code = resolve_ifsc(request.ifsc)
        if not code:
            raise HTTPException(status_code=404,
                                detail=f"Unknown IFSC prefix: {request.ifsc}")
        return code

    def _build_response(self, route: dict, source: str, ttl_ms: int) -> RouteResponse:
        return RouteResponse(
            bankCode         = route["bankCode"],
            bankName         = route["bankName"],
            primaryEndpoint  = route["primaryEndpoint"],
            fallbackEndpoint = route["fallbackEndpoint"],
            resolvedFrom     = source,
            ttlRemainingMs   = ttl_ms,
        )
