# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment_switch/handlers/payment_handler.py  (example usage)

from shared.metrics.ibts_metrics import (
    track_payment, payment_errors,
    bank_request_latency, circuit_breaker_state,
    idempotency_checks, rate_limit_hits, auth_failures,
)
import time

async def handle_payment(request):
    # ── Idempotency check ──────────────────────────────────────────────────────
    cached = await idempotency_store.get(request.idempotency_key)
    idem_result = "CACHED" if cached else "NEW"
    idempotency_checks.labels(idem_result=idem_result).inc()
    if cached:
        return cached

    # ── Main payment flow ──────────────────────────────────────────────────────
    with track_payment(payee_bank=request.payee_bank, idem_result=idem_result) as t:
        try:
            start = time.perf_counter()
            response = await bank_client.debit(request)             # outbound call
            bank_request_latency.labels(
                bank_code=request.payee_bank,
                endpoint_type="DEBIT",
            ).observe(time.perf_counter() - start)

            t.set_status("SUCCESS" if response.ok else "FAILED")

        except TimeoutError:
            payment_errors.labels(error_kind="TIMEOUT", service="payment-switch").inc()
            t.set_status("UNKNOWN")

        except BankRejectError as e:
            payment_errors.labels(error_kind="BANK_REJECT", service="payment-switch").inc()
            t.set_status("FAILED")
