[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Tag               ibts.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /tmp/fluent-bit.db
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name    record_modifier
    Match   ibts.*
    Record  env dev
    Record  project ibts

[OUTPUT]
    Name                es
    Match               ibts.*
    Host                elasticsearch
    Port                9200
    Logstash_Format     On
    Logstash_Prefix     ibts-logs
    Logstash_DateFormat %Y.%m.%d
    Suppress_Type_Name  On
    Retry_Limit         5
