# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/routers/payment_router.py

import os
import httpx
import redis

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from app.services.routing_service  import RoutingService
from app.repository.routing_repository import RoutingRepository
from app.models import RouteRequest

router = APIRouter(prefix="/api/v1/payment", tags=["payment"])

# ── Config from env (injected by docker-compose) ──────────────────────────
BANK_ADAPTER_URL = os.getenv(
    "BANK_ADAPTER_URL",
    "http://bank-adapter:8082/api/v1/adapter/send"
)
REDIS_HOST = os.getenv("REDIS_HOST", "redis")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))


class PaymentRequest(BaseModel):
    transactionId: str
    payerVpa:      str
    payeeVpa:      str
    amount:        float
    currency:      str = "INR"
    remarks:       str = ""


def _get_routing_service() -> RoutingService:
    redis_client = redis.Redis(
        host=REDIS_HOST, port=REDIS_PORT,
        decode_responses=True, socket_connect_timeout=2
    )
    return RoutingService(
        repository   = RoutingRepository(),
        redis_client = redis_client,
    )


@router.post("/initiate")
async def initiate(req: PaymentRequest):
    # Step 1 — resolve route via existing routing service
    routing_svc = _get_routing_service()
    route = routing_svc.resolve(RouteRequest(vpa=req.payerVpa))

    # Step 2 — forward to bank-adapter
    adapter_payload = {
        "transactionId":    req.transactionId,
        "bankCode":         route.bankCode,
        "primaryEndpoint":  route.primaryEndpoint,
        "fallbackEndpoint": route.fallbackEndpoint,
        "amount":           req.amount,
        "currency":         req.currency,
        "payerVpa":         req.payerVpa,
        "payeeVpa":         req.payeeVpa,
        "remarks":          req.remarks,
    }

    async with httpx.AsyncClient(timeout=12.0) as client:
        try:
            resp = await client.post(BANK_ADAPTER_URL, json=adapter_payload)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as e:
            raise HTTPException(
                status_code=e.response.status_code,
                detail=f"bank-adapter error: {e.response.text}"
            )
        except httpx.HTTPError as e:
            raise HTTPException(
                status_code=502,
                detail=f"bank-adapter unreachable: {str(e)}"
            )
