# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/routers/route_router.py

from fastapi import APIRouter, Depends
from app.models import RouteRequest, RouteResponse
from app.services.routing_service import RoutingService
from app.dependencies import get_routing_service

router = APIRouter(prefix="/api/v1/route", tags=["route"])

@router.post("/resolve", response_model=RouteResponse)
def resolve_route(request: RouteRequest,
                  service: RoutingService = Depends(get_routing_service)):
    return service.resolve(request)

@router.get("/debug/routes")
def debug_routes(service: RoutingService = Depends(get_routing_service)):
    return service._repo.find_all()
