# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: idempotency-service/app/idem_metrics.py
"""
Records idempotency check outcomes.
Call after every key lookup, before returning to payment-switch.
"""

from shared.metrics.registry import (
    IDEMPOTENCY_CHECKS_TOTAL,
    IDEMPOTENCY_STALE_PROCESSING_TOTAL,
)

_SERVICE = "idempotency-service"


def record_idem_check(result: str) -> None:
    """
    result: "NEW" | "CACHED" | "STALE_PROCESSING"
    """
    IDEMPOTENCY_CHECKS_TOTAL.labels(
        service     = _SERVICE,
        idem_result = result,
    ).inc()

    if result == "STALE_PROCESSING":
        IDEMPOTENCY_STALE_PROCESSING_TOTAL.labels(service=_SERVICE).inc()
