# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: router.py

import logging
from fastapi import APIRouter, Header, Response
from app.models import CheckRequest, CheckResponse, CompleteRequest
from app import service, store

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/idempotency")


@router.post("/check", response_model=CheckResponse)
def check(
    request: CheckRequest,
    x_idempotency_key: str = Header(..., alias="X-Idempotency-Key"),
    x_caller_service: str = Header(..., alias="X-Caller-Service"),
):
    result = service.check(x_idempotency_key, x_caller_service, request)
    status_code = 409 if result.duplicate else 200
    return Response(
        content=result.model_dump_json(),
        status_code=status_code,
        media_type="application/json",
    )


@router.post("/complete", status_code=204)
def complete(request: CompleteRequest):
    service.complete(request)


@router.get("/debug/records")
def debug_records():
    """Dev-only — inspect all in-memory records."""
    return store.scan_all()    # ✅ was store.all_records()
