# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: services.py
import time
import logging
from app import store
from app.models import CheckRequest, CheckResponse, CompleteRequest

logger = logging.getLogger(__name__)


def check(idempotency_key: str, caller_service: str, request: CheckRequest) -> CheckResponse:
    existing = store.find_by_key(idempotency_key)

    if existing:
        logger.info("Duplicate detected key=%s status=%s", idempotency_key, existing["status"])
        return CheckResponse(
            duplicate=True,
            status=existing["status"],
            transactionId=idempotency_key,
            responsePayload=existing.get("responsePayload"),
        )

    now = int(time.time() * 1000)
    new_record = {
        "idempotencyKey": idempotency_key,
        "callerService": caller_service,
        "transactionRefId": request.transactionRefId,
        "status": "PROCESSING",
        "responsePayload": None,
        "createdAt": now,
        "updatedAt": now,
    }

    inserted = store.insert_if_absent(new_record)

    if not inserted:
        # Race condition — another thread just inserted it
        existing = store.find_by_key(idempotency_key)
        logger.info("Race condition resolved key=%s", idempotency_key)
        return CheckResponse(
            duplicate=True,
            status=existing["status"] if existing else "PROCESSING",
            transactionId=idempotency_key,
            responsePayload=existing.get("responsePayload") if existing else None,
        )

    logger.info("New transaction accepted key=%s", idempotency_key)
    return CheckResponse(duplicate=False, status="PROCESSING", transactionId=idempotency_key)


def complete(request: CompleteRequest):
    store.complete(request.transactionId, request.finalStatus, request.responsePayload)
    logger.info("Completed transactionId=%s status=%s", request.transactionId, request.finalStatus)
