# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/resolvers/ifsc_resolver.py

from typing import Optional

PREFIX_MAP: dict[str, str] = {
    "SBIN": "SBI",
    "ICIC": "ICICI",
    "HDFC": "HDFC",
    "UTIB": "AXIS",
    "YESB": "YESBANK",
    "INDB": "INDUSIND",
    "PYTM": "PAYTM",
    "KKBK": "KOTAK",
    "PUNB": "PNB",
    "BKID": "BOI",
    "CNRB": "CANARA",
    "FDRL": "FEDERAL",
    "BARB": "BOB",
    "UBIN": "UBI",
    "IOBA": "IOB",
}

def resolve_ifsc(ifsc: str) -> Optional[str]:
    """'SBIN0001234' → 'SBI'"""
    if not ifsc or len(ifsc) < 4:
        return None
    return PREFIX_MAP.get(ifsc[:4].upper())
