# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-router/app/resolvers/vpa_resolver.py

from typing import Optional

HANDLE_MAP: dict[str, str] = {
    "sbi":        "SBI",
    "oksbi":      "SBI",
    "icici":      "ICICI",
    "okicici":    "ICICI",
    "hdfcbank":   "HDFC",
    "okhdfcbank": "HDFC",
    "axisbank":   "AXIS",
    "okaxis":     "AXIS",
    "ybl":        "YESBANK",    # PhonePe
    "ibl":        "INDUSIND",
    "paytm":      "PAYTM",
    "ptyes":      "PAYTM",
    "upi":        "NPCI",
    "kotak":      "KOTAK",
    "kmbl":       "KOTAK",
    "pnb":        "PNB",
    "boi":        "BOI",
    "cnrb":       "CANARA",
    "federal":    "FEDERAL",
    "fbl":        "FEDERAL",
    "ibts":       "YESBANK",   # IBTS test handle
}

def resolve_vpa(vpa: str) -> Optional[str]:
    """'john@sbi' â†’ 'SBI'"""
    if not vpa or "@" not in vpa:
        return None
    handle = vpa.split("@", 1)[1].lower().strip()
    return HANDLE_MAP.get(handle)

