# filename: scripts/deploy-observability.sh
# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${1:?Usage: deploy-observability.sh <cluster-name> <region>}"
REGION="${2:?Usage: deploy-observability.sh <cluster-name> <region>}"
OBS_NAMESPACE="ibts-observability"
GRAFANA_PASSWORD="${TF_VAR_grafana_admin_password:-ibts-grafana-dev}"
KARPENTER_VERSION="${KARPENTER_VERSION:-1.0.8}"

echo "==> Cluster : $CLUSTER_NAME"
echo "==> Region  : $REGION"

echo "==> Configuring kubectl"
aws eks update-kubeconfig --region "$REGION" --name "$CLUSTER_NAME"

echo "==> Verifying cluster connectivity"
kubectl get nodes --no-headers | awk '{print "  node:", $1, $2}'

echo "==> Node labels (checking for purpose label)"
kubectl get nodes --show-labels | grep -o 'purpose=[^ ,]*' || echo "  no purpose label found on any node"

echo "==> Adding Helm repos"
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add elastic               https://helm.elastic.co
helm repo add open-telemetry        https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo add jaegertracing         https://jaegertracing.github.io/helm-charts
helm repo add fluent                https://fluent.github.io/helm-charts
helm repo update
echo "  Repos updated"

# ════════════════════════════════════════
# HELPERS
# ════════════════════════════════════════
install_or_upgrade() {
  local release=$1
  local namespace=$2
  local chart=$3
  shift 3

  local status
  status=$(helm status "$release" -n "$namespace" --output json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")

  if [[ "$status" == "failed" || \
        "$status" == "pending-install" || \
        "$status" == "pending-upgrade" ]]; then
    echo "  Cleaning up stuck release $release (status: $status)"
    helm uninstall "$release" -n "$namespace" --ignore-not-found
    status="not-found"
  fi

  if [[ "$status" == "not-found" ]]; then
    echo "  Installing $release"
    helm install "$release" "$chart" -n "$namespace" "$@"
  else
    echo "  Upgrading $release (current status: $status)"
    helm upgrade "$release" "$chart" -n "$namespace" "$@"
  fi
}

# ════════════════════════════════════════
# KARPENTER
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " KARPENTER"
echo "══════════════════════════════════════"

CLUSTER_ENDPOINT=$(aws eks describe-cluster \
  --name "$CLUSTER_NAME" \
  --region "$REGION" \
  --query "cluster.endpoint" \
  --output text)

echo "  Cluster endpoint: $CLUSTER_ENDPOINT"

# ✅ FIX: no nodeSelector — label not confirmed on nodes
# ✅ FIX: no --wait — poll readiness separately for better debug output
install_or_upgrade karpenter kube-system \
  "oci://public.ecr.aws/karpenter/karpenter" \
  --version "${KARPENTER_VERSION}" \
  --set serviceAccount.create=false \
  --set serviceAccount.name=karpenter \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.clusterEndpoint=${CLUSTER_ENDPOINT}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}-karpenter" \
  --set "tolerations[0].key=CriticalAddonsOnly" \
  --set "tolerations[0].operator=Exists" \
  --set "tolerations[0].effect=NoSchedule" \
  --set "controller.resources.requests.cpu=100m" \
  --set "controller.resources.requests.memory=256Mi" \
  --set "controller.resources.limits.cpu=500m" \
  --set "controller.resources.limits.memory=512Mi"

echo "  Karpenter chart installed — polling pod readiness"
echo "  Current pod status:"
kubectl get pods -n kube-system -l app.kubernetes.io/name=karpenter -o wide || true

kubectl wait pod \
  -n kube-system \
  -l app.kubernetes.io/name=karpenter \
  --for=condition=Ready \
  --timeout=1200s \
  && echo "  ✅ Karpenter pod Ready" \
  || {
    echo "  ❌ Karpenter pod not Ready after 20 min — debug info:"
    echo "  --- pod status ---"
    kubectl get pods -n kube-system -l app.kubernetes.io/name=karpenter -o wide
    echo "  --- describe ---"
    kubectl describe pod -n kube-system -l app.kubernetes.io/name=karpenter
    echo "  --- logs ---"
    kubectl logs -n kube-system -l app.kubernetes.io/name=karpenter --tail=50 2>/dev/null || true
    exit 1
  }

echo "  Waiting 90s for Karpenter webhook to register"
sleep 90

echo "==> Applying EC2NodeClass"
kubectl apply -f - <<EOF
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: "${CLUSTER_NAME}-karpenter-node"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
EOF

echo "==> Applying NodePool"
kubectl apply -f - <<EOF
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3a.medium", "t3.large"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["${REGION}a", "${REGION}b"]
  limits:
    cpu: "8"
    memory: 16Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
EOF

echo "  EC2NodeClass + NodePool applied"
echo "  Pausing 30s for Karpenter controller to reconcile"
sleep 30

# ════════════════════════════════════════
# OBSERVABILITY STACK
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " OBSERVABILITY STACK"
echo "══════════════════════════════════════"

kubectl create namespace "$OBS_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

echo "==> Deploying kube-prometheus-stack"
install_or_upgrade kube-prometheus-stack "$OBS_NAMESPACE" \
  prometheus-community/kube-prometheus-stack \
  --version 58.2.2 \
  --timeout 15m \
  --set prometheusOperator.admissionWebhooks.enabled=false \
  --set prometheusOperator.admissionWebhooks.patch.enabled=false \
  --set "grafana.adminPassword=${GRAFANA_PASSWORD}" \
  --set grafana.persistence.enabled=true \
  --set grafana.persistence.storageClassName=gp3 \
  --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName=gp3 \
  --set prometheus.prometheusSpec.retention=30d \
  --wait

echo "==> Deploying elasticsearch"
install_or_upgrade elasticsearch "$OBS_NAMESPACE" \
  elastic/elasticsearch \
  --version 8.5.1 \
  --timeout 15m \
  --set replicas=1 \
  --set minimumMasterNodes=1 \
  --set esJavaOpts="-Xmx512m -Xms512m" \
  --set volumeClaimTemplate.storageClassName=gp3 \
  --set "esConfig.elasticsearch\\.yml=xpack.security.enabled: false\nxpack.ml.enabled: false\n" \
  --wait

echo "==> Deploying kibana"
install_or_upgrade kibana "$OBS_NAMESPACE" \
  elastic/kibana \
  --version 8.5.1 \
  --timeout 10m \
  --set "elasticsearchHosts=http://elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local:9200" \
  --wait

echo "==> Deploying otel-collector"
install_or_upgrade otel-collector "$OBS_NAMESPACE" \
  open-telemetry/opentelemetry-collector \
  --version 0.91.0 \
  --timeout 5m \
  --set mode=deployment \
  --set image.repository=otel/opentelemetry-collector-contrib \
  --wait

echo "==> Deploying jaeger"
install_or_upgrade jaeger "$OBS_NAMESPACE" \
  jaegertracing/jaeger \
  --version 3.0.0 \
  --timeout 5m \
  --set provisionDataStore.cassandra=false \
  --set provisionDataStore.elasticsearch=false \
  --set storage.type=elasticsearch \
  --set "storage.elasticsearch.host=elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local" \
  --set storage.elasticsearch.port=9200 \
  --set agent.enabled=false \
  --wait

echo "==> Deploying fluent-bit"
install_or_upgrade fluent-bit "$OBS_NAMESPACE" \
  fluent/fluent-bit \
  --version 0.46.7 \
  --timeout 5m \
  --wait

# ════════════════════════════════════════
# SUMMARY
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " DEPLOYMENT COMPLETE"
echo "══════════════════════════════════════"
echo ""
echo "Karpenter:"
helm status karpenter -n kube-system --output json \
  | python3 -c "import sys,json; d=json.load(sys.stdin); \
      print('  status :', d['info']['status'])"

echo ""
echo "Observability:"
for release in kube-prometheus-stack elasticsearch kibana \
               otel-collector jaeger fluent-bit; do
  STATUS=$(helm status "$release" -n "$OBS_NAMESPACE" --output json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")
  printf "  %-30s %s\n" "$release" "$STATUS"
done

echo ""
echo "Nodes:"
kubectl get nodes --no-headers | awk '{printf "  %-40s %s\n", $1, $2}'
echo ""
