# filename: scripts/deploy-observability.sh
# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="${1:?Usage: deploy-observability.sh <cluster-name> <region>}"
REGION="${2:?Usage: deploy-observability.sh <cluster-name> <region>}"
OBS_NAMESPACE="ibts-observability"
GRAFANA_PASSWORD="${TF_VAR_grafana_admin_password:-ibts-grafana-dev}"
KARPENTER_VERSION="${KARPENTER_VERSION:-1.0.8}"

echo "==> Cluster : $CLUSTER_NAME"
echo "==> Region  : $REGION"

echo "==> Configuring kubectl"
aws eks update-kubeconfig --region "$REGION" --name "$CLUSTER_NAME"

echo "==> Verifying cluster connectivity"
kubectl get nodes --no-headers | awk '{print "  node:", $1, $2}'

echo "==> Node labels (checking for purpose label)"
kubectl get nodes --show-labels | grep -o 'purpose=[^ ,]*' || echo "  no purpose label found on any node"

echo "==> Adding Helm repos"
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add elastic               https://helm.elastic.co
helm repo add open-telemetry        https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo add jaegertracing         https://jaegertracing.github.io/helm-charts
helm repo add fluent                https://fluent.github.io/helm-charts
helm repo update
echo "  Repos updated"

# ════════════════════════════════════════
# HELPERS
# ════════════════════════════════════════
install_or_upgrade() {
  local release=$1
  local namespace=$2
  local chart=$3
  shift 3

  local status
  status=$(helm status "$release" -n "$namespace" --output json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")

  if [[ "$status" == "failed" || \
        "$status" == "pending-install" || \
        "$status" == "pending-upgrade" ]]; then
    echo "  Cleaning up stuck release $release (status: $status)"
    helm uninstall "$release" -n "$namespace" --ignore-not-found
    status="not-found"
  fi

  if [[ "$status" == "not-found" ]]; then
    echo "  Installing $release"
    helm install "$release" "$chart" -n "$namespace" "$@"
  else
    echo "  Upgrading $release (current status: $status)"
    helm upgrade "$release" "$chart" -n "$namespace" "$@"
  fi
}

# Poll pods every 30s — print events every 60s — full dump on timeout
wait_for_pods() {
  local namespace=$1
  local label=$2
  local timeout_seconds=${3:-900}
  local elapsed=0
  local interval=30

  echo "  Waiting for pods -l $label in $namespace (timeout ${timeout_seconds}s)"
  while [[ $elapsed -lt $timeout_seconds ]]; do
    local total ready
    total=$(kubectl get pods -n "$namespace" -l "$label" \
      --no-headers 2>/dev/null | wc -l | tr -d ' ')
    ready=$(kubectl get pods -n "$namespace" -l "$label" \
      --no-headers 2>/dev/null \
      | awk '$2~/^([0-9]+)\/\1$/ && $3=="Running"' | wc -l | tr -d ' ')

    echo "  [${elapsed}s] pods ready: ${ready}/${total}"

    if [[ "$total" -gt "0" && "$ready" -eq "$total" ]]; then
      echo "  ✅ All pods Ready"
      return 0
    fi

    if (( elapsed % 60 == 0 && elapsed > 0 )); then
      echo "  --- scheduling events ---"
      kubectl get events -n "$namespace" \
        --field-selector reason=FailedScheduling \
        --sort-by='.lastTimestamp' 2>/dev/null | tail -5 || true
      echo "  --- pod status ---"
      kubectl get pods -n "$namespace" -l "$label" \
        --no-headers 2>/dev/null || true
      echo "  --- karpenter provisioning ---"
      kubectl get nodeclaims 2>/dev/null | head -10 || true
    fi

    sleep $interval
    elapsed=$(( elapsed + interval ))
  done

  echo "  ❌ Pods not Ready after ${timeout_seconds}s — full diagnostic dump:"
  kubectl get pods -n "$namespace" --no-headers
  kubectl get pvc  -n "$namespace" 2>/dev/null || true
  kubectl get events -n "$namespace" --sort-by='.lastTimestamp' | tail -30
  kubectl describe pods -n "$namespace" -l "$label" \
    | grep -A 15 "Events:" || true
  return 1
}

# ════════════════════════════════════════
# PREREQUISITE CHECKS
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " PREREQUISITE CHECKS"
echo "══════════════════════════════════════"

PREREQ_FAILED=0

echo "==> Checking SQS queue: ${CLUSTER_NAME}-karpenter"
SQS_URL=$(aws sqs get-queue-url \
  --queue-name "${CLUSTER_NAME}-karpenter" \
  --region "$REGION" \
  --query 'QueueUrl' \
  --output text 2>/dev/null || echo "MISSING")

if [[ "$SQS_URL" == "MISSING" ]]; then
  echo "  ❌ SQS queue ${CLUSTER_NAME}-karpenter NOT FOUND — stage2 Terraform did not complete"
  PREREQ_FAILED=1
else
  echo "  ✅ SQS queue exists: $SQS_URL"
fi

echo "==> Checking IAM role: ${CLUSTER_NAME}-karpenter-controller"
ROLE_ARN=$(aws iam get-role \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --query 'Role.Arn' \
  --output text 2>/dev/null || echo "MISSING")

if [[ "$ROLE_ARN" == "MISSING" ]]; then
  echo "  ❌ IAM role ${CLUSTER_NAME}-karpenter-controller NOT FOUND"
  PREREQ_FAILED=1
else
  echo "  ✅ IAM role exists: $ROLE_ARN"
fi

echo "==> Checking Karpenter service account IRSA annotation"
SA_ROLE=$(kubectl get serviceaccount karpenter -n kube-system \
  -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}' \
  2>/dev/null || echo "MISSING")

if [[ "$SA_ROLE" == "MISSING" || -z "$SA_ROLE" ]]; then
  echo "  ❌ Service account karpenter missing IRSA annotation"
  PREREQ_FAILED=1
else
  echo "  ✅ IRSA annotation: $SA_ROLE"
fi

if [[ "$PREREQ_FAILED" == "1" ]]; then
  echo ""
  echo "  ❌ Prerequisites missing — ensure stage2-apply completed then re-run"
  exit 1
fi

echo "  ✅ All prerequisites verified"

# ════════════════════════════════════════
# PATCH IAM PERMISSIONS
# Safety net — Terraform is the permanent
# fix via 03-karpenter.tf inline policy.
# This covers the current run immediately.
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " IAM PERMISSION PATCHES"
echo "══════════════════════════════════════"

SQS_QUEUE_ARN=$(aws sqs get-queue-attributes \
  --queue-url "$SQS_URL" \
  --attribute-names QueueArn \
  --query 'Attributes.QueueArn' \
  --output text)

echo "==> Queue ARN: $SQS_QUEUE_ARN"

# Patch 1 — SQS permissions
HAS_SQS=$(aws iam list-attached-role-policies \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --query 'AttachedPolicies[].PolicyArn' --output text \
  | xargs -I{} aws iam get-policy-version \
  --policy-arn {} --version-id v1 \
  --query 'PolicyVersion.Document.Statement[].Action[]' \
  --output text 2>/dev/null | grep -c "sqs" || echo "0")

if [[ "$HAS_SQS" == "0" ]]; then
  echo "==> Attaching inline SQS policy"
  aws iam put-role-policy \
    --role-name "${CLUSTER_NAME}-karpenter-controller" \
    --policy-name "KarpenterSQSInterruption" \
    --policy-document "{
      \"Version\": \"2012-10-17\",
      \"Statement\": [{
        \"Sid\": \"KarpenterSQSInterruption\",
        \"Effect\": \"Allow\",
        \"Action\": [
          \"sqs:GetQueueUrl\",
          \"sqs:GetQueueAttributes\",
          \"sqs:ReceiveMessage\",
          \"sqs:DeleteMessage\"
        ],
        \"Resource\": \"${SQS_QUEUE_ARN}\"
      }]
    }"
  echo "  ✅ SQS inline policy attached"
else
  echo "  ✅ SQS permissions already present"
fi

# Patch 2 — Instance profile permissions
# Karpenter v1 calls iam:GetInstanceProfile / CreateInstanceProfile
# at runtime when reconciling EC2NodeClass.
# Without these the EC2NodeClass stays InstanceProfileReady=Unknown
# and NodePool stays Ready=False → no nodes provisioned → all pods
# stay Pending forever → every Helm install times out
echo "==> Attaching instance profile permissions to Karpenter controller role"
aws iam put-role-policy \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --policy-name "KarpenterInstanceProfilePermissions" \
  --policy-document '{
    "Version": "2012-10-17",
    "Statement": [{
      "Sid": "KarpenterInstanceProfile",
      "Effect": "Allow",
      "Action": [
        "iam:CreateInstanceProfile",
        "iam:DeleteInstanceProfile",
        "iam:GetInstanceProfile",
        "iam:AddRoleToInstanceProfile",
        "iam:RemoveRoleFromInstanceProfile",
        "iam:TagInstanceProfile"
      ],
      "Resource": "*"
    }]
  }'
echo "  ✅ Instance profile permissions attached"

# ════════════════════════════════════════
# KARPENTER
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " KARPENTER"
echo "══════════════════════════════════════"

CLUSTER_ENDPOINT=$(aws eks describe-cluster \
  --name "$CLUSTER_NAME" \
  --region "$REGION" \
  --query "cluster.endpoint" \
  --output text)

echo "  Cluster endpoint: $CLUSTER_ENDPOINT"

install_or_upgrade karpenter kube-system \
  "oci://public.ecr.aws/karpenter/karpenter" \
  --version "${KARPENTER_VERSION}" \
  --set serviceAccount.create=false \
  --set serviceAccount.name=karpenter \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.clusterEndpoint=${CLUSTER_ENDPOINT}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}-karpenter" \
  --set "tolerations[0].key=CriticalAddonsOnly" \
  --set "tolerations[0].operator=Exists" \
  --set "tolerations[0].effect=NoSchedule" \
  --set "controller.resources.requests.cpu=100m" \
  --set "controller.resources.requests.memory=256Mi" \
  --set "controller.resources.limits.cpu=500m" \
  --set "controller.resources.limits.memory=512Mi"

echo "  Karpenter chart installed — polling pod readiness"
echo "  Current pod status:"
kubectl get pods -n kube-system -l app.kubernetes.io/name=karpenter -o wide || true

kubectl wait pod \
  -n kube-system \
  -l app.kubernetes.io/name=karpenter \
  --for=condition=Ready \
  --timeout=1200s \
  && echo "  ✅ Karpenter pod Ready" \
  || {
    echo "  ❌ Karpenter pod not Ready after 20 min"
    kubectl get pods    -n kube-system -l app.kubernetes.io/name=karpenter -o wide
    kubectl describe pod -n kube-system -l app.kubernetes.io/name=karpenter
    kubectl logs        -n kube-system -l app.kubernetes.io/name=karpenter --tail=50 2>/dev/null || true
    exit 1
  }

echo "  Waiting 90s for Karpenter webhook to register"
sleep 90

echo "==> Applying EC2NodeClass"
kubectl apply -f - <<EOF
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2@latest
  role: "${CLUSTER_NAME}-karpenter-node"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${CLUSTER_NAME}"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
EOF

echo "==> Applying NodePool"
kubectl apply -f - <<EOF
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      annotations:
        karpenter.sh/expire-after: 720h
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3a.medium", "t3.large", "t3.xlarge"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["${REGION}a", "${REGION}b"]
  limits:
    cpu: "16"
    memory: 32Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
EOF

echo "  EC2NodeClass + NodePool applied"

# Wait for EC2NodeClass to become Ready before installing observability
# If InstanceProfileReady stays Unknown, Karpenter cannot provision nodes
echo "==> Waiting for EC2NodeClass to become Ready (max 3 min)"
for i in $(seq 1 18); do
  STATUS=$(kubectl get ec2nodeclass default \
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' \
    2>/dev/null || echo "Unknown")
  INSTANCE_PROFILE=$(kubectl get ec2nodeclass default \
    -o jsonpath='{.status.conditions[?(@.type=="InstanceProfileReady")].status}' \
    2>/dev/null || echo "Unknown")
  echo "  [$(( i * 10 ))s] EC2NodeClass Ready=${STATUS}  InstanceProfileReady=${INSTANCE_PROFILE}"
  if [[ "$STATUS" == "True" ]]; then
    echo "  ✅ EC2NodeClass Ready"
    break
  fi
  if [[ $i -eq 18 ]]; then
    echo "  ⚠️  EC2NodeClass not Ready after 3 min — check Karpenter logs:"
    kubectl logs -n kube-system \
      -l app.kubernetes.io/name=karpenter --tail=30 2>/dev/null || true
    echo "  Continuing anyway — nodes may still provision"
  fi
  sleep 10
done

echo "  Pausing 30s for Karpenter controller to reconcile"
sleep 30

# ════════════════════════════════════════
# STORAGE PREREQUISITES
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " STORAGE PREREQUISITES"
echo "══════════════════════════════════════"

echo "==> Verifying EBS CSI driver is running"
kubectl wait pod \
  -n kube-system \
  -l app.kubernetes.io/name=aws-ebs-csi-driver \
  --for=condition=Ready \
  --timeout=120s \
  && echo "  ✅ EBS CSI driver Ready" \
  || {
    echo "  ⚠️  Checking EBS CSI pods by name"
    kubectl get pods -n kube-system | grep ebs || echo "  ❌ No EBS CSI pods found"
  }

echo "==> Ensuring gp3 StorageClass exists"
if kubectl get storageclass gp3 &>/dev/null; then
  echo "  ✅ gp3 StorageClass already exists"
  kubectl get storageclass gp3
else
  echo "  gp3 StorageClass missing — creating"
  kubectl apply -f - <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
EOF
  echo "  ✅ gp3 StorageClass created"
fi

echo "==> Removing default annotation from gp2 if present"
kubectl patch storageclass gp2 \
  -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}' \
  2>/dev/null && echo "  ✅ gp2 default annotation removed" \
  || echo "  gp2 not present or already non-default — skipping"

echo "==> Current StorageClasses:"
kubectl get storageclass

# ════════════════════════════════════════
# NODE CAPACITY CHECK
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " NODE CAPACITY CHECK"
echo "══════════════════════════════════════"

echo "==> Current nodes and allocatable capacity:"
kubectl get nodes -o custom-columns=\
"NAME:.metadata.name,\
STATUS:.status.conditions[-1].type,\
CPU:.status.allocatable.cpu,\
MEM:.status.allocatable.memory,\
ZONE:.metadata.labels.topology\.kubernetes\.io/zone"

echo ""
echo "==> Karpenter NodePool status:"
kubectl get nodepool default -o jsonpath=\
'{.status.conditions}' 2>/dev/null \
  | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  for c in data:
    print(f\"  {c.get('type','?'):30s} {c.get('status','?'):8s} {c.get('message','')}\")
except Exception as e:
  print('  could not parse:', e)
" 2>/dev/null || kubectl get nodepool default 2>/dev/null || echo "  NodePool not found"

echo ""
echo "==> Karpenter EC2NodeClass status:"
kubectl get ec2nodeclass default -o jsonpath=\
'{.status.conditions}' 2>/dev/null \
  | python3 -c "
import sys, json
try:
  data = json.load(sys.stdin)
  for c in data:
    print(f\"  {c.get('type','?'):30s} {c.get('status','?'):8s} {c.get('message','')}\")
except Exception as e:
  print('  could not parse:', e)
" 2>/dev/null || echo "  EC2NodeClass status unavailable"

echo ""
echo "==> Subnet discovery (karpenter.sh/discovery tag):"
aws ec2 describe-subnets \
  --region "$REGION" \
  --filters "Name=tag:karpenter.sh/discovery,Values=${CLUSTER_NAME}" \
  --query 'Subnets[].{ID:SubnetId,AZ:AvailabilityZone,CIDR:CidrBlock}' \
  --output table 2>/dev/null \
  || echo "  ⚠️  No subnets tagged karpenter.sh/discovery=${CLUSTER_NAME}"

echo ""
echo "==> Security group discovery (karpenter.sh/discovery tag):"
aws ec2 describe-security-groups \
  --region "$REGION" \
  --filters "Name=tag:karpenter.sh/discovery,Values=${CLUSTER_NAME}" \
  --query 'SecurityGroups[].{ID:GroupId,Name:GroupName}' \
  --output table 2>/dev/null \
  || echo "  ⚠️  No security groups tagged karpenter.sh/discovery=${CLUSTER_NAME}"

# ════════════════════════════════════════
# OBSERVABILITY STACK
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " OBSERVABILITY STACK"
echo "══════════════════════════════════════"

kubectl create namespace "$OBS_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

echo "==> Deploying kube-prometheus-stack"
install_or_upgrade kube-prometheus-stack "$OBS_NAMESPACE" \
  prometheus-community/kube-prometheus-stack \
  --version 58.2.2 \
  --timeout 30m \
  --set prometheusOperator.admissionWebhooks.enabled=false \
  --set prometheusOperator.admissionWebhooks.patch.enabled=false \
  --set "grafana.adminPassword=${GRAFANA_PASSWORD}" \
  --set grafana.persistence.enabled=true \
  --set grafana.persistence.storageClassName=gp3 \
  --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName=gp3 \
  --set prometheus.prometheusSpec.retention=30d

# ✅ FIXED: "release=kube-prometheus-stack" matched 0 pods
# correct label is app.kubernetes.io/instance
echo "  Waiting for kube-prometheus-stack pods"
wait_for_pods "$OBS_NAMESPACE" \
  "app.kubernetes.io/instance=kube-prometheus-stack" 1800

echo "==> Deploying elasticsearch"
install_or_upgrade elasticsearch "$OBS_NAMESPACE" \
  elastic/elasticsearch \
  --version 8.5.1 \
  --timeout 15m \
  --set replicas=1 \
  --set minimumMasterNodes=1 \
  --set esJavaOpts="-Xmx512m -Xms512m" \
  --set volumeClaimTemplate.storageClassName=gp3 \
  --set "esConfig.elasticsearch\\.yml=xpack.security.enabled: false\nxpack.ml.enabled: false\n"

echo "  Waiting for elasticsearch pods"
wait_for_pods "$OBS_NAMESPACE" "app=elasticsearch-master" 900

echo "==> Deploying kibana"
install_or_upgrade kibana "$OBS_NAMESPACE" \
  elastic/kibana \
  --version 8.5.1 \
  --timeout 10m \
  --set "elasticsearchHosts=http://elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local:9200"

echo "  Waiting for kibana pods"
wait_for_pods "$OBS_NAMESPACE" "app=kibana" 600

echo "==> Deploying otel-collector"
install_or_upgrade otel-collector "$OBS_NAMESPACE" \
  open-telemetry/opentelemetry-collector \
  --version 0.91.0 \
  --timeout 5m \
  --set mode=deployment \
  --set image.repository=otel/opentelemetry-collector-contrib

echo "  Waiting for otel-collector pods"
wait_for_pods "$OBS_NAMESPACE" \
  "app.kubernetes.io/name=opentelemetry-collector" 300

echo "==> Deploying jaeger"
install_or_upgrade jaeger "$OBS_NAMESPACE" \
  jaegertracing/jaeger \
  --version 3.0.0 \
  --timeout 5m \
  --set provisionDataStore.cassandra=false \
  --set provisionDataStore.elasticsearch=false \
  --set storage.type=elasticsearch \
  --set "storage.elasticsearch.host=elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local" \
  --set storage.elasticsearch.port=9200 \
  --set agent.enabled=false

echo "  Waiting for jaeger pods"
wait_for_pods "$OBS_NAMESPACE" "app.kubernetes.io/name=jaeger" 300

echo "==> Deploying fluent-bit"
install_or_upgrade fluent-bit "$OBS_NAMESPACE" \
  fluent/fluent-bit \
  --version 0.46.7 \
  --timeout 5m

echo "  Waiting for fluent-bit pods"
wait_for_pods "$OBS_NAMESPACE" "app.kubernetes.io/name=fluent-bit" 300

# ════════════════════════════════════════
# SUMMARY
# ════════════════════════════════════════
echo ""
echo "══════════════════════════════════════"
echo " DEPLOYMENT COMPLETE"
echo "══════════════════════════════════════"
echo ""
echo "Karpenter:"
helm status karpenter -n kube-system --output json \
  | python3 -c "import sys,json; d=json.load(sys.stdin); \
      print('  status :', d['info']['status'])"

echo ""
echo "Observability:"
for release in kube-prometheus-stack elasticsearch kibana \
               otel-collector jaeger fluent-bit; do
  STATUS=$(helm status "$release" -n "$OBS_NAMESPACE" --output json 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")
  printf "  %-30s %s\n" "$release" "$STATUS"
done

echo ""
echo "Nodes:"
kubectl get nodes --no-headers \
  | awk '{printf "  %-40s %s\n", $1, $2}'

echo ""
echo "PVCs:"
kubectl get pvc -n "$OBS_NAMESPACE" 2>/dev/null || echo "  none"

echo ""
echo "Pods:"
kubectl get pods -n "$OBS_NAMESPACE" --no-headers \
  | awk '{printf "  %-50s %s\n", $1, $3}'
echo ""
