#!/usr/bin/env bash
# filename: scripts/deploy-observability.sh
# Code Generated by Sidekick is for learning and experimentation purposes only.
set -euo pipefail

CLUSTER_NAME="${1:?Usage: deploy-observability.sh <cluster-name> <region>}"
REGION="${2:?Usage: deploy-observability.sh <cluster-name> <region>}"
OBS_NAMESPACE="ibts-observability"
GRAFANA_PASSWORD="${TF_VAR_grafana_admin_password:-ibts-grafana-dev}"
KARPENTER_VERSION="${KARPENTER_VERSION:-1.0.8}"

echo "==> Cluster : $CLUSTER_NAME"
echo "==> Region  : $REGION"

echo "==> Configuring kubectl"
aws eks update-kubeconfig --region "$REGION" --name "$CLUSTER_NAME"

echo "==> Verifying cluster connectivity"
kubectl get nodes --no-headers | awk '{print "  node:", $1, $2}'

echo "==> Node taints"
kubectl get nodes \
  -o custom-columns="NAME:.metadata.name,TAINTS:.spec.taints" \
  2>/dev/null || true

echo "==> Adding Helm repos"
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add elastic               https://helm.elastic.co
helm repo add open-telemetry        https://open-telemetry.github.io/opentelemetry-helm-charts
helm repo add jaegertracing         https://jaegertracing.github.io/helm-charts
helm repo add fluent                https://fluent.github.io/helm-charts
helm repo update
echo "  Repos updated"

# =========================================
# HELPERS
# =========================================

refresh_kubeconfig() {
  echo "  Refreshing kubeconfig token"
  aws eks update-kubeconfig --region "$REGION" --name "$CLUSTER_NAME" \
    --alias "$CLUSTER_NAME" 2>/dev/null || true
}

debug_namespace() {
  local ns=$1
  echo ""
  echo "  == DEBUG $ns =="
  kubectl get all        -n "$ns" 2>/dev/null || true
  kubectl get pvc        -n "$ns" 2>/dev/null || true
  kubectl get quota      -n "$ns" 2>/dev/null || true
  kubectl get limitrange -n "$ns" 2>/dev/null || true
  kubectl get events     -n "$ns" \
    --sort-by='.lastTimestamp' 2>/dev/null | tail -20 || true
  kubectl describe replicasets -n "$ns" 2>/dev/null \
    | grep -A 10 "Events:" || true
  kubectl get nodeclaims 2>/dev/null || echo "  no nodeclaims"
  kubectl logs -n kube-system \
    -l app.kubernetes.io/name=karpenter --tail=10 2>/dev/null || true
  echo "  == END DEBUG =="
  echo ""
}

wait_for_pods() {
  local namespace=$1
  local description=$2
  local timeout_seconds=${3:-900}
  local elapsed=0
  local interval=30

  echo "  Polling $description (timeout ${timeout_seconds}s)"

  while [[ $elapsed -lt $timeout_seconds ]]; do
    if (( elapsed > 0 && elapsed % 600 == 0 )); then
      refresh_kubeconfig
    fi

    local total ready pending failed

    total=$(kubectl get pods -n "$namespace" \
      --no-headers 2>/dev/null | wc -l | tr -d ' ')

    ready=$(kubectl get pods -n "$namespace" \
      --no-headers 2>/dev/null \
      | awk '$3=="Running" {
          split($2,a,"/")
          if (a[1]==a[2] && a[1]+0>0) count++
        }
        END { print count+0 }')

    pending=$(kubectl get pods -n "$namespace" \
      --no-headers 2>/dev/null \
      | awk '$3=="Pending"' | wc -l | tr -d ' ')

    failed=$(kubectl get pods -n "$namespace" \
      --no-headers 2>/dev/null \
      | awk '$3~/Error|CrashLoop|OOMKilled/' \
      | wc -l | tr -d ' ')

    echo "  [${elapsed}s] total=${total} ready=${ready} pending=${pending} failed=${failed}"

    if [[ "$total" -gt "0" && "$ready" -eq "$total" && "$failed" -eq "0" ]]; then
      echo "  [OK] All $description pods Ready"
      return 0
    fi

    if [[ $elapsed -eq 60 && "$total" -eq "0" ]]; then
      echo "  [WARN] total=0 after 60s -- full debug:"
      debug_namespace "$namespace"
    fi

    if (( elapsed % 120 == 0 && elapsed > 60 )); then
      kubectl get pods -n "$namespace" -o wide --no-headers 2>/dev/null || true
      kubectl get events -n "$namespace" \
        --field-selector reason=FailedScheduling \
        --sort-by='.lastTimestamp' 2>/dev/null | tail -5 || true
      kubectl get nodeclaims 2>/dev/null || true
    fi

    sleep $interval
    elapsed=$(( elapsed + interval ))
  done

  echo "  [FAIL] Timeout"
  debug_namespace "$namespace"
  return 1
}

# =========================================
# PREREQUISITE CHECKS
# =========================================
echo ""
echo "=========================================="
echo " PREREQUISITE CHECKS"
echo "=========================================="

PREREQ_FAILED=0

SQS_URL=$(aws sqs get-queue-url \
  --queue-name "${CLUSTER_NAME}-karpenter" \
  --region "$REGION" \
  --query 'QueueUrl' \
  --output text 2>/dev/null || echo "MISSING")
[[ "$SQS_URL" == "MISSING" ]] \
  && echo "  [FAIL] SQS NOT FOUND" && PREREQ_FAILED=1 \
  || echo "  [OK] SQS: $SQS_URL"

PROFILE_ARN=$(aws iam get-instance-profile \
  --instance-profile-name "${CLUSTER_NAME}-karpenter-node" \
  --query 'InstanceProfile.Arn' \
  --output text 2>/dev/null || echo "MISSING")
[[ "$PROFILE_ARN" == "MISSING" ]] \
  && echo "  [FAIL] Instance profile NOT FOUND" && PREREQ_FAILED=1 \
  || echo "  [OK] Instance profile: $PROFILE_ARN"

ROLE_ARN=$(aws iam get-role \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --query 'Role.Arn' --output text 2>/dev/null || echo "MISSING")
[[ "$ROLE_ARN" == "MISSING" ]] \
  && echo "  [FAIL] IAM role NOT FOUND" && PREREQ_FAILED=1 \
  || echo "  [OK] IAM role: $ROLE_ARN"

SA_ROLE=$(kubectl get serviceaccount karpenter -n kube-system \
  -o jsonpath='{.metadata.annotations.eks\.amazonaws\.com/role-arn}' \
  2>/dev/null || echo "MISSING")
[[ "$SA_ROLE" == "MISSING" || -z "$SA_ROLE" ]] \
  && echo "  [FAIL] IRSA missing" && PREREQ_FAILED=1 \
  || echo "  [OK] IRSA: $SA_ROLE"

[[ "$PREREQ_FAILED" == "1" ]] && exit 1
echo "  [OK] All prerequisites verified"

# =========================================
# IAM PATCHES
# =========================================
echo ""
echo "=========================================="
echo " IAM PATCHES"
echo "=========================================="

ACCOUNT_ID=$(aws sts get-caller-identity \
  --query 'Account' --output text)

SQS_QUEUE_ARN=$(aws sqs get-queue-attributes \
  --queue-url "$SQS_URL" --attribute-names QueueArn \
  --query 'Attributes.QueueArn' --output text)

# Patch 1 -- SQS interruption queue access
aws iam put-role-policy \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --policy-name "KarpenterSQSInterruption" \
  --policy-document "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Effect\": \"Allow\",
      \"Action\": [
        \"sqs:GetQueueUrl\",
        \"sqs:GetQueueAttributes\",
        \"sqs:ReceiveMessage\",
        \"sqs:DeleteMessage\"
      ],
      \"Resource\": \"${SQS_QUEUE_ARN}\"
    }]
  }"
echo "  [OK] SQS permissions patched"

# Patch 2 -- EC2 launch permissions for Karpenter v1
aws iam put-role-policy \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --policy-name "KarpenterV1EC2Launch" \
  --policy-document "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [
      {
        \"Sid\": \"RunInstances\",
        \"Effect\": \"Allow\",
        \"Action\": [\"ec2:RunInstances\", \"ec2:CreateFleet\"],
        \"Resource\": \"*\"
      },
      {
        \"Sid\": \"TagInstances\",
        \"Effect\": \"Allow\",
        \"Action\": [\"ec2:CreateTags\", \"ec2:TerminateInstances\"],
        \"Resource\": \"*\",
        \"Condition\": {
          \"StringEquals\": {
            \"aws:ResourceTag/kubernetes.io/cluster/${CLUSTER_NAME}\": \"owned\"
          }
        }
      },
      {
        \"Sid\": \"PassRole\",
        \"Effect\": \"Allow\",
        \"Action\": \"iam:PassRole\",
        \"Resource\": \"arn:aws:iam::${ACCOUNT_ID}:role/${CLUSTER_NAME}-karpenter-node\"
      },
      {
        \"Sid\": \"DescribeEC2\",
        \"Effect\": \"Allow\",
        \"Action\": [
          \"ec2:DescribeInstances\",
          \"ec2:DescribeInstanceTypes\",
          \"ec2:DescribeInstanceTypeOfferings\",
          \"ec2:DescribeAvailabilityZones\",
          \"ec2:DescribeImages\",
          \"ec2:DescribeSpotPriceHistory\",
          \"ec2:DescribeSecurityGroups\",
          \"ec2:DescribeSubnets\",
          \"ec2:DescribeVpcs\"
        ],
        \"Resource\": \"*\"
      },
      {
        \"Sid\": \"SSMGetParameter\",
        \"Effect\": \"Allow\",
        \"Action\": \"ssm:GetParameter\",
        \"Resource\": \"arn:aws:ssm:*:*:parameter/aws/service/eks/optimized-ami/*\"
      },
      {
        \"Sid\": \"Pricing\",
        \"Effect\": \"Allow\",
        \"Action\": \"pricing:GetProducts\",
        \"Resource\": \"*\"
      }
    ]
  }"
echo "  [OK] EC2 launch permissions patched"

# Patch 3 -- Launch template management
aws iam put-role-policy \
  --role-name "${CLUSTER_NAME}-karpenter-controller" \
  --policy-name "KarpenterV1LaunchTemplate" \
  --policy-document "{
    \"Version\": \"2012-10-17\",
    \"Statement\": [{
      \"Effect\": \"Allow\",
      \"Action\": [
        \"ec2:CreateLaunchTemplate\",
        \"ec2:DeleteLaunchTemplate\",
        \"ec2:DescribeLaunchTemplates\"
      ],
      \"Resource\": \"*\"
    }]
  }"
echo "  [OK] Launch template permissions patched"

# =========================================
# KARPENTER
# =========================================
echo ""
echo "=========================================="
echo " KARPENTER"
echo "=========================================="

CLUSTER_ENDPOINT=$(aws eks describe-cluster \
  --name "$CLUSTER_NAME" --region "$REGION" \
  --query "cluster.endpoint" --output text)

refresh_kubeconfig
echo "==> Cleaning up before install"
kubectl delete ec2nodeclass default --ignore-not-found --wait=false 2>/dev/null || true
kubectl delete nodepool   default --ignore-not-found --wait=false 2>/dev/null || true
echo "  Waiting for EC2NodeClass and NodePool to fully terminate"
for i in $(seq 1 6); do
  NC_EXISTS=$( { kubectl get ec2nodeclass default --no-headers 2>/dev/null || true; } | wc -l | tr -d ' ')
  NP_EXISTS=$( { kubectl get nodepool default --no-headers 2>/dev/null || true; } | wc -l | tr -d ' ')
  echo "  [$(( i * 5 ))s] ec2nodeclass=${NC_EXISTS} nodepool=${NP_EXISTS}"
  if [[ "$NC_EXISTS" -eq "0" && "$NP_EXISTS" -eq "0" ]]; then
    echo "  [OK] Objects fully terminated"
    break
  fi
  sleep 5
done
echo "  Force-removing finalizers if objects still stuck"
kubectl patch ec2nodeclass default \
  --type=json \
  -p='[{"op":"remove","path":"/metadata/finalizers"}]' \
  2>/dev/null || true
kubectl patch nodepool default \
  --type=json \
  -p='[{"op":"remove","path":"/metadata/finalizers"}]' \
  2>/dev/null || true
echo "  Waiting 10s after finalizer removal"
sleep 10
NC_EXISTS=$( { kubectl get ec2nodeclass default --no-headers 2>/dev/null || true; } | wc -l | tr -d ' ')
NP_EXISTS=$( { kubectl get nodepool default --no-headers 2>/dev/null || true; } | wc -l | tr -d ' ')
echo "  Final state: ec2nodeclass=${NC_EXISTS} nodepool=${NP_EXISTS}"


KSTATUS=$(helm status karpenter -n kube-system \
  --output json 2>/dev/null \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['info']['status'])" \
  2>/dev/null || echo "not-found")
[[ "$KSTATUS" != "not-found" ]] && {
  echo "  Uninstalling karpenter"
  helm uninstall karpenter -n kube-system --wait=false 2>/dev/null || true
  sleep 10
}

echo "  Installing karpenter"
helm install karpenter \
  "oci://public.ecr.aws/karpenter/karpenter" \
  -n kube-system \
  --version "${KARPENTER_VERSION}" \
  --set serviceAccount.create=false \
  --set serviceAccount.name=karpenter \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.clusterEndpoint=${CLUSTER_ENDPOINT}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}-karpenter" \
  --set "tolerations[0].key=CriticalAddonsOnly" \
  --set "tolerations[0].operator=Exists" \
  --set "tolerations[0].effect=NoSchedule" \
  --set "controller.resources.requests.cpu=100m" \
  --set "controller.resources.requests.memory=256Mi" \
  --set "controller.resources.limits.cpu=500m" \
  --set "controller.resources.limits.memory=512Mi"

# ---------------------------------------------------------
# FIX: kubectl wait exits 1 when pods are replaced mid-wait
# Use a polling loop instead -- tolerates pod churn
# ---------------------------------------------------------
refresh_kubeconfig
echo "  Waiting for Karpenter pods to be Ready"
KARP_READY=false
for i in $(seq 1 30); do
  KARP_TOTAL=$(kubectl get pods -n kube-system \
    -l app.kubernetes.io/name=karpenter \
    --no-headers 2>/dev/null | wc -l | tr -d ' ')
  KARP_READY_COUNT=$(kubectl get pods -n kube-system \
    -l app.kubernetes.io/name=karpenter \
    --no-headers 2>/dev/null \
    | awk '$3=="Running" {
        split($2,a,"/")
        if (a[1]==a[2] && a[1]+0>0) count++
      }
      END { print count+0 }')
  echo "  [$(( i * 10 ))s] karpenter total=${KARP_TOTAL} ready=${KARP_READY_COUNT}"
  if [[ "$KARP_TOTAL" -gt "0" && "$KARP_READY_COUNT" -eq "$KARP_TOTAL" ]]; then
    KARP_READY=true
    break
  fi
  sleep 10
done
if [[ "$KARP_READY" == "false" ]]; then
  echo "  [FAIL] Karpenter pods did not become Ready"
  kubectl describe pod -n kube-system \
    -l app.kubernetes.io/name=karpenter
  exit 1
fi
echo "  [OK] Karpenter Ready"

echo "  Waiting 90s for webhook registration"
sleep 90

refresh_kubeconfig

EC2NC_FILE=$(mktemp /tmp/ec2nodeclass-XXXXXX.yaml)
printf 'apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  instanceProfile: "%s-karpenter-node"
  amiSelectorTerms:
    - alias: al2@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "%s"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "%s"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
' "$CLUSTER_NAME" "$CLUSTER_NAME" "$CLUSTER_NAME" > "$EC2NC_FILE"

echo "==> EC2NodeClass manifest:"
cat "$EC2NC_FILE"
kubectl apply -f "$EC2NC_FILE"
rm -f "$EC2NC_FILE"

NP_FILE=$(mktemp /tmp/nodepool-XXXXXX.yaml)
printf 'apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium", "t3a.medium", "t3.large", "t3.xlarge"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["%sa", "%sb"]
  limits:
    cpu: "16"
    memory: 32Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
' "$REGION" "$REGION" > "$NP_FILE"

echo "==> NodePool manifest:"
cat "$NP_FILE"
kubectl apply -f "$NP_FILE"
rm -f "$NP_FILE"

echo "==> Waiting for EC2NodeClass Ready=True"
EC2_READY=false
for i in $(seq 1 18); do
  NC_STATUS=$(kubectl get ec2nodeclass default \
    -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' \
    2>/dev/null || echo "Unknown")
  echo "  [$(( i * 10 ))s] Ready=${NC_STATUS}"
  [[ "$NC_STATUS" == "True" ]] && { EC2_READY=true; break; }
  sleep 10
done
[[ "$EC2_READY" == "false" ]] && {
  kubectl describe ec2nodeclass default; exit 1
}
echo "  [OK] EC2NodeClass Ready"
kubectl get nodepool default
sleep 20

# =========================================
# STORAGE
# =========================================
echo ""
echo "=========================================="
echo " STORAGE"
echo "=========================================="

refresh_kubeconfig
kubectl wait pod -n kube-system \
  -l app.kubernetes.io/name=aws-ebs-csi-driver \
  --for=condition=Ready --timeout=120s \
  && echo "  [OK] EBS CSI Ready" || echo "  [WARN] EBS CSI check failed"

kubectl get storageclass gp3 &>/dev/null || kubectl apply -f - <<'YAMLEOF'
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
YAMLEOF

kubectl patch storageclass gp2 \
  -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}' \
  2>/dev/null || true
kubectl get storageclass

# =========================================
# NAMESPACE CLEANUP
# =========================================
echo ""
echo "=========================================="
echo " NAMESPACE CLEANUP"
echo "=========================================="

refresh_kubeconfig
for release in kube-prometheus-stack elasticsearch kibana \
               otel-collector jaeger fluent-bit; do
  STATUS=$(helm status "$release" -n "$OBS_NAMESPACE" \
    --output json 2>/dev/null \
    | python3 -c "import sys,json; \
        print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")
  [[ "$STATUS" != "not-found" ]] && {
    echo "  Uninstalling $release"
    helm uninstall "$release" -n "$OBS_NAMESPACE" \
      --wait=false 2>/dev/null || true
  }
done

kubectl delete pvc --all -n "$OBS_NAMESPACE" \
  --wait=false 2>/dev/null || true
kubectl delete mutatingwebhookconfiguration \
  kube-prometheus-stack-admission \
  --wait=false 2>/dev/null || true
kubectl delete validatingwebhookconfiguration \
  kube-prometheus-stack-admission \
  --wait=false 2>/dev/null || true

echo "  Waiting 15s for cleanup to settle"
sleep 15
kubectl create namespace "$OBS_NAMESPACE" \
  --dry-run=client -o yaml | kubectl apply -f -

# =========================================
# NAMESPACE QUOTA VERIFICATION
# =========================================
echo ""
echo "=========================================="
echo " NAMESPACE QUOTA VERIFICATION"
echo "=========================================="

QUOTA_COUNT=$(kubectl get resourcequota -n "$OBS_NAMESPACE" \
  --no-headers 2>/dev/null | wc -l | tr -d ' ')
LIMIT_COUNT=$(kubectl get limitrange -n "$OBS_NAMESPACE" \
  --no-headers 2>/dev/null | wc -l | tr -d ' ')

echo "  ResourceQuotas : $QUOTA_COUNT"
echo "  LimitRanges    : $LIMIT_COUNT"
kubectl get resourcequota -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get limitrange    -n "$OBS_NAMESPACE" 2>/dev/null || true

if [[ "$QUOTA_COUNT" -gt "0" && "$LIMIT_COUNT" -eq "0" ]]; then
  echo "  [FAIL] ResourceQuota exists but NO LimitRange found"
  echo "         Fix: push 05-namespaces.tf and run stage2-apply first"
  kubectl describe resourcequota -n "$OBS_NAMESPACE" 2>/dev/null || true
  exit 1
fi
echo "  [OK] Namespace quota configuration OK -- proceeding"

# =========================================
# KARPENTER NODE PROVISIONING DIAGNOSTIC
# =========================================
echo ""
echo "=========================================="
echo " KARPENTER NODE PROVISIONING DIAGNOSTIC"
echo "=========================================="

refresh_kubeconfig
echo "==> Deploying test pod to trigger Karpenter provisioning"

TEST_POD_FILE=$(mktemp /tmp/karpenter-test-XXXXXX.yaml)
printf 'apiVersion: v1
kind: Pod
metadata:
  name: karpenter-test
  namespace: %s
  labels:
    app: karpenter-test
spec:
  containers:
    - name: pause
      image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
' "$OBS_NAMESPACE" > "$TEST_POD_FILE"

kubectl apply -f "$TEST_POD_FILE"
rm -f "$TEST_POD_FILE"

echo "==> Waiting 15s for Karpenter to detect Pending pod"
sleep 15

echo ""
echo "==> NodeClaim status:"
kubectl get nodeclaims 2>/dev/null || echo "  no nodeclaims yet"

echo ""
echo "==> Test pod status:"
kubectl get pod karpenter-test -n "$OBS_NAMESPACE" -o wide 2>/dev/null || true

echo ""
echo "==> Karpenter logs -- provisioning attempt:"
kubectl logs -n kube-system \
  -l app.kubernetes.io/name=karpenter \
  --all-containers \
  --since=3m 2>/dev/null \
  | grep -i \
    "launch\|provision\|nodeclaim\|error\|denied\|failed\|instance\|ec2\|fleet\|access\|unauthorized\|forbidden\|capacity\|subnet\|security" \
  || echo "  no matching log lines"

echo ""
echo "==> Polling NodeClaim for up to 5 min"
echo "    Empty TYPE/CAPACITY/ZONE/NODE  = EC2 never launched (IAM issue)"
echo "    TYPE+ZONE filled, NODE empty   = EC2 launched, node not joining"
echo "    All fields filled              = node joined successfully"
echo ""

NC_RESOLVED=false
for i in $(seq 1 30); do
  (( i == 15 )) && refresh_kubeconfig

  echo "  --- [$(( i * 10 ))s] ---"
  kubectl get nodeclaims \
    -o custom-columns="NAME:.metadata.name,TYPE:.status.allocatable.cpu,CAPACITY:.metadata.labels.karpenter\.sh/capacity-type,ZONE:.metadata.labels.topology\.kubernetes\.io/zone,NODE:.status.nodeName,READY:.status.conditions[?(@.type=='Ready')].status" \
    2>/dev/null || true

  NODE_NAME=$(kubectl get nodeclaims \
    -o jsonpath='{.items[0].status.nodeName}' \
    2>/dev/null || echo "")

  if [[ -n "$NODE_NAME" ]]; then
    echo ""
    echo "  [OK] Node joined: $NODE_NAME"
    NC_RESOLVED=true
    break
  fi

  if (( i % 3 == 0 )); then
    echo ""
    echo "  --- Karpenter logs (last 30s) ---"
    kubectl logs -n kube-system \
      -l app.kubernetes.io/name=karpenter \
      --all-containers \
      --since=30s 2>/dev/null \
      | grep -i \
        "launch\|provision\|nodeclaim\|error\|denied\|failed\|instance\|ec2\|fleet\|access\|unauthorized\|forbidden\|capacity\|subnet\|security\|launched\|registered" \
      || echo "  (no matching lines)"
    echo ""
  fi

  sleep 10
done

echo ""
echo "==> NodeClaim full description:"
kubectl describe nodeclaims 2>/dev/null || echo "  no nodeclaims"

echo ""
echo "==> Full Karpenter logs since test pod created:"
kubectl logs -n kube-system \
  -l app.kubernetes.io/name=karpenter \
  --all-containers \
  --since=8m 2>/dev/null \
  | grep -v "^$" \
  || echo "  no logs"

echo ""
echo "==> Test pod events:"
kubectl describe pod karpenter-test \
  -n "$OBS_NAMESPACE" 2>/dev/null \
  | grep -A 20 "Events:" || true

echo ""
echo "==> Cleaning up test pod"
kubectl delete pod karpenter-test -n "$OBS_NAMESPACE" \
  --ignore-not-found --wait=false 2>/dev/null || true

if [[ "$NC_RESOLVED" == "true" ]]; then
  echo ""
  echo "  [OK] KARPENTER NODE PROVISIONING WORKS"
  echo "       Proceeding with observability stack"
else
  echo ""
  echo "  [FAIL] KARPENTER NODE PROVISIONING FAILED"
  echo "         Review logs above for exact error"
  exit 1
fi

# =========================================
# OBSERVABILITY STACK
# =========================================
echo ""
echo "=========================================="
echo " OBSERVABILITY STACK"
echo "=========================================="

refresh_kubeconfig
echo "==> Deploying kube-prometheus-stack"
helm install kube-prometheus-stack \
  prometheus-community/kube-prometheus-stack \
  -n "$OBS_NAMESPACE" \
  --version 58.2.2 \
  --timeout 30m \
  --set prometheusOperator.admissionWebhooks.enabled=false \
  --set prometheusOperator.admissionWebhooks.patch.enabled=false \
  --set prometheusOperator.admissionWebhooks.certManager.enabled=false \
  --set prometheusOperator.tls.enabled=false \
  --set "grafana.adminPassword=${GRAFANA_PASSWORD}" \
  --set grafana.persistence.enabled=true \
  --set grafana.persistence.storageClassName=gp3 \
  --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName=gp3 \
  --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=20Gi \
  --set prometheus.prometheusSpec.retention=30d

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "kube-prometheus-stack" 1800

refresh_kubeconfig
echo "==> Deploying elasticsearch"
helm install elasticsearch elastic/elasticsearch \
  -n "$OBS_NAMESPACE" --version 8.5.1 --timeout 15m \
  --set replicas=1 \
  --set minimumMasterNodes=1 \
  --set esJavaOpts="-Xmx512m -Xms512m" \
  --set resources.requests.cpu=500m \
  --set resources.requests.memory=1Gi \
  --set resources.limits.cpu=1000m \
  --set resources.limits.memory=1Gi \
  --set sysctlInitContainer.enabled=true \
   --set sysctlVmMaxMapCount=262144 \
  --set volumeClaimTemplate.storageClassName=gp3 \
  --set volumeClaimTemplate.resources.requests.storage=10Gi \
  --set "esConfig.elasticsearch\\.yml=xpack.security.enabled: false\nxpack.ml.enabled: false\n"

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "elasticsearch" 900

refresh_kubeconfig
echo "==> Deploying kibana"
helm install kibana elastic/kibana \
  -n "$OBS_NAMESPACE" --version 8.5.1 --timeout 10m \
  --set "elasticsearchHosts=http://elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local:9200"

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "kibana" 600

refresh_kubeconfig
echo "==> Deploying otel-collector"
helm install otel-collector \
  open-telemetry/opentelemetry-collector \
  -n "$OBS_NAMESPACE" --version 0.91.0 --timeout 5m \
  --set mode=deployment \
  --set image.repository=otel/opentelemetry-collector-contrib

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "otel-collector" 300

refresh_kubeconfig
echo "==> Deploying jaeger"
helm install jaeger jaegertracing/jaeger \
  -n "$OBS_NAMESPACE" --version 3.0.0 --timeout 5m \
  --set provisionDataStore.cassandra=false \
  --set provisionDataStore.elasticsearch=false \
  --set storage.type=elasticsearch \
  --set "storage.elasticsearch.host=elasticsearch-master.${OBS_NAMESPACE}.svc.cluster.local" \
  --set storage.elasticsearch.port=9200 \
  --set agent.enabled=false

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "jaeger" 300

refresh_kubeconfig
echo "==> Deploying fluent-bit"
helm install fluent-bit fluent/fluent-bit \
  -n "$OBS_NAMESPACE" --version 0.46.7 --timeout 5m

echo "==> State 15s after helm install:"
sleep 15
kubectl get all    -n "$OBS_NAMESPACE" 2>/dev/null || true
kubectl get events -n "$OBS_NAMESPACE" \
  --sort-by='.lastTimestamp' 2>/dev/null | tail -10 || true
wait_for_pods "$OBS_NAMESPACE" "fluent-bit" 300

# =========================================
# SUMMARY
# =========================================
echo ""
echo "=========================================="
echo " DEPLOYMENT COMPLETE"
echo "=========================================="

echo "Observability releases:"
for release in kube-prometheus-stack elasticsearch kibana \
               otel-collector jaeger fluent-bit; do
  STATUS=$(helm status "$release" -n "$OBS_NAMESPACE" \
    --output json 2>/dev/null \
    | python3 -c "import sys,json; \
        print(json.load(sys.stdin)['info']['status'])" \
    2>/dev/null || echo "not-found")
  printf "  %-30s %s\n" "$release" "$STATUS"
done

echo ""
echo "Nodes:"
kubectl get nodes --no-headers \
  | awk '{printf "  %-40s %s\n", $1, $2}'

echo ""
echo "PVCs:"
kubectl get pvc -n "$OBS_NAMESPACE" 2>/dev/null || echo "  none"

echo ""
echo "Pods:"
kubectl get pods -n "$OBS_NAMESPACE" --no-headers \
  | awk '{printf "  %-50s %-15s %s\n", $1, $3, $2}'
echo ""
