# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/delete/redis_tracker.py
"""
Thin wrapper around redis.asyncio that records latency and errors.

    from shared.delete.redis_tracker import TrackedRedis
    redis = TrackedRedis(await aioredis.from_url(...), service="payment-router")
    value = await redis.get("route:SBI")
"""

import time
import redis.asyncio as aioredis

from .registry import REDIS_OP_LATENCY_SECONDS, REDIS_ERRORS_TOTAL


class TrackedRedis:
    def __init__(self, client: aioredis.Redis, service: str):
        self._r       = client
        self._service = service

    async def _call(self, operation: str, coro):
        start = time.perf_counter()
        try:
            result = await coro
            return result
        except Exception as exc:
            REDIS_ERRORS_TOTAL.labels(
                service    = self._service,
                error_type = type(exc).__name__,
            ).inc()
            raise
        finally:
            REDIS_OP_LATENCY_SECONDS.labels(
                service   = self._service,
                operation = operation,
            ).observe(time.perf_counter() - start)

    async def get(self, key: str):
        return await self._call("GET", self._r.get(key))

    async def set(self, key: str, value, ex: int = None):
        return await self._call("SET", self._r.set(key, value, ex=ex))

    async def delete(self, *keys: str):
        return await self._call("DEL", self._r.delete(*keys))

    async def exists(self, *keys: str):
        return await self._call("EXISTS", self._r.exists(*keys))

    async def expire(self, key: str, seconds: int):
        return await self._call("EXPIRE", self._r.expire(key, seconds))
