# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/services/adapter_service.py

import time
import httpx
import structlog
import pybreaker

from app.models import AdapterRequest, AdapterResponse
from app.config import settings
from app.transformers.transformer_factory import get_transformer
from app.circuit_breaker.breaker_registry import get_breaker
from shared.metrics.registry import (              # ← NEW
    BANK_REQUESTS_TOTAL,
    BANK_REQUEST_LATENCY_SECONDS,
    BANK_FAILURES_TOTAL,
    BANK_FALLBACK_USED_TOTAL,
    CIRCUIT_BREAKER_REJECTED_TOTAL,
)

logger = structlog.get_logger()


class AdapterService:

    async def send(self, req: AdapterRequest) -> AdapterResponse:
        breaker     = get_breaker(req.bankCode)
        transformer = get_transformer(req.bankCode)
        payload     = transformer.to_bank_payload(req)
        start_ms    = int(time.time() * 1000)
        attempts    = 0

        # ── PRIMARY ────────────────────────────────────────────────────────────
        try:
            attempts += 1
            raw = await self._post(
                req.primaryEndpoint,
                payload,
                settings.primary_timeout_seconds,
                breaker,
                bank_code     = req.bankCode,
                endpoint_type = "primary",          # ← METRIC label
            )
            normalized = transformer.from_bank_response(raw)
            if normalized["status"] == "SUCCESS":
                logger.info("primary_success", txn=req.transactionId,
                            bank=req.bankCode)
                return AdapterResponse(
                    transactionId   = req.transactionId,
                    bankCode        = req.bankCode,
                    status          = "SUCCESS",
                    bankReferenceId = normalized["bankReferenceId"],
                    resolvedVia     = "PRIMARY",
                    attempts        = attempts,
                    responseTimeMs  = int(time.time() * 1000) - start_ms,
                )
            raise ValueError(f"Bank returned non-success: {normalized}")

        except pybreaker.CircuitBreakerError:
            CIRCUIT_BREAKER_REJECTED_TOTAL.labels(              # ← METRIC
                bank_code=req.bankCode
            ).inc()
            logger.warning("circuit_open", bankCode=req.bankCode)
            return self._failed(req, start_ms, attempts,
                                "CIRCUIT_OPEN",
                                f"Circuit breaker open for {req.bankCode}")

        except (httpx.HTTPStatusError, httpx.TimeoutException,
                httpx.ConnectError, ValueError) as primary_err:
            logger.warning("primary_failed", txn=req.transactionId,
                           bank=req.bankCode, error=str(primary_err))
            if (isinstance(primary_err, httpx.HTTPStatusError)
                    and primary_err.response.status_code < 500):
                return self._failed(req, start_ms, attempts,
                                    "CLIENT_ERROR", str(primary_err))

        # ── FALLBACK ───────────────────────────────────────────────────────────
        BANK_FALLBACK_USED_TOTAL.labels(bank_code=req.bankCode).inc()  # ← METRIC
        logger.info("trying_fallback", txn=req.transactionId,
                    bank=req.bankCode)

        try:
            attempts += 1
            raw = await self._post(
                req.fallbackEndpoint,
                payload,
                settings.fallback_timeout_seconds,
                breaker,
                bank_code     = req.bankCode,
                endpoint_type = "fallback",         # ← METRIC label
            )
            normalized = transformer.from_bank_response(raw)
            if normalized["status"] == "SUCCESS":
                logger.info("fallback_success", txn=req.transactionId,
                            bank=req.bankCode)
                return AdapterResponse(
                    transactionId   = req.transactionId,
                    bankCode        = req.bankCode,
                    status          = "SUCCESS",
                    bankReferenceId = normalized["bankReferenceId"],
                    resolvedVia     = "FALLBACK",
                    attempts        = attempts,
                    responseTimeMs  = int(time.time() * 1000) - start_ms,
                )
            raise ValueError(f"Fallback non-success: {normalized}")

        except pybreaker.CircuitBreakerError:
            CIRCUIT_BREAKER_REJECTED_TOTAL.labels(              # ← METRIC
                bank_code=req.bankCode
            ).inc()
            logger.warning("circuit_open_fallback", bankCode=req.bankCode)
            return self._failed(req, start_ms, attempts,
                                "CIRCUIT_OPEN",
                                f"Circuit breaker open for {req.bankCode}")

        except Exception as fallback_err:
            BANK_FAILURES_TOTAL.labels(                         # ← METRIC
                bank_code    = req.bankCode,
                failure_type = "both_failed",
            ).inc()
            logger.error("fallback_failed", txn=req.transactionId,
                         bank=req.bankCode, error=str(fallback_err))
            return self._failed(req, start_ms, attempts,
                                "BANK_UNREACHABLE",
                                "Both primary and fallback failed")

    # ── Helpers ────────────────────────────────────────────────────────────────
    async def _post(
        self,
        url:           str,
        payload:       dict,
        timeout:       float,
        breaker:       pybreaker.CircuitBreaker,
        bank_code:     str,                        # ← NEW for metrics
        endpoint_type: str,                        # ← NEW for metrics
    ) -> dict:
        start = time.perf_counter()
        code  = "error"

        async with httpx.AsyncClient(timeout=timeout) as client:
            try:
                resp = await client.post(url, json=payload)
                code = str(resp.status_code)
                resp.raise_for_status()

                BANK_REQUESTS_TOTAL.labels(                     # ← METRIC
                    bank_code     = bank_code,
                    endpoint_type = endpoint_type,
                    http_code     = code,
                ).inc()

                data = resp.json()
                breaker.call(lambda: None)   # register success
                return data

            except httpx.TimeoutException as exc:
                BANK_REQUESTS_TOTAL.labels(                     # ← METRIC
                    bank_code=bank_code, endpoint_type=endpoint_type, http_code="timeout"
                ).inc()
                BANK_FAILURES_TOTAL.labels(                     # ← METRIC
                    bank_code=bank_code, failure_type="timeout"
                ).inc()
                captured = exc
                try:
                    breaker.call(lambda: (_ for _ in ()).throw(captured))
                except pybreaker.CircuitBreakerError:
                    raise
                except Exception:
                    pass
                raise

            except httpx.HTTPStatusError as exc:
                BANK_REQUESTS_TOTAL.labels(                     # ← METRIC
                    bank_code     = bank_code,
                    endpoint_type = endpoint_type,
                    http_code     = str(exc.response.status_code),
                ).inc()
                BANK_FAILURES_TOTAL.labels(                     # ← METRIC
                    bank_code=bank_code, failure_type="http_error"
                ).inc()
                captured = exc
                try:
                    breaker.call(lambda: (_ for _ in ()).throw(captured))
                except pybreaker.CircuitBreakerError:
                    raise
                except Exception:
                    pass
                raise

            except httpx.ConnectError as exc:
                BANK_REQUESTS_TOTAL.labels(                     # ← METRIC
                    bank_code=bank_code, endpoint_type=endpoint_type, http_code="connection_error"
                ).inc()
                BANK_FAILURES_TOTAL.labels(                     # ← METRIC
                    bank_code=bank_code, failure_type="connection"
                ).inc()
                captured = exc
                try:
                    breaker.call(lambda: (_ for _ in ()).throw(captured))
                except pybreaker.CircuitBreakerError:
                    raise
                except Exception:
                    pass
                raise

            finally:
                BANK_REQUEST_LATENCY_SECONDS.labels(            # ← METRIC (always)
                    bank_code     = bank_code,
                    endpoint_type = endpoint_type,
                ).observe(time.perf_counter() - start)

    def _failed(
        self, req: AdapterRequest, start_ms: int,
        attempts: int, code: str, msg: str,
    ) -> AdapterResponse:
        return AdapterResponse(
            transactionId  = req.transactionId,
            bankCode       = req.bankCode,
            status         = "FAILED",
            resolvedVia    = "NONE",
            attempts       = attempts,
            responseTimeMs = int(time.time() * 1000) - start_ms,
            errorCode      = code,
            errorMessage   = msg,
        )
