# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/patch.ps1

$EndpointUrl = "http://localhost:4566"
$Region      = "ap-south-1"
$Table       = "routing-table"

$patches = @(
    @{
        bankCode         = "SBI"
        primaryEndpoint  = "http://mock-bank-server:8080/mock/sbi/txn"
        fallbackEndpoint = "http://mock-bank-server:8080/mock/sbi/txn/fallback"
    },
    @{
        bankCode         = "HDFC"
        primaryEndpoint  = "http://mock-bank-server:8080/mock/hdfc/txn"
        fallbackEndpoint = "http://mock-bank-server:8080/mock/hdfc/txn/fallback"
    },
    @{
        bankCode         = "ICICI"
        primaryEndpoint  = "http://mock-bank-server:8080/mock/icici/txn"
        fallbackEndpoint = "http://mock-bank-server:8080/mock/icici/txn/fallback"
    }
)

foreach ($p in $patches) {
    Write-Host "Patching $($p.bankCode)..." -ForegroundColor Cyan

    $keyPath  = [System.IO.Path]::GetTempFileName()
    $attrPath = [System.IO.Path]::GetTempFileName()

    $keyJson  = '{"bankCode":{"S":"' + $p.bankCode + '"}}'
    $attrJson = '{":p":{"S":"' + $p.primaryEndpoint + '"},":f":{"S":"' + $p.fallbackEndpoint + '"}}'

    # BOM-free UTF-8 write
    [System.IO.File]::WriteAllText($keyPath,  $keyJson)
    [System.IO.File]::WriteAllText($attrPath, $attrJson)

    aws dynamodb update-item `
      --table-name        $Table `
      --endpoint-url      $EndpointUrl `
      --region            $Region `
      --key               "file://$keyPath" `
      --update-expression "SET primaryEndpoint = :p, fallbackEndpoint = :f" `
      --expression-attribute-values "file://$attrPath" `
      --no-cli-pager

    Remove-Item $keyPath, $attrPath -Force

    if ($LASTEXITCODE -eq 0) {
        Write-Host "  [PASS] $($p.bankCode) patched`n" -ForegroundColor Green
    } else {
        Write-Host "  [FAIL] $($p.bankCode) failed`n" -ForegroundColor Red
        exit 1
    }
}

# Verify SBI
Write-Host "Verifying SBI..." -ForegroundColor Cyan
$keyPath = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($keyPath, '{"bankCode":{"S":"SBI"}}')

aws dynamodb get-item `
  --table-name   $Table `
  --endpoint-url $EndpointUrl `
  --region       $Region `
  --key          "file://$keyPath" `
  --query        "Item.{primary:primaryEndpoint.S,fallback:fallbackEndpoint.S}" `
  --no-cli-pager

Remove-Item $keyPath -Force
