# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/test-bank-adapter.ps1

param(
  [string]$AdapterUrl = "http://localhost:8082",
  [string]$RouterUrl  = "http://localhost:8081"
)

$pass = 0; $fail = 0

function Assert-Pass { param([string]$L) Write-Host "  [PASS] $L" -ForegroundColor Green;  $script:pass++ }
function Assert-Fail { param([string]$L, [string]$D="") Write-Host "  [FAIL] $L $D" -ForegroundColor Red; $script:fail++ }
function Test-Case   { param([string]$Id,[string]$Desc) Write-Host "`n[$Id] $Desc" -ForegroundColor Cyan }

function Invoke-Api {
    param([string]$Uri,[string]$Method="GET",[string]$Body=$null)
    $p = @{Uri=$Uri;Method=$Method;ContentType="application/json";ErrorAction="Stop"}
    if ($Body) { $p.Body = $Body }
    return Invoke-RestMethod @p
}

# T01
Test-Case "T01" "Health check"
try {
    $r = Invoke-Api -Uri "$AdapterUrl/actuator/health"
    if ($r.status -eq "UP") { Assert-Pass "status=UP" }
    else { Assert-Fail "Expected UP" $r.status }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T02
Test-Case "T02" "SBI primary success"
$body = '{"transactionId":"TXN-001","bankCode":"SBI","primaryEndpoint":"http://mock-bank-server:8080/mock/sbi/txn","fallbackEndpoint":"http://mock-bank-server:8080/mock/sbi/txn/fallback","amount":1000,"payerVpa":"john@sbi","payeeVpa":"merchant@sbi"}'
try {
    $r = Invoke-Api -Uri "$AdapterUrl/api/v1/adapter/send" -Method POST -Body $body
    if ($r.status -eq "SUCCESS" -and $r.resolvedVia -eq "PRIMARY" -and $r.attempts -eq 1) {
        Assert-Pass "SUCCESS via PRIMARY attempts=1 ref=$($r.bankReferenceId)"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T03
Test-Case "T03" "HDFC primary success"
$body = '{"transactionId":"TXN-002","bankCode":"HDFC","primaryEndpoint":"http://mock-bank-server:8080/mock/hdfc/txn","fallbackEndpoint":"http://mock-bank-server:8080/mock/hdfc/txn/fallback","amount":500,"payerVpa":"john@okhdfcbank","payeeVpa":"merchant@okhdfcbank"}'
try {
    $r = Invoke-Api -Uri "$AdapterUrl/api/v1/adapter/send" -Method POST -Body $body
    if ($r.status -eq "SUCCESS" -and $r.resolvedVia -eq "PRIMARY") {
        Assert-Pass "SUCCESS via PRIMARY ref=$($r.bankReferenceId)"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T04
Test-Case "T04" "ICICI primary 503 -> fallback success"
$body = '{"transactionId":"TXN-003","bankCode":"ICICI","primaryEndpoint":"http://mock-bank-server:8080/mock/icici/txn","fallbackEndpoint":"http://mock-bank-server:8080/mock/icici/txn/fallback","amount":250,"payerVpa":"john@okicici","payeeVpa":"merchant@okicici"}'
try {
    $r = Invoke-Api -Uri "$AdapterUrl/api/v1/adapter/send" -Method POST -Body $body
    if ($r.status -eq "SUCCESS" -and $r.resolvedVia -eq "FALLBACK" -and $r.attempts -eq 2) {
        Assert-Pass "SUCCESS via FALLBACK attempts=2 ref=$($r.bankReferenceId)"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T05
Test-Case "T05" "Both primary and fallback 503 -> FAILED"
$body = '{"transactionId":"TXN-004","bankCode":"SBI","primaryEndpoint":"http://mock-bank-server:8080/mock/sbi/txn/fail","fallbackEndpoint":"http://mock-bank-server:8080/mock/sbi/txn/fail/fallback","amount":100,"payerVpa":"john@sbi","payeeVpa":"merchant@sbi"}'
try {
    $r = Invoke-Api -Uri "$AdapterUrl/api/v1/adapter/send" -Method POST -Body $body
    if ($r.status -eq "FAILED" -and $r.errorCode -eq "BANK_UNREACHABLE" -and $r.attempts -eq 2) {
        Assert-Pass "FAILED errorCode=BANK_UNREACHABLE attempts=2"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T06
Test-Case "T06" "End-to-end: payment-router -> bank-adapter (john@sbi)"
$body = '{"transactionId":"TXN-E2E-001","payerVpa":"john@sbi","payeeVpa":"merchant@sbi","amount":750}'
try {
    $r = Invoke-Api -Uri "$RouterUrl/api/v1/payment/initiate" -Method POST -Body $body
    if ($r.status -eq "SUCCESS" -and $r.bankCode -eq "SBI") {
        Assert-Pass "E2E SUCCESS bankCode=SBI via=$($r.resolvedVia)"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T07
Test-Case "T07" "responseTimeMs populated and > 0"
$body = '{"transactionId":"TXN-005","bankCode":"SBI","primaryEndpoint":"http://mock-bank-server:8080/mock/sbi/txn","fallbackEndpoint":"http://mock-bank-server:8080/mock/sbi/txn/fallback","amount":1,"payerVpa":"a@sbi","payeeVpa":"b@sbi"}'
try {
    $r = Invoke-Api -Uri "$AdapterUrl/api/v1/adapter/send" -Method POST -Body $body
    if ($r.responseTimeMs -gt 0) { Assert-Pass "responseTimeMs=$($r.responseTimeMs)ms" }
    else { Assert-Fail "responseTimeMs not populated" }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# Summary
$total = $pass + $fail
Write-Host "`n======================================" -ForegroundColor White
Write-Host " RESULTS: $pass/$total passed" -ForegroundColor $(if ($fail -eq 0){"Green"}else{"Yellow"})
if ($fail -gt 0) { Write-Host " $fail test(s) FAILED" -ForegroundColor Red }
else             { Write-Host " All tests passed - bank-adapter healthy" -ForegroundColor Green }
Write-Host "======================================`n" -ForegroundColor White
