# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/shared/telemetry.py

import os
import logging

from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.resources import Resource, SERVICE_NAME
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter

logger = logging.getLogger(__name__)


def setup_telemetry() -> None:
    service_name = os.getenv("OTEL_SERVICE_NAME", "unknown-service")
    endpoint     = os.getenv(
        "OTEL_EXPORTER_OTLP_ENDPOINT",
        "http://ibts-otel-collector:4318"
    )
    exporter_env = os.getenv("OTEL_TRACES_EXPORTER", "none")

    resource = Resource.create({SERVICE_NAME: service_name})
    provider = TracerProvider(resource=resource)

    if exporter_env == "otlp":
        otlp_exporter = OTLPSpanExporter(
            endpoint=f"{endpoint}/v1/traces",
        )
        provider.add_span_processor(BatchSpanProcessor(otlp_exporter))
        logger.info("OTel tracing enabled -> %s/v1/traces", endpoint)
    else:
        logger.info("OTel tracing disabled (OTEL_TRACES_EXPORTER=%s)", exporter_env)

    trace.set_tracer_provider(provider)

    # ── FastAPI instrumentor (creates server-side spans)
    try:
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
        FastAPIInstrumentor().instrument()
        logger.info("FastAPIInstrumentor active")
    except Exception as e:
        logger.warning("FastAPIInstrumentor skipped: %s", e)

    # ── HTTPX instrumentor (propagates trace context between services)
    try:
        from opentelemetry.instrumentation.httpx import HTTPXClientInstrumentor
        HTTPXClientInstrumentor().instrument()
        logger.info("HTTPXClientInstrumentor active")
    except Exception as e:
        logger.warning("HTTPXClientInstrumentor skipped: %s", e)

    # ── Log correlation
    if os.getenv("OTEL_PYTHON_LOG_CORRELATION", "false").lower() == "true":
        try:
            from opentelemetry.instrumentation.logging import LoggingInstrumentor
            LoggingInstrumentor().instrument(set_logging_format=True)
            logger.info("LoggingInstrumentor active")
        except Exception as e:
            logger.warning("LoggingInstrumentor skipped: %s", e)
