# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/base_transformer.py

from abc import ABC, abstractmethod
from app.models import AdapterRequest

class BaseTransformer(ABC):
    @abstractmethod
    def to_bank_payload(self, req: AdapterRequest) -> dict:
        """Transform unified request to bank-specific payload."""

    @abstractmethod
    def from_bank_response(self, raw: dict) -> dict:
        """Normalize bank-specific response to unified format."""
