# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/default_transformer.py

from app.transformers.base_transformer import BaseTransformer
from app.models import AdapterRequest

class DefaultTransformer(BaseTransformer):
    """Fallback — used for banks without a custom transformer."""
    def to_bank_payload(self, req: AdapterRequest) -> dict:
        return {
            "transactionId": req.transactionId,
            "payerVpa":      req.payerVpa,
            "payeeVpa":      req.payeeVpa,
            "amount":        req.amount,
            "currency":      req.currency,
            "remarks":       req.remarks,
        }

    def from_bank_response(self, raw: dict) -> dict:
        return {
            "bankReferenceId": raw.get("referenceId") or raw.get("refId"),
            "status":          "SUCCESS" if raw.get("status") == "SUCCESS" else "FAILED",
        }
