# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/hdfc_transformer.py

from app.transformers.base_transformer import BaseTransformer
from app.models import AdapterRequest

class HdfcTransformer(BaseTransformer):
    def to_bank_payload(self, req: AdapterRequest) -> dict:
        return {
            "transRef":   req.transactionId,
            "debitVpa":   req.payerVpa,
            "creditVpa":  req.payeeVpa,
            "amount":     req.amount,
            "currCode":   req.currency,
            "narration":  req.remarks,
        }

    def from_bank_response(self, raw: dict) -> dict:
        return {
            "bankReferenceId": raw.get("hdfcRefId"),
            "status":          "SUCCESS" if raw.get("statusCode") == "0" else "FAILED",
        }
