# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/icici_transformer.py

from app.transformers.base_transformer import BaseTransformer
from app.models import AdapterRequest

class IciciTransformer(BaseTransformer):
    def to_bank_payload(self, req: AdapterRequest) -> dict:
        return {
            "msgId":      req.transactionId,
            "srcVpa":     req.payerVpa,
            "destVpa":    req.payeeVpa,
            "txnAmt":     req.amount,
            "ccy":        req.currency,
            "addInfo":    req.remarks,
        }

    def from_bank_response(self, raw: dict) -> dict:
        return {
            "bankReferenceId": raw.get("iciciBankRef"),
            "status":          "SUCCESS" if raw.get("txnStatus") == "SUCCESS" else "FAILED",
        }
