# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/sbi_transformer.py

from app.transformers.base_transformer import BaseTransformer
from app.models import AdapterRequest

class SbiTransformer(BaseTransformer):
    def to_bank_payload(self, req: AdapterRequest) -> dict:
        return {
            "txnId":      req.transactionId,
            "payerVpa":   req.payerVpa,
            "payeeVpa":   req.payeeVpa,
            "amt":        str(req.amount),
            "currency":   req.currency,
            "remarks":    req.remarks,
            "channel":    "UPI",
        }

    def from_bank_response(self, raw: dict) -> dict:
        return {
            "bankReferenceId": raw.get("sbiRefNo") or raw.get("refId"),
            "status":          "SUCCESS" if raw.get("respCode") == "00" else "FAILED",
        }
