# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: bank-adapter/app/transformers/transformer_factory.py

from app.transformers.base_transformer  import BaseTransformer
from app.transformers.sbi_transformer   import SbiTransformer
from app.transformers.hdfc_transformer  import HdfcTransformer
from app.transformers.icici_transformer import IciciTransformer
from app.transformers.default_transformer import DefaultTransformer

_REGISTRY: dict[str, BaseTransformer] = {
    "SBI":   SbiTransformer(),
    "HDFC":  HdfcTransformer(),
    "ICICI": IciciTransformer(),
}

def get_transformer(bank_code: str) -> BaseTransformer:
    return _REGISTRY.get(bank_code.upper(), DefaultTransformer())
