# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: shared/delete/registry.py
"""
Single source of truth for every Prometheus metric in IBTS.
All five Python services import from here — no metric is defined twice.
"""

from prometheus_client import Counter, Histogram, Gauge

# ── Label name constants ───────────────────────────────────────────────────────
L_SERVICE     = "service"        # api-gateway|payment-switch|payment-router|bank-adapter|idempotency
L_ENDPOINT    = "endpoint"       # route template  e.g. /api/v1/payments
L_METHOD      = "method"         # GET|POST
L_HTTP_CODE   = "http_code"      # 200|404|422|429|502
L_BANK        = "bank_code"      # SBI|HDFC|ICICI|YESBANK
L_PAYER_BANK  = "payer_bank"
L_PAYEE_BANK  = "payee_bank"
L_STATUS      = "status"         # SUCCESS|FAILED|CACHED
L_IDEM        = "idem_result"    # NEW|CACHED|STALE_PROCESSING
L_ROUTE_SRC   = "resolved_from"  # DB|CACHE
L_EP_TYPE     = "endpoint_type"  # primary|fallback
L_TRANSITION  = "transition"     # closed_to_open|open_to_half_open|...
L_OPERATION   = "operation"      # GET|SET|DEL / GetItem|PutItem|...
L_TABLE       = "table"          # routing-table|idempotency-records
L_ERROR_KIND  = "error_kind"     # validation|routing|bank_error|timeout|unknown
L_FAIL_TYPE   = "failure_type"   # http_error|timeout|connection|both_failed

# ==============================================================================
# HTTP Layer  (all services)
# ==============================================================================

HTTP_REQUESTS_TOTAL = Counter(
    "ibts_http_requests_total",
    "Total HTTP requests received, labelled by service/endpoint/method/code.",
    [L_SERVICE, L_ENDPOINT, L_METHOD, L_HTTP_CODE],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "ibts_http_request_duration_seconds",
    "End-to-end HTTP request latency at each service. SLA: p99 < 2 s.",
    [L_SERVICE, L_ENDPOINT, L_METHOD, L_HTTP_CODE],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0),
)

HTTP_REQUESTS_IN_FLIGHT = Gauge(
    "ibts_http_requests_in_flight",
    "Requests currently being processed (concurrency).",
    [L_SERVICE, L_ENDPOINT],
)

# ==============================================================================
# Auth + Rate Limiting  (api-gateway only)
# ==============================================================================

AUTH_FAILURES_TOTAL = Counter(
    "ibts_auth_failures_total",
    "Requests rejected for missing/invalid API key (401/403). "
    "Spike = key rotation issue or scanning attempt.",
    [L_SERVICE, "reason"],          # reason: missing_key | invalid_key
)

RATE_LIMIT_HITS_TOTAL = Counter(
    "ibts_rate_limit_hits_total",
    "Requests rejected by IP rate limiter (429).",
    [L_SERVICE, "client_ip"],
)

RATE_LIMIT_REMAINING = Gauge(
    "ibts_rate_limit_window_remaining_requests",
    "Remaining quota in current window for the last seen client IP.",
    [L_SERVICE],
)

# ==============================================================================
# Payment Business Metrics  (payment-switch)
# ==============================================================================

PAYMENT_INITIATED_TOTAL = Counter(
    "ibts_payment_initiated_total",
    "Payments initiated by final status and both bank codes. "
    "Core volume metric — alert on drop > 20 %.",
    [L_PAYER_BANK, L_PAYEE_BANK, L_STATUS, L_IDEM],
)

PAYMENT_AMOUNT_PAISE = Histogram(
    "ibts_payment_amount_paise",
    "Distribution of transaction amounts (100 paise = 1 INR).",
    [L_PAYER_BANK, L_PAYEE_BANK, L_STATUS],
    buckets=(
        100, 500, 1_000, 5_000, 10_000, 50_000,
        100_000, 500_000, 1_000_000, 5_000_000, 10_000_000,
    ),
)

PAYMENT_TOTAL_AMOUNT_PAISE = Counter(
    "ibts_payment_total_amount_paise_total",
    "Running total of successful payment amounts in paise. "
    "rate() gives INR throughput per second.",
    [L_PAYER_BANK, L_PAYEE_BANK],
)

PAYMENT_E2E_LATENCY_SECONDS = Histogram(
    "ibts_payment_end_to_end_latency_seconds",
    "Full payment lifecycle: gateway receipt → final response. "
    "SLA: p95 < 3 s, p99 < 5 s.",
    [L_PAYEE_BANK, L_STATUS],
    buckets=(0.1, 0.25, 0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 30.0),
)

PAYMENT_ERRORS_TOTAL = Counter(
    "ibts_payment_errors_total",
    "Payment failures by error kind and bank.",
    [L_PAYEE_BANK, L_ERROR_KIND],
)

# ==============================================================================
# Idempotency Service
# ==============================================================================

IDEMPOTENCY_CHECKS_TOTAL = Counter(
    "ibts_idempotency_checks_total",
    "Key lookups by result: NEW | CACHED | STALE_PROCESSING.",
    [L_SERVICE, L_IDEM],
)

IDEMPOTENCY_DYNAMO_LATENCY_SECONDS = Histogram(
    "ibts_idempotency_dynamo_latency_seconds",
    "DynamoDB latency for idempotency get/put/update.",
    [L_SERVICE, L_OPERATION],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
)

IDEMPOTENCY_STALE_PROCESSING_TOTAL = Counter(
    "ibts_idempotency_stale_processing_total",
    "Keys found in PROCESSING state — indicates crashed transaction. "
    "Alert if > 1 % of total checks.",
    [L_SERVICE],
)

# ==============================================================================
# Payment Router / VPA Resolution
# ==============================================================================

VPA_RESOLUTION_TOTAL = Counter(
    "ibts_vpa_resolution_total",
    "VPA resolution outcomes by bank, source and success flag.",
    [L_BANK, L_ROUTE_SRC, "success"],   # success: true | false
)

VPA_RESOLUTION_LATENCY_SECONDS = Histogram(
    "ibts_vpa_resolution_latency_seconds",
    "Time to resolve a VPA. CACHE < 5 ms, DB < 50 ms.",
    [L_BANK, L_ROUTE_SRC],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5),
)

ROUTE_CACHE_OPS_TOTAL = Counter(
    "ibts_route_cache_ops_total",
    "Redis cache operations for routing: hit | miss | set | evict.",
    [L_BANK, L_OPERATION],
)

ROUTE_CACHE_HIT_RATIO = Gauge(
    "ibts_route_cache_hit_ratio",
    "Rolling route cache hit ratio (0.0-1.0). Alert below 0.7.",
    [L_SERVICE],
)

VPA_UNKNOWN_TOTAL = Counter(
    "ibts_vpa_unknown_total",
    "VPA handles that resolved to no bank (404). "
    "Spike = routing table missing entries.",
    ["handle_suffix"],
)

# ==============================================================================
# Bank Adapter
# ==============================================================================

BANK_REQUESTS_TOTAL = Counter(
    "ibts_bank_requests_total",
    "HTTP calls sent to bank endpoints by bank/type/response code.",
    [L_BANK, L_EP_TYPE, L_HTTP_CODE],
)

BANK_REQUEST_LATENCY_SECONDS = Histogram(
    "ibts_bank_request_latency_seconds",
    "Individual bank endpoint call latency.",
    [L_BANK, L_EP_TYPE],
    buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0),
)

BANK_FAILURES_TOTAL = Counter(
    "ibts_bank_failures_total",
    "Bank call failures: http_error | timeout | connection | both_failed.",
    [L_BANK, L_FAIL_TYPE],
)

BANK_FALLBACK_USED_TOTAL = Counter(
    "ibts_bank_fallback_used_total",
    "Times fallback was tried because primary failed. "
    "Sustained rate > 0 = primary endpoint degraded.",
    [L_BANK],
)

# ==============================================================================
# Circuit Breaker  (bank-adapter)
# ==============================================================================

CIRCUIT_BREAKER_STATE = Gauge(
    "ibts_circuit_breaker_state",
    "Breaker state: 0=closed, 1=open, 2=half_open.",
    [L_BANK],
)

CIRCUIT_BREAKER_FAIL_COUNT = Gauge(
    "ibts_circuit_breaker_fail_count",
    "Current consecutive failure count before trip threshold.",
    [L_BANK],
)

CIRCUIT_BREAKER_TRANSITIONS_TOTAL = Counter(
    "ibts_circuit_breaker_transitions_total",
    "State transitions: closed_to_open | open_to_half_open | "
    "half_open_to_closed | half_open_to_open.",
    [L_BANK, L_TRANSITION],
)

CIRCUIT_BREAKER_OPEN_DURATION_SECONDS = Histogram(
    "ibts_circuit_breaker_open_duration_seconds",
    "Duration breaker stayed OPEN before moving to HALF-OPEN.",
    [L_BANK],
    buckets=(10, 30, 60, 120, 300, 600, 1800),
)

CIRCUIT_BREAKER_REJECTED_TOTAL = Counter(
    "ibts_circuit_breaker_rejected_total",
    "Requests short-circuited by an OPEN breaker (never reached bank).",
    [L_BANK],
)

# ==============================================================================
# Infrastructure  (Redis + DynamoDB)  -- used across services
# ==============================================================================

REDIS_OP_LATENCY_SECONDS = Histogram(
    "ibts_redis_operation_latency_seconds",
    "Redis command latency by service and operation.",
    [L_SERVICE, L_OPERATION],
    buckets=(0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1),
)

REDIS_ERRORS_TOTAL = Counter(
    "ibts_redis_errors_total",
    "Redis operation failures. Alert immediately — cascades to DB storm.",
    [L_SERVICE, "error_type"],
)

DYNAMO_OP_LATENCY_SECONDS = Histogram(
    "ibts_dynamo_operation_latency_seconds",
    "DynamoDB operation latency by service, table, and operation.",
    [L_SERVICE, L_TABLE, L_OPERATION],
    buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
)

DYNAMO_ERRORS_TOTAL = Counter(
    "ibts_dynamo_errors_total",
    "DynamoDB failures by service, table and AWS error code.",
    [L_SERVICE, L_TABLE, "error_type"],
)
