# filename: 00-versions.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.47"
    }
    # kubernetes provider — lets Terraform talk to the cluster
    # after it's created (for namespaces, configmaps etc.)
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.29"
    }
    # helm provider — installs Helm charts (Karpenter, LB Controller)
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
    # tls — generates OIDC thumbprint for IRSA
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
} # 👈 THIS CLOSING BRACKET WAS ADDED TO FIX THE SYNTAX ERROR

# ── Primary AWS provider
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "ibts"
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# ── Kubernetes provider — authenticates using the EKS cluster token
# depends on the cluster being created first (data sources below)
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = [
      "eks", "get-token",
      "--cluster-name", module.eks.cluster_name,
      "--region", var.aws_region
    ]
  }
}

# ── Helm provider — same auth as kubernetes provider
provider "helm" {
  kubernetes {
    host                   = module.eks.cluster_endpoint
    cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

    exec {
      api_version = "client.authentication.k8s.io/v1beta1"
      command     = "aws"
      args = [
        "eks", "get-token",
        "--cluster-name", module.eks.cluster_name,
        "--region", var.aws_region
      ]
    }
  }
}
 