# filename: 00-versions.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.47"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.29"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.13"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.0"
    }
  }

  backend "s3" {
    bucket       = "sandesh-tf-file"
    key          = "ibts-eks/terraform.tfstate"
    region       = "us-east-1"
    encrypt      = true
    use_lockfile = true
  }
}

# ── AWS provider — unchanged
provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project     = "ibts"
      Environment = var.environment
      ManagedBy   = "terraform"
    }
  }
}

# ══════════════════════════════════════════════════════════════
# DATA SOURCES — read cluster details directly from AWS API
# This is the fix: providers read from AWS directly instead of
# from module outputs which are not resolved at provider init time
# ══════════════════════════════════════════════════════════════
data "aws_eks_cluster" "this" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "this" {
  name = var.cluster_name
}

# ── Kubernetes provider — reads from data source, not module output
provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.this.token
  # No exec block needed — token is fetched above via data source
}

# ── Helm provider — reads from data source, not module output
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.this.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.this.token
  }
}

# ── kubectl provider — reads from data source, not module output
provider "kubectl" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.this.token
  load_config_file       = false
}
