# filename: 02-vpc.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ── VPC — the private network boundary for everything
resource "aws_vpc" "ibts" {
  cidr_block = var.vpc_cidr

  # Required for EKS — allows pods to resolve AWS service DNS names
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = "${var.cluster_name}-vpc"
  }
}

# ── Internet Gateway — allows the PUBLIC subnet to reach internet
# ALB needs this to receive inbound traffic from Global Accelerator
resource "aws_internet_gateway" "ibts" {
  vpc_id = aws_vpc.ibts.id

  tags = {
    Name = "${var.cluster_name}-igw"
  }
}

# ── PUBLIC subnets — ALB and NAT Gateway only
# Nodes are NEVER placed here
resource "aws_subnet" "public" {
  count = length(var.availability_zones)

  vpc_id            = aws_vpc.ibts.id
  cidr_block        = var.public_subnet_cidrs[count.index]
  availability_zone = var.availability_zones[count.index]

  # ALB needs to auto-assign public IPs — required for internet-facing ALB
  map_public_ip_on_launch = true

  tags = {
    Name = "${var.cluster_name}-public-${var.availability_zones[count.index]}"

    # These tags are REQUIRED for AWS LB Controller to discover subnets
    # and know where to place internet-facing load balancers
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/elb"                    = "1"
  }
}

# ── PRIVATE subnets — all EKS nodes and pods live here
resource "aws_subnet" "private" {
  count = length(var.availability_zones)

  vpc_id            = aws_vpc.ibts.id
  cidr_block        = var.private_subnet_cidrs[count.index]
  availability_zone = var.availability_zones[count.index]

  # Nodes must NOT have public IPs — they're accessed via private network only
  map_public_ip_on_launch = false

  tags = {
    Name = "${var.cluster_name}-private-${var.availability_zones[count.index]}"

    # Required for AWS LB Controller — internal ALBs use these subnets
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb"           = "1"

    # Required for Karpenter — it uses this tag to discover which subnets
    # to launch new EC2 nodes into
    "karpenter.sh/discovery" = var.cluster_name
  }
}

# ── Elastic IP for NAT Gateway
# NAT Gateway needs a static public IP to send outbound traffic
resource "aws_eip" "nat" {
  count  = length(var.availability_zones)
  domain = "vpc"

  tags = {
    Name = "${var.cluster_name}-nat-eip-${count.index}"
  }

  depends_on = [aws_internet_gateway.ibts]
}

# ── NAT Gateway — sits in PUBLIC subnet
# Gives private subnet nodes outbound internet access
# (for Docker Hub image pulls, AWS API calls)
resource "aws_nat_gateway" "ibts" {
  count = length(var.availability_zones)

  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id

  tags = {
    Name = "${var.cluster_name}-nat-${var.availability_zones[count.index]}"
  }

  depends_on = [aws_internet_gateway.ibts]
}

# ── Route table for PUBLIC subnets
# All traffic → Internet Gateway
resource "aws_route_table" "public" {
  vpc_id = aws_vpc.ibts.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.ibts.id
  }

  tags = {
    Name = "${var.cluster_name}-rt-public"
  }
}

resource "aws_route_table_association" "public" {
  count = length(var.availability_zones)

  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}

# ── Route table for PRIVATE subnets
# All outbound traffic → NAT Gateway (not internet directly)
resource "aws_route_table" "private" {
  count  = length(var.availability_zones)
  vpc_id = aws_vpc.ibts.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.ibts[count.index].id
  }

  tags = {
    Name = "${var.cluster_name}-rt-private-${var.availability_zones[count.index]}"
  }
}

resource "aws_route_table_association" "private" {
  count = length(var.availability_zones)

  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private[count.index].id
}

# ── VPC Endpoints — CRITICAL for POC cost optimization
# ECR API endpoint — for image manifest fetching
resource "aws_vpc_endpoint" "ecr_api" {
  vpc_id              = aws_vpc.ibts.id
  service_name        = "com.amazonaws.${var.aws_region}.ecr.api"
  vpc_endpoint_type   = "Interface"
  subnet_ids          = aws_subnet.private[*].id
  security_group_ids  = [aws_security_group.vpc_endpoints.id]
  private_dns_enabled = true

  tags = { Name = "${var.cluster_name}-ecr-api-endpoint" }
}

# ECR DKR endpoint — for actual image layer downloads
resource "aws_vpc_endpoint" "ecr_dkr" {
  vpc_id              = aws_vpc.ibts.id
  service_name        = "com.amazonaws.${var.aws_region}.ecr.dkr"
  vpc_endpoint_type   = "Interface"
  subnet_ids          = aws_subnet.private[*].id
  security_group_ids  = [aws_security_group.vpc_endpoints.id]
  private_dns_enabled = true

  tags = { Name = "${var.cluster_name}-ecr-dkr-endpoint" }
}

# DynamoDB endpoint — Gateway type is FREE
resource "aws_vpc_endpoint" "dynamodb" {
  vpc_id            = aws_vpc.ibts.id
  service_name      = "com.amazonaws.${var.aws_region}.dynamodb"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = aws_route_table.private[*].id

  tags = { Name = "${var.cluster_name}-dynamodb-endpoint" }
}

# S3 endpoint — FREE Gateway type, needed for ECR image layers stored in S3
resource "aws_vpc_endpoint" "s3" {
  vpc_id            = aws_vpc.ibts.id
  service_name      = "com.amazonaws.${var.aws_region}.s3"
  vpc_endpoint_type = "Gateway"
  route_table_ids   = aws_route_table.private[*].id

  tags = { Name = "${var.cluster_name}-s3-endpoint" }
}

# ── Security Group for VPC Interface Endpoints
resource "aws_security_group" "vpc_endpoints" {
  name        = "${var.cluster_name}-vpc-endpoints-sg"
  description = "Allow HTTPS from VPC for interface endpoints"
  vpc_id      = aws_vpc.ibts.id

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = [var.vpc_cidr]
    description = "HTTPS from VPC CIDR"
  }

  # 🚀 FIXED: Added standard egress rule to allow interface responses back to subnets
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound traffic"
  }

  tags = { Name = "${var.cluster_name}-vpc-endpoints-sg" }
}
