# filename: 04-node-groups.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ==============================================================================
# EKS MANAGED SYSTEM NODE GROUP
# ==============================================================================
module "eks_system_node_group" {
  source  = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "~> 20.11"

  name            = "system"
  cluster_name    = module.eks.cluster_name
  cluster_version = module.eks.cluster_version

  # ✅ FIX 2: cluster_service_cidr is REQUIRED when using this submodule standalone
  # Without it the internal null_resource validation fails with:
  #   "local.cluster_service_cidr is empty string"
  # module.eks.cluster_service_cidr returns the CIDR EKS assigned
  # to Kubernetes Services (default: 172.20.0.0/16)
  # This is different from your VPC CIDR — it's the internal k8s service network
  cluster_service_cidr = module.eks.cluster_service_cidr

  # Single AZ for POC — avoids cross-AZ EBS volume attachment issues
  subnet_ids = [aws_subnet.private[0].id]

  min_size     = 1
  max_size     = 1
  desired_size = 1

  instance_types = [var.system_node_instance_type]
  capacity_type  = "ON_DEMAND"

  # POC: no taint on system node
  # This lets LB Controller, metrics-server, and Karpenter schedule here
  # without needing tolerations in their Helm values.
  # Production: re-add CriticalAddonsOnly taint and add tolerations
  # to system Helm charts to prevent app pods landing here.
  taints = {}

  labels = {
    role                         = "system"
    "node.kubernetes.io/purpose" = "system"
  }

  ami_type = "AL2_x86_64"

  iam_role_additional_policies = {
    AmazonEC2ContainerRegistryReadOnly = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    AmazonSSMManagedInstanceCore       = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  }

  block_device_mappings = {
    xvda = {
      device_name = "/dev/xvda"
      ebs = {
        volume_size           = 30
        volume_type           = "gp3"
        encrypted             = true
        delete_on_termination = true
      }
    }
  }

  cluster_primary_security_group_id = module.eks.cluster_primary_security_group_id
  vpc_security_group_ids            = [module.eks.node_security_group_id]

  depends_on = [module.eks]
}
