# filename: 04-node-groups.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ==============================================================================
# EKS MANAGED SYSTEM NODE GROUP
# ==============================================================================
module "eks_system_node_group" {
  source  = "terraform-aws-modules/eks/aws//modules/eks-managed-node-group"
  version = "~> 20.11"

  name            = "system"
  cluster_name    = module.eks.cluster_name
  cluster_version = module.eks.cluster_version

  # 🚀 FIXED: Added [0] index to cleanly pull the primary private subnet (ap-south-1a) from the count array
  subnet_ids = [aws_subnet.private[0].id]

  min_size     = 1
  max_size     = 1
  desired_size = 1

  instance_types = [var.system_node_instance_type]
  capacity_type  = "ON_DEMAND"

  taints = {}

  labels = {
    role                         = "system"
    "node.kubernetes.io/purpose" = "system"
  }

  ami_type = "AL2_x86_64"

  iam_role_additional_policies = {
    AmazonEC2ContainerRegistryReadOnly = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
    AmazonSSMManagedInstanceCore       = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
  }

  block_device_mappings = {
    xvda = {
      device_name = "/dev/xvda"
      ebs = {
        volume_size           = 30
        volume_type           = "gp3"
        encrypted             = true
        delete_on_termination = true
      }
    }
  }

  cluster_primary_security_group_id = module.eks.cluster_primary_security_group_id
  vpc_security_group_ids            = [module.eks.node_security_group_id]

  depends_on = [module.eks]
}
