# filename: 06-irsa.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ── Helper: look up your AWS account ID
data "aws_caller_identity" "current" {}

# ─────────────────────────────────────────────
# payment-switch
# Needs: DynamoDB (ibts-transactions) + SQS (ibts-settlement-events)
# ─────────────────────────────────────────────
module "irsa_payment_switch" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name = "${var.cluster_name}-payment-switch"

  # ── Custom policy — only what payment-switch actually needs
  role_policy_arns = {
    policy = aws_iam_policy.payment_switch.arn
  }

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      # Format: "namespace:serviceaccount-name"
      # This ties the IAM role to a SPECIFIC Kubernetes ServiceAccount
      # No other pod can assume this role
      namespace_service_accounts = ["ibts-app:payment-switch"]
    }
  }
}

resource "aws_iam_policy" "payment_switch" {
  name        = "${var.cluster_name}-payment-switch-policy"
  description = "Least privilege policy for payment-switch service"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "DynamoDBTransactions"
        Effect = "Allow"
        Action = [
          "dynamodb:GetItem",
          "dynamodb:PutItem",
          "dynamodb:UpdateItem",
          "dynamodb:Query"
        ]
        Resource = "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/ibts-transactions"
      },
      {
        Sid    = "SQSSettlement"
        Effect = "Allow"
        Action = [
          "sqs:SendMessage",
          "sqs:GetQueueUrl"
        ]
        Resource = "arn:aws:sqs:${var.aws_region}:${data.aws_caller_identity.current.account_id}:ibts-settlement-events"
      }
    ]
  })
}

# ─────────────────────────────────────────────
# payment-router
# Needs: DynamoDB (routing-table) read only
# ─────────────────────────────────────────────
module "irsa_payment_router" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name        = "${var.cluster_name}-payment-router"
  role_policy_arns = { policy = aws_iam_policy.payment_router.arn }

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["ibts-app:payment-router"]
    }
  }
}

resource "aws_iam_policy" "payment_router" {
  name        = "${var.cluster_name}-payment-router-policy"
  description = "Read-only routing table access for payment-router"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "DynamoDBRoutingTableRead"
      Effect = "Allow"
      Action = [
        "dynamodb:GetItem",
        "dynamodb:Scan",
        "dynamodb:Query"
      ]
      Resource = "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/routing-table"
    }]
  })
}

# ─────────────────────────────────────────────
# idempotency-guard
# Needs: DynamoDB (IdempotencyRecords) read + write
# ─────────────────────────────────────────────
module "irsa_idempotency_guard" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name        = "${var.cluster_name}-idempotency-guard"
  role_policy_arns = { policy = aws_iam_policy.idempotency_guard.arn }

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["ibts-app:idempotency-guard"]
    }
  }
}

resource "aws_iam_policy" "idempotency_guard" {
  name        = "${var.cluster_name}-idempotency-guard-policy"
  description = "Idempotency records access for idempotency-guard"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid    = "DynamoDBIdempotency"
      Effect = "Allow"
      Action = [
        "dynamodb:GetItem",
        "dynamodb:PutItem",
        "dynamodb:UpdateItem"
      ]
      Resource = "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/IdempotencyRecords"
    }]
  })
}
