# filename: 07-addons.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ==============================================================================
# 1. IRSA FOR AWS LOAD BALANCER CONTROLLER
# ==============================================================================
module "irsa_aws_lb_controller" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name                              = "${var.cluster_name}-aws-lb-controller"
  attach_load_balancer_controller_policy = true

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
    }
  }
}

# ==============================================================================
# 2. AWS LOAD BALANCER CONTROLLER HELM RELEASE
# ==============================================================================
resource "helm_release" "aws_lb_controller" {
  namespace  = "kube-system"
  name       = "aws-load-balancer-controller"


  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  version    = var.aws_lb_controller_version

  values = [
    yamlencode({
      clusterName = module.eks.cluster_name
      region      = var.aws_region
      vpcId       = aws_vpc.ibts.id

      serviceAccount = {
        create = true
        name   = "aws-load-balancer-controller"
        annotations = {

          "eks.amazonaws.com/role-arn" = module.irsa_aws_lb_controller.iam_role_arn
        }
      }

      # Since taints = {} on the system node, tolerations can stay empty.
      # If you re-add CriticalAddonsOnly taint in prod, add it back here:
      # tolerations = [{ key = "CriticalAddonsOnly", operator = "Exists", effect = "NoSchedule" }]
      tolerations = []

      nodeSelector = {
        "node.kubernetes.io/purpose" = "system"
      }

      enableWaf    = false
      enableWafv2  = false
      enableShield = false
      replicaCount = 1
    })
  ]

  depends_on = [
    module.eks_system_node_group,
    module.irsa_aws_lb_controller
  ]
}

# ==============================================================================
# 3. METRICS SERVER HELM RELEASE
# ==============================================================================
resource "helm_release" "metrics_server" {
  namespace  = "kube-system"
  name       = "metrics-server"

  # ✅ FIX 5: correct Helm repository for metrics-server
  # "https://github.io" resolves to nothing — Helm will fail with 404.
  # The official metrics-server chart repo is at kubernetes-sigs.github.io
  repository = "https://kubernetes-sigs.github.io/metrics-server/"
  chart      = "metrics-server"
  version    = "3.12.1"

  values = [
    yamlencode({
      tolerations = []

      nodeSelector = {
        "node.kubernetes.io/purpose" = "system"
      }

      # Required for EKS — kubelet uses self-signed certs
      # Without this flag metrics-server refuses to connect to kubelet
      # and kubectl top nodes returns "error: metrics not available yet"
      args = ["--kubelet-insecure-tls"]
    })
  ]

  depends_on = [module.eks_system_node_group]
}
