# filename: 07-addons.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ==============================================================================
# 1. IAM ROLE FOR AWS LOAD BALANCER CONTROLLER
# ==============================================================================
# It needs to create/update/delete ALBs and Target Groups in your AWS account
module "irsa_aws_lb_controller" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "~> 5.39"

  role_name                              = "${var.cluster_name}-aws-lb-controller"
  attach_load_balancer_controller_policy = true # module includes the exact policy AWS requires

  oidc_providers = {
    main = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["kube-system:aws-load-balancer-controller"]
    }
  }
}

# ==============================================================================
# 2. AWS LOAD BALANCER CONTROLLER HELM RELEASE
# ==============================================================================
# This is what turns your Kubernetes Ingress YAML into a real AWS ALB
resource "helm_release" "aws_lb_controller" {
  namespace  = "kube-system"
  name       = "aws-load-balancer-controller"
  repository = "https://github.io"
  chart      = "aws-load-balancer-controller"
  version    = var.aws_lb_controller_version

  values = [
    yamlencode({
      clusterName = module.eks.cluster_name
      region      = var.aws_region
      vpcId       = aws_vpc.ibts.id

      serviceAccount = {
        create = true
        name   = "aws-load-balancer-controller"
        annotations = {
          # IRSA annotation — links this ServiceAccount to the IAM role above
          "://amazonaws.com" = module.irsa_aws_lb_controller.iam_role_arn
        }
      }

      # 🚀 FIXED: Cleared the 'CriticalAddonsOnly' toleration constraint to align with the untainted system nodes
      tolerations = []

      nodeSelector = {
        "node.kubernetes.io/purpose" = "system"
      }

      # Enable WAF integration readiness (for future prod)
      enableWaf    = false
      enableWafv2  = false
      enableShield = false

      replicaCount = 1 # POC: 1; prod: 2
    })
  ]

  depends_on = [
    module.eks_system_node_group,
    module.irsa_aws_lb_controller
  ]
}

# ==============================================================================
# 3. METRICS SERVER HELM CONFIGURATION
# ==============================================================================
# Provides real-time CPU/memory data for debugging tools and HPA configurations
resource "helm_release" "metrics_server" {
  namespace  = "kube-system"
  name       = "metrics-server"
  repository = "https://github.io"
  chart      = "metrics-server"
  version    = "3.12.1"

  values = [
    yamlencode({
      # 🚀 FIXED: Cleared the toleration block constraint so pods can schedule instantly
      tolerations = []

      nodeSelector = {
        "node.kubernetes.io/purpose" = "system"
      }

      # Required for EKS — kubelet uses self-signed certs
      args = ["--kubelet-insecure-tls"]
    })
  ]

  depends_on = [module.eks_system_node_group]
}
