# filename: 09-outputs.tf
# Code Generated by Sidekick is for learning and experimentation purposes only.

output "cluster_name" {
  description = "EKS cluster name — use in kubectl and AWS CLI commands"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "EKS API server endpoint"
  value       = module.eks.cluster_endpoint
  sensitive   = true
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded cluster CA — needed for kubeconfig"
  value       = module.eks.cluster_certificate_authority_data
  sensitive   = true
}

output "oidc_provider_arn" {
  description = "OIDC provider ARN — needed when adding more IRSA roles"
  value       = module.eks.oidc_provider_arn
}

output "configure_kubectl_command" {
  description = "Run this command to configure kubectl after apply"
  value       = "aws eks update-kubeconfig --region ${var.aws_region} --name ${module.eks.cluster_name}"
}

output "vpc_id" {
  description = "VPC ID — needed for additional security group rules"
  value       = aws_vpc.ibts.id
}

output "private_subnet_ids" {
  description = "Private subnet IDs — for any additional node groups"
  value       = aws_subnet.private[*].id
}

# 🚀 TEMPORARILY COMMENTED OUT: Will be un-commented once the 05-karpenter.tf file is created
# output "karpenter_node_role_name" {
#   description = "IAM role name Karpenter-provisioned nodes will assume"
#   value       = module.karpenter.node_iam_role_name
# }

output "irsa_payment_switch_role_arn" {
  description = "IAM role ARN for payment-switch pods"
  value       = module.irsa_payment_switch.iam_role_arn
}

output "irsa_payment_router_role_arn" {
  description = "IAM role ARN for payment-router pods"
  value       = module.irsa_payment_router.iam_role_arn
}

output "irsa_idempotency_guard_role_arn" {
  description = "IAM role ARN for idempotency-guard pods"
  value       = module.irsa_idempotency_guard.iam_role_arn
}
