# filename: terraform.tfvars
# Code Generated by Sidekick is for learning and experimentation purposes only.

# ── Region & Identity
aws_region   = "ap-south-1"
environment  = "poc"
cluster_name = "ibts-eks"

# ── Kubernetes version — pin this, never leave it floating
cluster_version = "1.30"

# ── VPC Networking
vpc_cidr             = "10.0.0.0/16"

# 🚀 FIXED: Expanded to two AZs to pass the strict AWS EKS API control plane validation check.
# (Your actual worker nodes will still be safely restricted to ap-south-1a inside 04-node-groups.tf).
availability_zones   = ["ap-south-1a", "ap-south-1b"]     
private_subnet_cidrs = ["10.0.10.0/24", "10.0.11.0/24"]   # nodes + pods live here
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]    # ALB + NAT Gateway live here

# ── System node — On-Demand, always running
# t3.medium = 2 vCPU / 4GB RAM
# Hosts: CoreDNS, kube-proxy, Karpenter, LB Controller, metrics-server
system_node_instance_type = "t3.medium"

# ── Karpenter Spot pool — workload nodes
# Multiple families = fewer simultaneous interruptions
karpenter_spot_instance_families = ["t3", "t3a", "t2"]
karpenter_spot_instance_sizes    = ["medium", "large"]

# ── Tool versions — pin these for reproducibility
karpenter_version         = "0.36.2"
aws_lb_controller_version = "1.8.1"
