# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/init_resources.py

import boto3, time, logging, sys
from app.config import settings

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

def create_table(ddb):
    try:
        ddb.create_table(
            TableName=settings.dynamodb_table_name,
            KeySchema=[{"AttributeName": "txn_id", "KeyType": "HASH"}],
            AttributeDefinitions=[{"AttributeName": "txn_id", "AttributeType": "S"}],
            BillingMode="PAY_PER_REQUEST",
        )
        log.info("Table '%s' created", settings.dynamodb_table_name)
    except ddb.meta.client.exceptions.ResourceInUseException:
        log.info("Table '%s' already exists", settings.dynamodb_table_name)

def create_queue(sqs):
    try:
        sqs.create_queue(QueueName=settings.sqs_queue_name)
        log.info("SQS queue '%s' created", settings.sqs_queue_name)
    except Exception as exc:
        log.warning("SQS queue creation skipped: %s", exc)

def main():
    for attempt in range(10):
        try:
            ddb = boto3.resource(
                "dynamodb",
                endpoint_url=settings.dynamodb_endpoint_url,
                region_name=settings.aws_default_region,
                aws_access_key_id=settings.aws_access_key_id,
                aws_secret_access_key=settings.aws_secret_access_key,
            )
            sqs = boto3.client(
                "sqs",
                endpoint_url=settings.sqs_endpoint_url,
                region_name=settings.aws_default_region,
                aws_access_key_id=settings.aws_access_key_id,
                aws_secret_access_key=settings.aws_secret_access_key,
            )
            create_table(ddb)
            create_queue(sqs)
            log.info("Resources ready"); sys.exit(0)
        except Exception as exc:
            log.warning("Attempt %d failed: %s", attempt + 1, exc)
            time.sleep(5)
    log.error("Resource init failed"); sys.exit(1)

if __name__ == "__main__":
    main()
