# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/main.py

import logging
from fastapi import FastAPI
from app.routers.payments import router as payments_router
from app.config import settings

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s — %(message)s")

app = FastAPI(title="IBTS Payment Switch", version="1.0.0")
app.include_router(payments_router)

@app.get("/actuator/health")
def health():
    return {"status": "UP", "service": "payment-switch"}
