# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/main.py

from shared.telemetry import setup_telemetry   # â† line 1
setup_telemetry()

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from starlette.routing import Mount
from prometheus_client import make_asgi_app

from metrics.middleware import MetricsMiddleware
from app.routers.payments import router as payments_router
from app.config import settings

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s â€” %(message)s",
)
log = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("payment-switch startup complete")
    yield
    log.info("payment-switch shutting down")


app = FastAPI(
    title="IBTS Payment Switch",
    version="1.0.0",
    lifespan=lifespan,
    routes=[Mount("/metrics", make_asgi_app())],           # â† fixes 404
)

# MetricsMiddleware still instruments every request â€” just the scrape
# endpoint is now served by make_asgi_app() instead of metrics_router
app.add_middleware(MetricsMiddleware, service_name="payment-switch")

app.include_router(payments_router)


@app.get("/actuator/health", tags=["ops"])
def health():
    return {"status": "UP", "service": "payment-switch"}

