# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/test-payment-switch.ps1

param([string]$BaseUrl = "http://localhost:8083")

$pass = 0; $fail = 0

function Assert-Pass { param([string]$L) Write-Host "  [PASS] $L" -ForegroundColor Green;  $script:pass++ }
function Assert-Fail { param([string]$L, [string]$D="") Write-Host "  [FAIL] $L $D" -ForegroundColor Red; $script:fail++ }

function Invoke-Api {
    param([string]$Uri, [string]$Method="GET", [string]$Body=$null)
    $p = @{ Uri=$Uri; Method=$Method; ContentType="application/json"; ErrorAction="Stop" }
    if ($Body) { $p.Body = $Body }
    return Invoke-RestMethod @p
}

function Test-Case { param([string]$Id, [string]$Desc)
    Write-Host "`n[$Id] $Desc" -ForegroundColor Cyan
}

$key1 = "idem-key-$(Get-Random)"
$key2 = "idem-key-$(Get-Random)"
$key3 = "idem-key-$(Get-Random)"

# T01
Test-Case "T01" "Health check"
try {
    $r = Invoke-Api -Uri "$BaseUrl/actuator/health"
    if ($r.status -eq "UP") { Assert-Pass "status=UP" }
    else { Assert-Fail "Expected UP" $r.status }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T02
Test-Case "T02" "New payment → john@sbi → SUCCESS"
try {
    $body = @{ idempotency_key=$key1; payer_vpa="alice@okicici"; payee_vpa="john@sbi"; amount_paise=50000; remarks="Test T02" } | ConvertTo-Json
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    if ($r.status -eq "SUCCESS" -and $r.source -eq "NEW" -and $r.txn_id) {
        Assert-Pass "SUCCESS txn_id=$($r.txn_id) rrn=$($r.bank_rrn)"
        $script:txnId = $r.txn_id
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T03
Test-Case "T03" "Same idempotency key → CACHED response"
try {
    $body = @{ idempotency_key=$key1; payer_vpa="alice@okicici"; payee_vpa="john@sbi"; amount_paise=50000 } | ConvertTo-Json
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    if ($r.source -eq "CACHED" -and $r.txn_id -eq $script:txnId) {
        Assert-Pass "CACHED same txn_id=$($r.txn_id)"
    } else { Assert-Fail "Expected CACHED" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T04
Test-Case "T04" "GET /payments/{txn_id} → DB record"
try {
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/payments/$($script:txnId)"
    if ($r.txn_id -eq $script:txnId -and $r.status -eq "SUCCESS") {
        Assert-Pass "DB record found status=SUCCESS"
    } else { Assert-Fail "Unexpected" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# T05
Test-Case "T05" "Unknown payee VPA → 404"
try {
    $body = @{ idempotency_key=$key2; payer_vpa="alice@okicici"; payee_vpa="john@unknownxyz"; amount_paise=10000 } | ConvertTo-Json
    Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    Assert-Fail "Expected 404 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 404) { Assert-Pass "404 unresolvable VPA" }
    else { Assert-Fail "Wrong status: $code" }
}

# T06
Test-Case "T06" "Zero amount → 422 validation"
try {
    $body = @{ idempotency_key=$key3; payer_vpa="alice@okicici"; payee_vpa="john@sbi"; amount_paise=0 } | ConvertTo-Json
    Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    Assert-Fail "Expected 422 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 422) { Assert-Pass "422 zero amount rejected" }
    else { Assert-Fail "Wrong status: $code" }
}

# T07
Test-Case "T07" "Missing idempotency_key → 422"
try {
    $body = @{ payer_vpa="alice@okicici"; payee_vpa="john@sbi"; amount_paise=10000 } | ConvertTo-Json
    Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    Assert-Fail "Expected 422 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 422) { Assert-Pass "422 missing key rejected" }
    else { Assert-Fail "Wrong status: $code" }
}

# T08
Test-Case "T08" "Invalid VPA format → 422"
try {
    $body = @{ idempotency_key="key-bad-vpa"; payer_vpa="notavpa"; payee_vpa="john@sbi"; amount_paise=10000 } | ConvertTo-Json
    Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    Assert-Fail "Expected 422 but got 200"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 422) { Assert-Pass "422 bad VPA format" }
    else { Assert-Fail "Wrong status: $code" }
}

# T09
Test-Case "T09" "GET non-existent txn_id → 404"
try {
    Invoke-Api -Uri "$BaseUrl/api/v1/payments/non-existent-id-9999"
    Assert-Fail "Expected 404"
} catch {
    $code = $_.Exception.Response.StatusCode.value__
    if ($code -eq 404) { Assert-Pass "404 txn not found" }
    else { Assert-Fail "Wrong status: $code" }
}

# T10
Test-Case "T10" "HDFC payee route → SUCCESS"
try {
    $k = "idem-hdfc-$(Get-Random)"
    $body = @{ idempotency_key=$k; payer_vpa="alice@sbi"; payee_vpa="bob@okhdfcbank"; amount_paise=100000 } | ConvertTo-Json
    $r = Invoke-Api -Uri "$BaseUrl/api/v1/payments/initiate" -Method POST -Body $body
    if ($r.status -eq "SUCCESS") { Assert-Pass "HDFC route SUCCESS rrn=$($r.bank_rrn)" }
    else { Assert-Fail "Expected SUCCESS" ($r | ConvertTo-Json -Compress) }
} catch { Assert-Fail "Request failed" $_.Exception.Message }

# ── Summary ────────────────────────────────────────────────────────────────
$total = $pass + $fail
Write-Host "`n======================================" -ForegroundColor White
Write-Host " RESULTS: $pass/$total passed" -ForegroundColor $(if ($fail -eq 0){"Green"}else{"Yellow"})
if ($fail -gt 0) { Write-Host " $fail test(s) FAILED" -ForegroundColor Red }
else             { Write-Host " All tests passed - payment-switch healthy" -ForegroundColor Green }
Write-Host "======================================`n" -ForegroundColor White
