# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/clients/adapter.py

import httpx, logging
from app.config import settings

log = logging.getLogger(__name__)
_BASE = settings.bank_adapter_url


async def send_payment(
    txn_id: str,
    bank_code: str,
    primary_endpoint: str,
    fallback_endpoint: str,
    amount_paise: int,
    payer_vpa: str,
    payee_vpa: str,
    remarks: str | None,
) -> dict:
    """Returns AdapterResponse dict: {transactionId, status, bankReferenceId, ...}"""
    payload = {
        "transactionId":    txn_id,
        "bankCode":         bank_code,
        "primaryEndpoint":  primary_endpoint,
        "fallbackEndpoint": fallback_endpoint,
        "amount":           round(amount_paise / 100, 2),  # paise → rupees
        "currency":         "INR",
        "payerVpa":         payer_vpa,
        "payeeVpa":         payee_vpa,
        "remarks":          remarks or "",
    }
    async with httpx.AsyncClient(timeout=10.0) as c:
        r = await c.post(f"{_BASE}/api/v1/adapter/send", json=payload)
        r.raise_for_status()
        return r.json()
