# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/clients/idempotency.py

import httpx
import logging
from app.config import settings

log = logging.getLogger(__name__)
_BASE = settings.idempotency_guard_url
_SERVICE = "payment-switch"


async def check(key: str) -> dict:
    """
    Returns CheckResponse dict.
    Guard returns 200 for NEW, 409 for DUPLICATE — both are valid business
    responses; only 4xx/5xx other than 409 are true errors.
    """
    async with httpx.AsyncClient(timeout=3.0) as c:
        r = await c.post(
            f"{_BASE}/api/v1/idempotency/check",
            headers={
                "X-Idempotency-Key": key,
                "X-Caller-Service": _SERVICE,
            },
            json={"transactionRefId": key},
        )
        if r.status_code == 409:          # ← DUPLICATE: valid, don't raise
            return r.json()
        r.raise_for_status()              # raises on other 4xx/5xx
        return r.json()


async def complete(
    transaction_id: str,
    final_status: str,
    response_payload: str | None = None,
) -> None:
    async with httpx.AsyncClient(timeout=3.0) as c:
        r = await c.post(
            f"{_BASE}/api/v1/idempotency/complete",
            json={
                "transactionId": transaction_id,
                "finalStatus": final_status,
                "responsePayload": response_payload,
            },
        )
        r.raise_for_status()
