# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/clients/router.py

import httpx, logging
from app.config import settings

log = logging.getLogger(__name__)
_BASE = settings.payment_router_url

async def resolve_vpa(vpa: str) -> dict:
    """Returns {bankCode, primaryEndpoint, fallbackEndpoint}"""
    async with httpx.AsyncClient(timeout=3.0) as c:
        r = await c.post(f"{_BASE}/api/v1/route/resolve", json={"vpa": vpa})
        r.raise_for_status()
        return r.json()
