# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/routers/payments.py

import asyncio
import json
import logging
import time

import httpx
from fastapi import APIRouter, HTTPException

from app import dynamo, sqs
from app.clients import adapter as adp_client
from app.clients import idempotency as idm_client
from app.clients import router as rtr_client
from app.models import PaymentRequest, PaymentResponse, TxnRecord, TxnState
from app.payment_metrics import (
    payment_timer,
    record_bank_request,
    record_duplicate_debit,
    record_idempotency,
    record_state_corruption,
)

log     = logging.getLogger(__name__)
router  = APIRouter(prefix="/api/v1/payments", tags=["payments"])
_SERVICE = "payment-switch"


@router.post("/initiate", response_model=PaymentResponse)
async def initiate_payment(req: PaymentRequest):

    # ── Step 1: Idempotency check ──────────────────────────────────────────────
    try:
        idm = await idm_client.check(req.idempotency_key)
    except Exception as exc:
        log.error("idempotency-guard unreachable: %s", exc)
        raise HTTPException(503, "idempotency-guard unavailable")

    if idm.get("duplicate"):
        record_idempotency(_SERVICE, "CACHED")               # ← METRIC

        cached_raw = idm.get("responsePayload")

        # Fast path — guard echoed the serialised payload back
        if cached_raw:
            cached = (
                json.loads(cached_raw)
                if isinstance(cached_raw, str)
                else cached_raw
            )
            return PaymentResponse(
                txn_id   = cached.get("txn_id", ""),
                status   = cached.get("status", "SUCCESS"),
                bank_rrn = cached.get("bank_rrn"),
                message  = cached.get("message", ""),
                source   = "CACHED",
            )

        # Slow path — guard returned no payload; look up via GSI
        log.warning(
            "responsePayload absent on duplicate; querying GSI key=%s",
            req.idempotency_key,
        )
        record = dynamo.get_txn_by_idempotency_key(req.idempotency_key)
        if record:
            return PaymentResponse(
                txn_id   = record["txn_id"],
                status   = record["state"],
                bank_rrn = record.get("bank_rrn"),
                message  = record.get("error") or record["state"],
                source   = "CACHED",
            )

        # Duplicate key but no record — data integrity violation
        log.error(
            "Duplicate key but no DynamoDB record found for key=%s",
            req.idempotency_key,
        )
        record_state_corruption(                             # ← METRIC
            service   = _SERVICE,
            violation = "duplicate_key_no_dynamo_record",
        )
        raise HTTPException(
            500, "Duplicate request — original transaction not recoverable"
        )

    # ── NEW request ────────────────────────────────────────────────────────────
    record_idempotency(_SERVICE, "NEW")                      # ← METRIC

    # ── Step 2: Create transaction record ─────────────────────────────────────
    txn = TxnRecord(
        idempotency_key = req.idempotency_key,
        payer_vpa       = req.payer_vpa,
        payee_vpa       = req.payee_vpa,
        amount_paise    = req.amount_paise,
        remarks         = req.remarks,
    )
    dynamo.write_txn(txn)

    # ── Step 3: Resolve payee VPA → bank endpoint ──────────────────────────────
    try:
        route = await rtr_client.resolve_vpa(req.payee_vpa)
    except httpx.HTTPStatusError as exc:
        dynamo.update_state(txn.txn_id, TxnState.FAILED, error="VPA unresolvable")
        raise HTTPException(
            exc.response.status_code,
            f"VPA resolution failed: {req.payee_vpa}",
        )
    except Exception as exc:
        dynamo.update_state(txn.txn_id, TxnState.FAILED, error=str(exc))
        raise HTTPException(503, "payment-router unavailable")

    bank_code         = route["bankCode"]
    primary_endpoint  = route.get("primaryEndpoint", "")
    fallback_endpoint = route.get("fallbackEndpoint", "")

    # ── Step 4: Mark PROCESSING ────────────────────────────────────────────────
    dynamo.update_state(txn.txn_id, TxnState.PROCESSING, bank_code=bank_code)

    # ── Steps 5-7 wrapped in payment_timer ────────────────────────────────────
    # On exit (any outcome) auto-records:
    #   PAYMENT_INITIATED_TOTAL, PAYMENT_E2E_LATENCY_SECONDS,
    #   PAYMENT_AMOUNT_PAISE, PAYMENT_ERRORS_TOTAL
    async with payment_timer(
        payer_vpa    = req.payer_vpa,
        payee_vpa    = req.payee_vpa,
        amount_paise = req.amount_paise,
        idem_result  = "NEW",
        service      = _SERVICE,
    ) as ctx:

        ctx.bank_code = bank_code

        # ── Step 5: Call bank adapter ──────────────────────────────────────────
        bank_start = time.perf_counter()
        try:
            bank_resp = await adp_client.send_payment(
                txn_id            = txn.txn_id,
                bank_code         = bank_code,
                primary_endpoint  = primary_endpoint,
                fallback_endpoint = fallback_endpoint,
                amount_paise      = req.amount_paise,
                payer_vpa         = req.payer_vpa,
                payee_vpa         = req.payee_vpa,
                remarks           = req.remarks,
            )
            record_bank_request(                             # ← METRIC (success)
                bank_code     = bank_code,
                endpoint_type = "primary",
                http_code     = "200",
                duration_s    = time.perf_counter() - bank_start,
            )

        except TimeoutError:
            record_bank_request(                             # ← METRIC (timeout)
                bank_code     = bank_code,
                endpoint_type = "primary",
                http_code     = "timeout",
                duration_s    = time.perf_counter() - bank_start,
                failed        = True,
                fail_type     = "timeout",
            )
            dynamo.update_state(txn.txn_id, TxnState.FAILED, error="bank timeout")
            # ✅ Set BEFORE raise — payment_timer now preserves UNKNOWN
            ctx.status     = "UNKNOWN"
            ctx.error_kind = "timeout"
            raise HTTPException(504, "bank-adapter timeout")

        except httpx.HTTPStatusError as exc:
            record_bank_request(                             # ← METRIC (http error)
                bank_code     = bank_code,
                endpoint_type = "primary",
                http_code     = str(exc.response.status_code),
                duration_s    = time.perf_counter() - bank_start,
                failed        = True,
                fail_type     = "http_error",
            )
            dynamo.update_state(txn.txn_id, TxnState.FAILED, error=str(exc))
            ctx.status     = "FAILED"
            ctx.error_kind = "bank_error"
            raise HTTPException(502, "bank-adapter http error")

        except Exception as exc:
            record_bank_request(                             # ← METRIC (connection)
                bank_code     = bank_code,
                endpoint_type = "primary",
                http_code     = "connection_error",
                duration_s    = time.perf_counter() - bank_start,
                failed        = True,
                fail_type     = "connection",
            )
            dynamo.update_state(txn.txn_id, TxnState.FAILED, error=str(exc))
            ctx.status     = "FAILED"
            ctx.error_kind = "internal"
            raise HTTPException(502, "bank-adapter call failed")

        adapter_status = bank_resp.get("status", "FAILED")
        bank_rrn       = bank_resp.get("bankReferenceId")

        # ── Step 6: Finalise state ─────────────────────────────────────────────
        final_state = (
            TxnState.SUCCESS if adapter_status == "SUCCESS" else TxnState.FAILED
        )
        dynamo.update_state(txn.txn_id, final_state, bank_rrn=bank_rrn)

        ctx.status     = final_state.value                   # ← SUCCESS | FAILED
        ctx.error_kind = None if final_state == TxnState.SUCCESS else "bank_error"

        # Duplicate debit guard (requires bank_rrn GSI on DynamoDB table)
        if final_state == TxnState.SUCCESS and bank_rrn:
            existing = dynamo.get_txn_by_bank_rrn(bank_rrn)
            if existing and existing["txn_id"] != txn.txn_id:
                log.error(
                    "Duplicate debit detected bank_rrn=%s txn=%s collision=%s",
                    bank_rrn, txn.txn_id, existing["txn_id"],
                )
                record_duplicate_debit(                      # ← METRIC
                    service        = _SERVICE,
                    detection_type = "bank_rrn_collision",
                )

        response = PaymentResponse(
            txn_id   = txn.txn_id,
            status   = final_state,
            bank_rrn = bank_rrn,
            message  = bank_resp.get("errorMessage") or adapter_status,
            source   = "NEW",
        )

        # ── Step 7: Cache result + async settlement emit ───────────────────────
        await idm_client.complete(
            transaction_id   = txn.txn_id,
            final_status     = final_state.value,
            response_payload = response.model_dump_json(),
        )

        if final_state == TxnState.SUCCESS:
            asyncio.create_task(
                asyncio.to_thread(
                    sqs.emit_settlement_event,
                    txn.txn_id,
                    bank_code,
                    req.amount_paise,
                )
            )

    if final_state == TxnState.FAILED:
        raise HTTPException(502, response.message)

    return response


@router.get("/{txn_id}", response_model=PaymentResponse)
async def get_payment(txn_id: str):
    record = dynamo.get_txn(txn_id)
    if not record:
        raise HTTPException(404, f"Transaction {txn_id} not found")
    return PaymentResponse(
        txn_id   = record["txn_id"],
        status   = record["state"],
        bank_rrn = record.get("bank_rrn"),
        message  = record.get("error") or record["state"],
        source   = "DB",
    )
