# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: payment-switch/app/routers/payments.py

import asyncio, json, logging
import httpx
from fastapi import APIRouter, HTTPException
from app.models import PaymentRequest, PaymentResponse, TxnRecord, TxnState
from app.clients import idempotency as idm_client
from app.clients import router     as rtr_client
from app.clients import adapter    as adp_client
from app import dynamo, sqs

log    = logging.getLogger(__name__)
router = APIRouter(prefix="/api/v1/payments", tags=["payments"])


@router.post("/initiate", response_model=PaymentResponse)
async def initiate_payment(req: PaymentRequest):

    # ── Step 1: Idempotency check ─────────────────────────────────────────
    try:
        idm = await idm_client.check(req.idempotency_key)
    except Exception as exc:
        log.error("idempotency-guard unreachable: %s", exc)
        raise HTTPException(503, "idempotency-guard unavailable")

    if idm.get("duplicate"):
        cached_raw = idm.get("responsePayload")

        # Fast path — guard echoed the serialised payload back
        if cached_raw:
            cached = json.loads(cached_raw) if isinstance(cached_raw, str) else cached_raw
            return PaymentResponse(
                txn_id=cached.get("txn_id", ""),
                status=cached.get("status", "SUCCESS"),
                bank_rrn=cached.get("bank_rrn"),
                message=cached.get("message", ""),
                source="CACHED",
            )

        # Slow path — guard returned no payload; look up by idempotency key via GSI
        # NOTE: idm.get("transactionId") is the guard's internal key, NOT our txn_id UUID
        log.warning("responsePayload absent on duplicate; querying GSI key=%s", req.idempotency_key)
        record = dynamo.get_txn_by_idempotency_key(req.idempotency_key)
        if record:
            return PaymentResponse(
                txn_id=record["txn_id"],
                status=record["state"],
                bank_rrn=record.get("bank_rrn"),
                message=record.get("error") or record["state"],
                source="CACHED",
            )

        log.error("Duplicate key but no DynamoDB record found for key=%s", req.idempotency_key)
        raise HTTPException(500, f"Duplicate request — original transaction not recoverable")

    # ── Step 2: Create transaction record ─────────────────────────────────
    txn = TxnRecord(
        idempotency_key=req.idempotency_key,
        payer_vpa=req.payer_vpa,
        payee_vpa=req.payee_vpa,
        amount_paise=req.amount_paise,
        remarks=req.remarks,
    )
    dynamo.write_txn(txn)

    # ── Step 3: Resolve payee VPA → bank endpoint ─────────────────────────
    try:
        route = await rtr_client.resolve_vpa(req.payee_vpa)
    except httpx.HTTPStatusError as exc:
        dynamo.update_state(txn.txn_id, TxnState.FAILED, error="VPA unresolvable")
        raise HTTPException(exc.response.status_code, f"VPA resolution failed: {req.payee_vpa}")
    except Exception as exc:
        dynamo.update_state(txn.txn_id, TxnState.FAILED, error=str(exc))
        raise HTTPException(503, "payment-router unavailable")

    bank_code         = route["bankCode"]
    primary_endpoint  = route.get("primaryEndpoint", "")
    fallback_endpoint = route.get("fallbackEndpoint", "")

    # ── Step 4: Mark PROCESSING ───────────────────────────────────────────
    dynamo.update_state(txn.txn_id, TxnState.PROCESSING, bank_code=bank_code)

    # ── Step 5: Call bank adapter ─────────────────────────────────────────
    try:
        bank_resp = await adp_client.send_payment(
            txn_id=txn.txn_id,
            bank_code=bank_code,                       # ← new
            primary_endpoint=primary_endpoint,         # ← split from single endpoint
            fallback_endpoint=fallback_endpoint,       # ← split from single endpoint
            amount_paise=req.amount_paise,
            payer_vpa=req.payer_vpa,
            payee_vpa=req.payee_vpa,
            remarks=req.remarks,
        )
    except Exception as exc:
        dynamo.update_state(txn.txn_id, TxnState.FAILED, error=str(exc))
        raise HTTPException(502, "bank-adapter call failed")

    adapter_status = bank_resp.get("status", "FAILED")
    bank_rrn       = bank_resp.get("bankReferenceId")  # ← was "rrn"

    # ── Step 6: Finalise state ────────────────────────────────────────────
    final_state = TxnState.SUCCESS if adapter_status == "SUCCESS" else TxnState.FAILED
    dynamo.update_state(txn.txn_id, final_state, bank_rrn=bank_rrn)

    response = PaymentResponse(
        txn_id=txn.txn_id,
        status=final_state,
        bank_rrn=bank_rrn,
        message=bank_resp.get("errorMessage") or adapter_status,  # ← richer error
        source="NEW",
    )

    # ── Step 7: Cache result + async settlement emit ──────────────────────
    await idm_client.complete(
        transaction_id=txn.txn_id,
        final_status=final_state.value,
        response_payload=response.model_dump_json(),
    )

    if final_state == TxnState.SUCCESS:
        asyncio.create_task(
            asyncio.to_thread(sqs.emit_settlement_event, txn.txn_id, bank_code, req.amount_paise)
        )

    if final_state == TxnState.FAILED:
        raise HTTPException(502, response.message)

    return response


@router.get("/{txn_id}", response_model=PaymentResponse)
async def get_payment(txn_id: str):
    record = dynamo.get_txn(txn_id)
    if not record:
        raise HTTPException(404, f"Transaction {txn_id} not found")
    return PaymentResponse(
        txn_id=record["txn_id"],
        status=record["state"],
        bank_rrn=record.get("bank_rrn"),
        message=record.get("error") or record["state"],
        source="DB",
    )
